### ISSUE TITLE
Report on missing names/subjects excluded from initial Subject report

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damsmanager#107]
Per @arwenhutt:

```
What we would need is a report on any names (or subjects if there are any of those) which were not included in the initial reports. 
```

@lsitu suspects there were predicates that were not included when the initial subject report was created. Please provide this supplemental report.

**Comment by arwenhutt** [comment]
@lsitu could you give me an update on how this is progressing?  Thanks!

**Comment by lsitu** [comment]
@arwenhutt I think it's done for mads:Name and mads:PersonalName. Now it's on mads:CorporateName, which hits 14273 records for corporate name. My process is still running for it. I think the SPARQLs to query the counts for each Relationship for the records count is slow.

**Comment by arwenhutt** [comment]
Thanks for the report Longshou! If the mads:Name and mads:PersonalName reports are available, we might be able to go ahead and get the ball rolling on those.

**Comment by lsitu** [comment]
@arwenhutt Attached are the reports for mads:Name and mads:PersonalName, which are found in the Relationship but not in subject name (dams:name, dams:personalName). And I think all these names should not be included in our last report.
[missing-Name.txt](https://github.com/ucsdlib/damsmanager/files/564890/missing-Name.txt)
[missing-PersonalName.txt](https://github.com/ucsdlib/damsmanager/files/564889/missing-PersonalName.txt)

**Comment by lsitu** [comment]
@arwenhutt Just let you know that the report for mods:CorporateName got interrupted with error "org.apache.http.NoHttpResponseException: The target server failed to respond" this morning after running for several days. 
I am re-running my process to generate the report for mods:CorporateName now.

**Comment by lsitu** [comment]
@arwenhutt Attached missing-CorporateName.txt is the report for mads:CorporateName that are found in the Relationship but not in subject name dams:corporateName).
And I also compare the subjects names reported last time and found some records that are in the subject names but not included in our last report, see attachments 
[missing-CorporateName.txt](https://github.com/ucsdlib/damsmanager/files/577000/missing-CorporateName.txt)
[CorporateName-additional.txt](https://github.com/ucsdlib/damsmanager/files/577001/CorporateName-additional.txt)
[Name-additional.txt](https://github.com/ucsdlib/damsmanager/files/577003/Name-additional.txt)
[PersonalName-additional.txt](https://github.com/ucsdlib/damsmanager/files/577002/PersonalName-additional.txt)



PersonalName-additional.txt, CorporateName-additional.txt, Name-additional.txt.

**Comment by remerjohnson** [comment]
@lsitu I'm having problems with these attachments. Although they report at being UTF-8, the names are badly encoded and corrupted. There's also some with some abnormalities that make it so it cannot be opened as tab-separated. Is there a way to get these to come out clean encoding-wise?

**Comment by lsitu** [comment]
@remerjohnson What tool do you use to open the files?

**Comment by remerjohnson** [comment]
@lsitu So far Mousepad and LibreOffice Calc (on Xubuntu)

**Comment by lsitu** [comment]
@remerjohnson Does it work with the first file missing-CorporateName.txt?

**Comment by remerjohnson** [comment]
@lsitu The encoding on that file seems to be non-corrupt, but LibreOffice Calc complains that a cell exceeds the allowable length and so does not split at tabs properly (at line 240 it breaks and the whole doc becomes one column)

**Comment by remerjohnson** [comment]
@lsitu I think it might be due to line 241 being a quoted value, which throws off the quoting of values. I can tweak that, but there's still the issue of bad encoding for names.

**Comment by lsitu** [comment]
Hmm, interesting. Do you see just several of the names corrupted or all names that have diacritic are corrupted in the first file missing-CorporateName.txt?

**Comment by remerjohnson** [comment]
In missing-CorporateName.txt, the diacritics are fine and correct. In CorporateName-additional.txt, however, diacritics are garbled.

**Comment by lsitu** [comment]
@remerjohnson Could you try the following attachments to see whether it works? Thanks.
[CorporateName-additional.txt](https://github.com/ucsdlib/damsmanager/files/598299/CorporateName-additional.txt)
[Name-additional.txt](https://github.com/ucsdlib/damsmanager/files/598300/Name-additional.txt)
[PersonalName-additional.txt](https://github.com/ucsdlib/damsmanager/files/598301/PersonalName-additional.txt)

**Comment by remerjohnson** [comment]
@lsitu The first two files are fine, but PersonalName-additional.txt has an unknown encoding...

**Comment by lsitu** [comment]
@remerjohnson How about the following attachment?
[PersonalName-additional.txt](https://github.com/ucsdlib/damsmanager/files/598336/PersonalName-additional.txt)

**Comment by remerjohnson** [comment]
@lsitu Still "unknown". I can open it in Windows notepad or force Calc to open as UTF-8, but there's about 5 names that are corrupt...

**Comment by lsitu** [comment]
Hmm, it looks like something is messing up when I am merging the for the diff. Let's see how this one goes:
[PersonalName-additional.txt](https://github.com/ucsdlib/damsmanager/files/598450/PersonalName-additional.txt)

**Comment by remerjohnson** [comment]
Still invalid/unknown. I wonder if there's some character in the file that throws everything off?

**Comment by lsitu** [comment]
@remerjohnson Not sure what's going wrong but it looks good when I open the last attachment https://github.com/ucsdlib/damsmanager/files/598450/PersonalName-additional.txt with Notpad++.
Could you convert it at you end to see how it goes?

**Comment by remerjohnson** [comment]
Okay I can convert things. I would like a final listing of all the names though, if that's possible. Thanks

**Comment by lsitu** [comment]
@remerjohnson Do you mean a file with the names from all the name types in it, or one file for each name type? I am not sure whether there are something newly ingested since my last report but I can generate the report again, which could include some new names if that works.

**Comment by remerjohnson** [comment]
Well, just to the original issue: a collection of all the files, since this ticket is now pointing to a lot of different files. We've been trying to be diligent about getting new names reconciled before ingest, so it wouldn't have to be super recent.

**Comment by lsitu** [comment]
@remerjohnson Okay, I just merged all files into one (attachment all-missing-names.txt), which includes all the names that are not in the original report:
[all-missing-names.txt](https://github.com/ucsdlib/damsmanager/files/598818/all-missing-names.txt)

**Comment by remerjohnson** [comment]
@lsitu There were still the issues from before, but I managed to clean it up and identify some problems that were making it fail. I think we're good here. Thanks!

**Comment by lsitu** [comment]
That sounds good. Thanks @remerjohnson .
