### ISSUE TITLE
CSV preview does not include 655 field

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damsmanager#112]
Per @GregReser from #104 

@mdpeters discovered that the CSV preview function is not including the 655 field.  All other FAST headings are working.

Roger: http://roger.ucsd.edu/record=b9292834~S9
655  7 History.|2fast|0(OCoLC)fst01411628 

The XML output contains the heading "History", but the CSV output does not.

[preview-1861538287.xlsx](https://github.com/ucsdlib/damsmanager/files/595939/preview-1861538287.xlsx)

**Comment by lsitu** [comment]
@mcritchlow Yes, it's just a little mistake in the stylesheet for GenreForm conversion for the CSV output, and I've created a PR to fix it. It ready for review now. Thanks.

**Comment by mcritchlow** [comment]
@lsitu - This issue is still open, but I believe needs to be Closed. Yes?

**Comment by lsitu** [comment]
@mcritchlow Yes. It should be fixed.
