### ISSUE TITLE
PDF derivatives showing up as completely black upon ingest

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#114]
We have a problem of dark PDFs having completely [black derivatives][1] being generated upon ingest. If you click through to access the PDF in the viewer, it shows the correct document.   

Initially, we suspected this was because the size of the PDFs was too large, but this problem still occurs with these much smaller PDFs.  

The only pattern I can see from the ingest is that the problematic PDFs are very dark by nature.  

Is there possibly a setting with the PDF generating library that we can tweak to not be so sensitive to the amount of black in PDFs? Thanks.  

[1]: http://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=UC+San+Diego+General+Catalog&f%5Bdecade_sim%5D%5B%5D=1970s

![screenshot-1](https://cloud.githubusercontent.com/assets/5183580/20763895/cf0f8df0-b6e0-11e6-9c7e-b9e1cb55dc95.png)

**Comment by lsitu** [comment]
@rstanonik I created the thumbnail for PDF http://library.ucsd.edu/dc/object/bb1504296t on my Mac and I don't see the problem (see attachment). Do you have any thoughts regarding this issue? 
I see the GS version on QA is "GPL Ghostscript 8.70 (2009-07-31)", which is old. Could we install a newer version of GS on QA to see how it goes? Thanks.

Here is version of ImageMagick and GS, and the convert command I use:
$ convert -version
Version: ImageMagick 6.9.3-0 Q16 x86_64 2016-02-23 http://www.imagemagick.org

$ gs -v
GPL Ghostscript 9.18 (2015-10-05)
Copyright (C) 2015 Artifex Software, Inc.  All rights reserved.

$ convert -auto-orient -resize 450x450 bb1504296t_1.pdf[0] bb1504296t_1.jpg

![bb1504296t_1](https://cloud.githubusercontent.com/assets/2430784/20769478/eb95cd98-b6f6-11e6-8476-b1424ec5357d.jpg)

**Comment by lsitu** [comment]
@rstanonik Have you got a chance to look into the issue of upgrading Ghostscript? Thanks.

**Comment by gamontoya** [comment]
@lsitu Heard from Ron and he said he hasn't been following Github issues, but he will look for an updated version of GhostScript as you suggested.

Can you ping Ron early next week to remind him to look into this? I'll try to as well.

**Comment by lsitu** [comment]
@gamontoya Sure. Thanks for tracking this down.
Sorry @rstanonik. I haven't realized that but we've changed to use Github issues for a little while already.

**Comment by rstanonik** [comment]
I replaced ghostscript on lib-hydatail-qa, lib-hydratail-staging, and lib-hydratail-prod and confirmed that

convert -auto-orient -resize 450x450 bb1504296t_1.pdf[0] bb1504296t_1.jpg

was no longer just a black box.

Give it a try and let me know.

Ron

**Comment by gamontoya** [comment]
@lsitu Looks like you're good to go to test out now.

**Comment by lsitu** [comment]
Thanks @rstanonik . That sounds promising.
@gamontoya I am on it now.

**Comment by lsitu** [comment]
@gamontoya, @remerjohnson, @rstanonik  I've created a couple of examples on QA and both looks good:
http://libraryqa.ucsd.edu/dc/object/bd1381047p
http://libraryqa.ucsd.edu/dc/object/bd7251406d

I think we can move ahead to make the change on staging and prod. What do you think?

**Comment by remerjohnson** [comment]
@lsitu Would you need a list of ARKs of the corrupt images to replace?

**Comment by lsitu** [comment]
@remerjohnson How about just replacing the thumbnail/derivatives for all 45 objects in that collection?

**Comment by remerjohnson** [comment]
@lsitu Ah... okay, that would be a way to catch everything

**Comment by remerjohnson** [comment]
@rstanonik I think we are good to go. Do you need anything else from us?

**Comment by mcritchlow** [comment]
@remerjohnson @lsitu @rstanonik - Is #119 the remaining work here? Or do we still need this ticket open for further work/testing?

**Comment by lsitu** [comment]
@mcritchlow For this ticket, I think we may still need to update GS on staging and prod, and then I'll recreate the thumbnails for the PDFs in trouble. We'll deal with #119 as a separate ticket. 
What do you think @remerjohnson @rstanonik ?

**Comment by lsitu** [comment]
Thanks @rstanonik for upgrading GS on staging and prod. 
@remerjohnson, I've recreated the thumbnails for the PDFs in collection [UC San Diego General Catalog](http://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=UC+San+Diego+General+Catalog) . It seems like that all those black thumbnails are gone. Could you take a look?

**Comment by remerjohnson** [comment]
@lsitu Yup, these look great. Thanks for all your help, and also @rstanonik
