### ISSUE TITLE
MARC CSV preview includes invalid column headers

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#115]
Output from the CSV preview includes semantically incorrect headers, examples include:

- "Identifier:Roger record" - "Identifier:roger record"
- "Personal:Creator" - should be "Person:Creator"

Please fix incorrectly formatted headers in the CSV preview.

** For now, I believe we can leave incomplete headers (e.g. "Note:") so these can be reviewed and given a human mapping before ingest

**Comment by arwenhutt** [comment]
Output from the CSV preview includes semantically incorrect headers, examples include:
- "Identifier:Roger record" - "Identifier:roger record"
- "Personal:Creator" - should be "Person:Creator"

Please fix incorrectly formatted headers in the CSV preview.

* For now, I believe we can leave incomplete headers (e.g. "Note:") so these can be reviewed and given a human mapping before ingest

**Comment by lsitu** [comment]
@arwenhutt I've created a [PR](https://github.com/ucsdlib/damsmanager/pull/117) to fix column header "Identifier:Roger record" and "Personal:Creator". I think both Date and Note could have incomplete headers like "Date:", "Note:" etc. when the date type and note type can't be determined. Please let me know if you want to give it a default type in this case.

**Comment by mcritchlow** [comment]
It appears @lsitu created a PR to fix this, but this ticket remains open. Are we still testing? Or can this be closed?

**Comment by lsitu** [comment]
@mcritchlow Yes, we may still need to deploy damsmanager to staging as a sprint deployment cycle for test.

**Comment by GregReser** [comment]
@mcritchlow @lsitu This must not have been deployed yet - just tested CVS preview in staging and got invalid headers.

**Comment by lsitu** [comment]
@GregReser Yes, I just deployed damsmanager to staging and it's ready for review now.

**Comment by GregReser** [comment]
@lsitu 

1. Date column header is coming over without a type.  Please make it "Date:creation"
2. Eliminate column "Note:local attribution" since this is added automatically by the Excel ingest process.

**Comment by lsitu** [comment]
@GregReser I've updated damsmanager to use column name "Date:creation" when there is no type for Date and deleted column "Note:local attribution". The changes are on staging now. Could you take a look?

**Comment by GregReser** [comment]
@lsitu The latest version on staging looks good to me.

**Comment by lsitu** [comment]
Thanks @GregReser . We'll close the ticket then.
