### ISSUE TITLE
Replace curator-only .zips in Course Catalogs with PDFs

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#119]
As discussed with @lsitu, [Course Catalogs](http://library.ucsd.edu/dc/collection/bb1265385x) needs each curator-only .zip in its 45 objects replaced with PDFs. 

This would mean for each object:
+ Delete the current zip (curator, document-source) file 
+ Ingest the new pdf (curator, document-source [or service?]). 

@lsitu: Let me know if you need an ARK/file sheet mapping. The files are at `/digital-staging/UCSD-course-catalogs/Final_files`. The PDF files with the "-h" suffix are the PDFs that are replacing the .zips (`*-h.pdf`). 

The other PDFs (without the "-h") are the ones to be used in #114

**Comment by lsitu** [comment]
@remerjohnson I think it'll be nice if you can provide the ARK/file mapping. Thanks.

**Comment by remerjohnson** [comment]
@lsitu I've got the mapping completed. It has the ARK, current .zip file, and the pdf to replace it as curator-only. If this is easier to complete with #114 or after that issue, it's fine. 

2 caveats: 
+ One object, http://library.ucsd.edu/dc/object/bb8500947k, is a duplicate and can be deleted (it's noted in the csv)
+ One object, http://library.ucsd.edu/dc/object/bb1845593k, doesn't have a .zip or any curator-only file currently, so will just need the .pdf added as curator-only

[zips_to_replace.txt](https://github.com/ucsdlib/damsmanager/files/667116/zips_to_replace.txt)

**Comment by lsitu** [comment]
@remerjohnson Yes, we can replace the files after #114 is done. For the second PDF files to replace the .zip files, I think the files use need to be document-source since we've ingested the first PDF as document-service already, and only document-source is curator-only since those are public objects under rights holder "UC Regents".

**Comment by remerjohnson** [comment]
@lsitu Ah yes, you're right, these should be document-source. Thanks for catching that.

**Comment by lsitu** [comment]
Okay, It sounds good and I'll use document-source then.

**Comment by lsitu** [comment]
@remerjohnson I've deleted the .zip files and ingested the *-h.pdf files for each object in [Course Catalogs](http://library.ucsd.edu/dc/collection/bb1265385x). Could you take a look?

Just a note that I found the following two files in `/digital-staging/UCSD-course-catalogs/Final_files` but there are no corresponding objects ingested in prod:
UCSDGC_1989_1990-h.pdf
UCSDGC_1997_1998-h.pdf

**Comment by remerjohnson** [comment]
@lsitu Great, it looks good and I'll close this ticket once I've confirmed everything. 

The extra files are new and I will ingest these in a new batch. see [JIRA](https://lib-jira.ucsd.edu:8443/browse/CPP-76?focusedCommentId=49286&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-49286)

**Comment by lsitu** [comment]
@remerjohnson Thank you very much for your review and clarification for those new files. I am moving the ticket to the "Closed" column now.
