### ISSUE TITLE
Add component and sub-components to existing object (Heavy Metals collection)

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#121]
For the [Heavy Metals Collection](http://library.ucsd.edu/dc/collection/bb8056206n), we need a component added to [this object (http://library.ucsd.edu/dc/object/bb0820653z)](http://library.ucsd.edu/dc/object/bb0820653z), with two sub-components with files (meaning the component is merely a header with a title). I've attached the required metadata here (it's comma-separated). 

If ordering is possible, we would like this addition to be the _second_ component, meaning coming after the 'Collection event records' component but before the 'Specimen analysis records - derived data for 7 elements' component.

The two files referenced in the metadata are located on rdcp-staging at `rdcp-staging/heavy-metal/Final_Files`

If this is confusing, feel free to ask for clarification. Thanks

[OLR_heavy_metals_additions.txt](https://github.com/ucsdlib/damsmanager/files/700126/OLR_heavy_metals_additions.txt)

**Comment by gamontoya** [comment]
@hweng This is a test for you as a watcher.

**Comment by lsitu** [comment]
@remerjohnson @hjsyoo I've added the component with those two PDF files to the Heavy Metals object http://library.ucsd.edu/dc/object/bb0820653z. Could you take a look?

**Comment by hjsyoo** [comment]
@lsitu It looks like the PDFs were ingested as JPGs. When trying to download the files, they save as single page jpgs, and clicking on the image itself results in this message: Error: unable to find zoomable image. Both components should be multiple page PDFs.

**Comment by remerjohnson** [comment]
@hjsyoo That's strange. Not sure how that could have happened. I imagine we could try a file replace but I'll wait for guidance.

**Comment by lsitu** [comment]
@hjsyoo @remerjohnson I think it's my mistake to use a wrong use property data-service. It's fixed now. Could you take a look again? Thanks.

**Comment by hjsyoo** [comment]
It looks good now. Thanks @lsitu ! Will close the ticket.
