### ISSUE TITLE
Staging - PDF derivatives showing up as completely white upon ingest

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#126]
Possibly related to https://github.com/ucsdlib/damsmanager/issues/114

Objects ingested to staging have all white preview images.  Most recent ingest was Wed Jan 18 15:32:26
The PDF file looks fine, it's just the preview image that is blank.

http://librarytest.ucsd.edu/dc/object/bd9572278r
http://librarytest.ucsd.edu/dc/object/bd6876058n
![image](https://cloud.githubusercontent.com/assets/5453716/22119850/fb387612-de31-11e6-8557-82ada937e9ec.png)

**Comment by GregReser** [comment]
Oddly, one of three PDFs has a good preview image, while the other two are all white.

Good image: 
bd27121991

Bad image:
bd37360999
bd6876058n

**Comment by gamontoya** [comment]
@mcritchlow This is the ticket. Does Longshou have time to look into this today?

**Comment by lsitu** [comment]
@gamontoya @mcritchlow Sure. I'll look into it.

**Comment by GregReser** [comment]
I've done some more research that might help...

The objects with bad preview images, have dams:File/dams:outcomeNote = "Not well-formed"
The object with the good preview image has dams:File/dams:outcomeNote "Well-Formed and valid"

For the tile "Manifestación que hace a todas...", I created a new PDF from the same source TIFFs.  This time the preview image is correct and dams:File/dams:outcomeNote "Well-Formed and valid"
Bad image test = https://librarytest.ucsd.edu/dc/object/bd02889719 (source = S:\book_backlog\_INGEST\BAJA\b5436430.pdf)
Good image test = https://librarytest.ucsd.edu/dc/object/bd2439160j (source = S:\book_backlog\_INGEST\BAJA\TEST\b5436430.pdf)

All files passed the pre-ingest validation.

**Comment by lsitu** [comment]
Thanks @GregReser for the information. It looks like we can still created thumbnail for the PDFs with white background preview image. So it could be just the Ghostscript support issue.
@jhriv @rstanonik  I see the white background thumbnail is created on lib-camel, which has Ghostscript version "GPL Ghostscript 9.07 (2013-02-14)". While on lib-hydratail-staging with GS version "GPL Ghostscript 9.20 (2016-09-26)", I don't see this white background image issue. 
Could we upgrade Ghostscript on lib-camel to "GPL Ghostscript 9.20 (2016-09-26)" so that it's inline with other environments? Thanks.

**Comment by lsitu** [comment]
@jhriv Have you got a chance to upgrade Ghostscript on lib-camel to version "GPL Ghostscript 9.20 (2016-09-26)"? Thanks.

**Comment by jhriv** [comment]
Unfortunately, there are no pre-built Ghostscript 9.20 for RHEL 7, so I am trying to use the Fedora 22 SRPM to create the Ghostscript 9.20 RPM.

**Comment by lsitu** [comment]
Thanks @jhriv

**Comment by jhriv** [comment]
Ghostscript has been updated to 9.20.

**Comment by lsitu** [comment]
Thank you very much @jhriv .

**Comment by lsitu** [comment]
@GregReser It look like the problem is fixed now. I recreated the preview thumbnails and I see it shows up for https://librarytest.ucsd.edu/dc/object/bd6876058n. Could you try it again? Thanks.

**Comment by GregReser** [comment]
@lsitu Looks great - preview thumbnails are correct.
http://librarytest.ucsd.edu/dc/object/bd74904113 
http://librarytest.ucsd.edu/dc/object/bd42480600
http://librarytest.ucsd.edu/dc/object/bd1005712c

Has this been updated on production too?

**Comment by GregReser** [comment]
@lsitu Has this been updated on production too?  Can I ingest these same PDFs on production?

**Comment by lsitu** [comment]
@GregReser I think prod should have the same GS version already and it should work. So just feel free to ingest these PDFs on production. Thanks.

**Comment by GregReser** [comment]
@jhriv Is DAMS production running Ghostscript 9.20?  I'm wondering if I can proceed with ingest of the PDFs mentioned above to production.

**Comment by jhriv** [comment]
lib-hydratail-prod has Ghostscript 9.20
lib-hydrahead-prod has Ghostscript 8.70

**Comment by lsitu** [comment]
@GregReser We are using lib-hydratail-prod for derivatives creation on prod so we've got the right GS version installed there. Thanks @jhriv for checking it out.

**Comment by GregReser** [comment]
@lsitu Thanks, I'll go ahead with my ingests
