### ISSUE TITLE
Adjust DAMS statistics to include hits/downloads per collection from SC&A exhibits

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#127]
- Special Collections & Archives has several collections that pull objects directly from our DAMS. These Solr hits should be counted. For example: https://library.ucsd.edu/speccoll/dswenttowar
- Matt Peters will list all of the collection URLs here:

**Comment by mdpeters** [comment]
http://library.ucsd.edu/speccoll/dswenttowar/
http://library.ucsd.edu/speccoll/dsads/
http://library.ucsd.edu/historyofucsd/
http://library.ucsd.edu/speccoll/missionsites/index.html

**Comment by lsitu** [comment]
@mdpeters In Special Collections & Archives web page, what kind of files are you pulling from DAMS (like _4.jpg, _3.jpg, _2.jpg etc.)? What file would you consider to be a hit? And how about downloads?

**Comment by mdpeters** [comment]
I pull the _4 for thumb views and _2.jpg when doing the object view. I would consider the _2 to be object hits. The exhibit sites don't really do "downloads" per se, the best someone can get from the exhibits is the _2 file.

**Comment by lsitu** [comment]
@mdpeters Thanks for the information. I'll count _2.jpg access as object hits and ignore file downloads then.

**Comment by lsitu** [comment]
@gamontoya Would you like to add all _2.jpg access from Special Collections & Archives collection page to DAMS Statistics as object views, or separate those access from the object views for DAMS Statistics but add to the collections object access only?

**Comment by lsitu** [comment]
@gamontoya I've moved ahead to make the stats a different app and aggregated it for [DAMS Object Hits by Month](https://library.ucsd.edu/damsmanager/statsCollectionObjects.do) for now. Please let me know if you want to count it for DAMS Statistics as objects views as well, which will increase the count for accessing the object view URL like http://library.ucsd.edu/dc/object/bbxxxxxxxx.
@mcritchlow The PR https://github.com/ucsdlib/damsmanager/pull/131 is ready for review now. Thanks.

**Comment by mcritchlow** [comment]
@lsitu I'd prefer to hear if the change implemented in your PR (as described above) is what's desired by @gamontoya and company before evaluating the PR. Once we have agreement on that I'll dig into the PR.

**Comment by lsitu** [comment]
Thanks @mcritchlow. 
@gamontoya What's you though on it? I think we are flexible to include the status in or exclude it from any reports.

**Comment by gamontoya** [comment]
@lsitu The stats should be counted along with our DAMS stats and not separated out.

**Comment by lsitu** [comment]
@gamontoya Sure. I've update the PR to count it inside DAMS Stats.
@mcritchlow The PR  (see commit https://github.com/ucsdlib/damsmanager/commit/306a2acf5540419d46bb43db8995825b2a830962) is ready for review now. Thanks.
