### ISSUE TITLE
Adjust code for RDCP download statistics

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#128]

**Comment by gamontoya** [comment]
1. Investigate and fix: CSV, SAS7BDAT, TAR, GZIP and possibly other data file types do not get logged as downloads when in curator mode.
2. At the component level, when a user clicks on "View File" add a rule to count all file accesses as downloads.

**Comment by gamontoya** [comment]
@mcritchlow I touched based with Longshou on this. Can we add to the next Sprint?

**Comment by mcritchlow** [comment]
@gamontoya yeah i think so. while we definitely want his attention on the IIIF ticket, I think that won't be 100% time. I'll add the milestone 👍

**Comment by lsitu** [comment]
@gamontoya Do you want to count all master source files and the second source file (such as "File_2" in the Excel Input  Stream as file downloads?

**Comment by gamontoya** [comment]
@lsitu Master files are "curator" counts, right? What master source files can the public access?

**Comment by lsitu** [comment]
@gamontoya I think all service files, like PDFs (document-service), data files (data-service) etc, are allowed public access.

**Comment by gamontoya** [comment]
@lsitu Yes, I know about the service files, but you mentioned master source files. I was asking if there are any master source files in the DAMS that the public accesses?

**Comment by lsitu** [comment]
No, I don't think any files that are marked as source like image-source will be allowed public access. We always change it to a service file when a file need public access.
I was thinking about those files ingested by the curator are master source files, sorry about the confusing wordings.

**Comment by gamontoya** [comment]
@lsitu Okay, but make sure we are also tracking downloads made by curators (when logged in), whether they are master or service files.

**Comment by lsitu** [comment]
@gamontoya Yes, all downloads by the curator are tracking down with a marker. I've added [PR](https://github.com/ucsdlib/damsmanager/pull/129) to count all access to master/service files as downloads, and this will exclude all derivatives created by DAMS from being counted.
@mcritchlow The PR https://github.com/ucsdlib/damsmanager/pull/129 is ready for review now. Thanks.
