### ISSUE TITLE
Excel ingest - make column header validation case insensitive

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#130]
To avoid problems with output from other tools (MARC CSV > DAMS RDF) or user error, make the validation of all column headers in the Excel standard input spreadsheet case-insensitive.

For example, these should all be valid:
"File name", "file name"
"Title", "title"
"Person:artist", "Person:Artist", "person:Artist", "person:artist"

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/133 to make Excel Input Stream column header validation case insensitive. It's ready for review now. Thanks.

**Comment by gamontoya** [comment]
@mcritchlow @GregReser @arwenhutt Did someone in DOMM review this on staging?

**Comment by mcritchlow** [comment]
@gamontoya I don't think so. I believe @lsitu just created the release branch and deployed it to staging.

**Comment by gamontoya** [comment]
@GregReser @arwenhutt Can one of you review on staging and report back here?

**Comment by GregReser** [comment]
@gamontoya I'll test it today

**Comment by GregReser** [comment]
@gamontoya @lsitu It's working perfectly. Thanks.

**Comment by gamontoya** [comment]
@GregReser Thank you for confirming.
