### ISSUE TITLE
Change MARC to CSV Mapping

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#138]
### Change mapping for MARC 700 12 
- no longer map to title:variant
- map to Note:work title  (this is a new note type, which we will deal with later)
 - value = $a $d $t (replace subfield with whitespace)

Example:
```
MARC source:
700 12 |iContainer of (expression):|aIves, Charles,|d1874-1954.|tHe is there!;|oarranged
```
```
DAMS CSV output:
note:work title = "Ives, Charles, 1874-1954. He is there!"
```
### Handle multiple roles for a single MARC creator, 100, 110, 700, 710
In the current CSV output, if there is a second creator $e then a column without a header is inserted and creator values are not aligned with the proper column headers.  Fix this by:

**If** there are multiple $e in a single MARC creator
**Then** create separate columns for each role and place the name value in each column

Example:
```
MARC Source:
100 1  Ives, Charles,|d1874-1954,|ecomposer,|earranger of music 
```
```
DAMS CSV output:
Person:composer = "Ives, Charles, 1874-1954"
Person:arranger of music = "Ives, Charles, 1874-1954"
```

### Map MARC 336 $a to Subject:genre

Example:
```
MARC Source:
336    performed music|bprm|2rdacontent 
```
```
DAMS CSV output:
Subject:genre = "performed music"
```

**Comment by lsitu** [comment]
@GregReser Do you have an example with the bib number that I can use for test? Thanks.

**Comment by GregReser** [comment]
@lsitu this one has all three MARC tags mentioned above.
b3128805

**Comment by GregReser** [comment]
@lsitu Here is a test MARC to CSV I did to evaluate the issues.
See row 2 and how the creator values do not line up with the correct column header. 
"Kimball, Jean, (Conductor)" should be Person:conductor
"Yates, Peter, 1909-1976" should be Person:host
"Myrick, Julian, 1880-1969" should be Person:speaker
[yates_marc2Csv_001.xlsx](https://github.com/ucsdlib/damsmanager/files/855879/yates_marc2Csv_001.xlsx)

**Comment by lsitu** [comment]
@GregReser Yes, I see the problem and I'll look into it. Thanks.

**Comment by lsitu** [comment]
@GregReser Currently MARC 336 is map to typeOfResource with the following conversions:
cartographic dataset => cartographic data
cartographic image => cartographic
cartographic moving image => cartographic moving image
cartographic tactile image => cartographic
cartographic tactile three-dimensional form => cartographic
cartographic three-dimensional form => cartographic
computer dataset => data
computer program => software
notated movement => notated movement
notated music => notated music
performed music => sound recording - musical
sounds => sound recording - nonmusical
spoken word => sound recording - nonmusical
still image => still image
tactile image => still image
tactile notated movement => notated movement
tactile notated music => notated music
tactile text => text
tactile three-dimensional form => three dimensional object
three-dimensional form => three dimensional object
three-dimensional moving image => moving image
two-dimensional moving image => moving image

Should we simply map it to Subject:genre with no conversions?

**Comment by GregReser** [comment]
@lsitu Can we have both?
- typeOfResource = 336 current conversion 
- Subject:genre = 336 value?

336 is a more specific type of resource and seems like a good fit for genre.

**Comment by lsitu** [comment]
@GregReser Yes. I'll make another copy with no conversions for Subject:genre then.

**Comment by lsitu** [comment]
@GregReser To have MARC 336 as Subject:genre in the CSV output, I need to make it a FAST subject with no valueURI for the FAST url in the JollyRoger stylesheet for mods conversion by default. Does it sound good to you?

**Comment by GregReser** [comment]
@lsitu You're right, we did restrict subjects to FAST and I don't want to conflict with that.
Do we have anything mapped to Note:material details?  If not, let's map the 336 there.

**Comment by lsitu** [comment]
No, 336 is only mapped to typeOfResource at this time. I'll add it to Note:material details then. Could you update the Excel Standard Input template (xls_standard_input_template.xlsx) to include new note type Note:work title for validation? Thanks.

**Comment by GregReser** [comment]
@lsitu I updated https://github.com/ucsdlib/dams-metadata/blob/master/xls_standard_input_template.xlsx

**Comment by lsitu** [comment]
@GregReser I got the 404 error when I click on the link above. It looks like I don't have the access rights.

**Comment by GregReser** [comment]
@lsitu here it is.
[xls_standard_input_template.xlsx](https://github.com/ucsdlib/damsmanager/files/859200/xls_standard_input_template.xlsx)

**Comment by lsitu** [comment]
@mcritchlow I've created a PR in JollyRoger and a PR in damsmanager for the mapping changes:
https://lib-stash.ucsd.edu/projects/OD/repos/jollyroger/pull-requests/8/overview
https://github.com/ucsdlib/damsmanager/pull/139

Both PRs are ready for review now. Thanks.

**Comment by GregReser** [comment]
@lsitu Sorry, I received feedback that we need to import more subfields from the MARC 700 12.  I wanted to warn you in case you are wrapping this up.
I'll get you a new list of subfields as soon as possible.

**Comment by lsitu** [comment]
@GregReser Yes, we've merged the PRs and the ticket was closed by default. But no problem and we can work together on it again once the new fields are ready for 700 12.

**Comment by GregReser** [comment]
@lsitu is it better in cases like this to open a new ticket?

**Comment by mcritchlow** [comment]
Sorry to jump in, but I'd say if the work was done as originally described, a new ticket makes sense. That seems to be the scenario in this case.

If work was not completed as originally described, then re-opening makes sense.
