### ISSUE TITLE
Change MARC to CSV Mapping: 700 12

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#140]
### Include additional subfields for MARC 700 12
- map to Note:work featured (ucsd:workFeatured)
  - this is a change in the data dictionary and import template
- include values from subfields $a, $b, $c, $d, $f, $g, $j, $k, $l, $m, $n, $o, $p, $q, $r, $s, $t
  - keep order of subfield values from MARC source (not the subfield order above )
  - replace subfield with whitespace (keep all other punctuation)

Examples:
```
MARC source:
700 12 Ives, Charles,|d1874-1954.|tSonatas,|mpiano,|nno. 2

DAMS CSV output:
note:work featured = "Ives, Charles, 1874-1954. Sonatas, piano, no. 2"
```
```
MARC source:
700 12 $iContainer of (expression):$aBenedict$bXIV,$cPope,$d1675-1758.$tSollicitudini Nostrae.$lFrench.

DAMS CSV output:
note:work featured = "Benedict XIV, Pope, 1675-1758. Sollicitudini Nostrae. French."
```

```
MARC source:
700 12 Beethoven, Ludwig van,|d1770-1827.|tSonatas,|mpiano,|nno. 14, op. 27, no. 2,|rC♯ minor.|pAdagio sostenuto

DAMS CSV output:
note:work featured = "Beethoven, Ludwig van, 1770-1827. Sonatas, piano, no. 14, op. 27, no. 2, C♯ minor. Adagio sostenuto"
```

**Comment by GregReser** [comment]
[xls_standard_input_template.xlsx](https://github.com/ucsdlib/damsmanager/files/865647/xls_standard_input_template.xlsx)

updated ingest template with Note:work featured

**Comment by lsitu** [comment]
@GregReser Should we hold off the release for damsmanager for the changes we had last sprint while we are working on this ticket this sprint?

**Comment by GregReser** [comment]
@lsitu Yes, it makes sense to wait.

**Comment by lsitu** [comment]
@GregReser Are we going to replace the mapping for Note:work title to Note:work features for MARC 700 12, and the column Note:work title will be no longer used?

**Comment by GregReser** [comment]
@lsitu Yes and thanks for catching that

**Comment by lsitu** [comment]
@mcritchlow I've created a PR in damsmanager and a PR in JollyRoger for the new mapping, and both PRs are ready for review now. Thanks.
https://lib-stash.ucsd.edu/projects/OD/repos/jollyroger/pull-requests/9/overview
https://github.com/ucsdlib/damsmanager/pull/141
