### ISSUE TITLE
Stuart Collection Photographs - update metadata and visibility

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#142]
### Descriptive summary

This request is to make several metadata edits to the Stuart Collection http://library.ucsd.edu/dc/collection/bb9421444x
It is not a very high priority since they are not currently public. However, there is a desire by the project manager to finally make approved objects public.

## Issue 1
Redundant Title values.  SubTitle value is repeated in Title after "--".
In Title, "--" should be ": "

Action:

For all objects -

1. dams:title/mads:Title/mads:elementList/mads:SubTitleElement 
   - delete property

2. dams:title/mads:Title/mads:authoritativeLabel
   - replace "--" with ": "

3. dams:title/mads:Title/mads:elementList/mads:MainTitleElement/mads:elementValue
   - replace with new value from mads:authoritativeLabel

```xml
OLD:
	<dams:title>
		<mads:Title>
			<mads:authoritativeLabel>La Jolla Project--general view</mads:authoritativeLabel>
			<mads:elementList rdf:parseType="Collection">
				<mads:MainTitleElement>
					<mads:elementValue>La Jolla Project</mads:elementValue>
				</mads:MainTitleElement>
				<mads:SubTitleElement>
					<mads:elementValue>general view</mads:elementValue>
				</mads:SubTitleElement>
			</mads:elementList>
		</mads:Title>
	</dams:title>

NEW:
	<dams:title>
		<mads:Title>
			<mads:authoritativeLabel>La Jolla Project: general view</mads:authoritativeLabel>
			<mads:elementList rdf:parseType="Collection">
				<mads:MainTitleElement>
					<mads:elementValue>La Jolla Project: general view</mads:elementValue>
				</mads:MainTitleElement>
			</mads:elementList>
		</mads:Title>
	</dams:title>
```

## Issue 2
Change dams:relationship/dams:corporateName "Stuart Collection (San Diego, Calif.)" role from "Sponsor" to "Creator"

Action:

For all objects -

1. **IF** dams:relationship/dams:corporateName/mads:CorporateName = http://library.ucsd.edu/ark:/20775/bb0376994d *"Stuart Collection (San Diego, Calif.)"*
  - **CHANGE** dams:role/mads:Authority **TO** http://library.ucsd.edu/ark:/20775/bb67931665 *"Creator"*

## Issue 3
Change dams:relationship/dams:personalName "Beebe, Mary Livingstone (American, born 1940)" role from "director" to "donor"

Action:

For all objects -

1. **IF** dams:relationship/dams:personalName **=** http://library.ucsd.edu/ark:/20775/bb29708767 *"Beebe, Mary Livingstone (American, born 1940)"*
  - **CHANGE** dams:role/mads:Authority **TO** http://library.ucsd.edu/ark:/20775/bb02746293 *"donor"*

  
## Issue 4

Add rightsHolder and visibility based on photographer name value.  
All objects where the photographer **IS** *"Rittermann, Philipp Scholz (American photographer, 1955 CE-)"* should have rightsHolderPersonal *"Rittermann, Philipp Scholz (American photographer, 1955 CE-)"* and should be curator view

All objects where the photographer **IS** *"Cohen, Becky (American photographer, contemporary)"* should have rightsHolderPersonal *"Cohen, Becky (American photographer, contemporary)"* and should be public view

All other objects should have dams:rightsHolderCorporate *"UC Regents"* and should be public view

Action:

**IF** dams:relationship/dams:role/mads:Authority **=** http://library.ucsd.edu/ark:/20775/bb95577756 *"Photographer"*

1. **IF** dams:relationship/dams:personalName **=** http://library.ucsd.edu/ark:/20775/bb51552033 *"Rittermann, Philipp Scholz (American photographer, 1955 CE-)"*
   - **ADD** dams:rightsHolderPersonal **value =** http://library.ucsd.edu/ark:/20775/bb51552033 "Rittermann, *Philipp Scholz (American photographer, 1955 CE-)"*
   - Object should remain as curator view only

 2. **IF** dams:relationship/dams:personalName **=** http://library.ucsd.edu/ark:/20775/bb9523843c *"Cohen, Becky (American photographer, contemporary)"*
    - **ADD** dams:rightsHolderPersonal **value =** http://library.ucsd.edu/ark:/20775/bb9523843c *"Cohen, Becky (American photographer, contemporary)"*
    - **ADD** dams:visibility **value =** *"public"*

3. **IF** dams:relationship/dams:personalName **=** undefined
**OR IF** dams:relationship/dams:personalName **!=** http://library.ucsd.edu/ark:/20775/bb51552033 *"Rittermann, Philipp Scholz (American photographer, 1955 CE-)"*
**OR IF** dams:relationship/dams:personalName **!=**  http://library.ucsd.edu/ark:/20775/bb9523843c *"Cohen, Becky (American photographer, contemporary)"*
   - **ADD** dams:rightsHolderCorporate **value =** http://library.ucsd.edu/ark:/20775/bb9421331f *"UC Regents"*
   - **ADD** dams:visibility **value =** *"public"*

**Comment by lsitu** [comment]
@GregReser I see all records in Stuart collection has rights holder UC Regents:   
<dams:rightsHolderCorporate>
      <mads:CorporateName>
        <mads:authoritativeLabel>UC Regents</mads:authoritativeLabel>
        <mads:elementList rdf:parseType="Collection">
          <mads:FullNameElement>
            <mads:elementValue>UC Regents</mads:elementValue>
          </mads:FullNameElement>
        </mads:elementList>
      </mads:CorporateName>
    </dams:rightsHolderCorporate>

Should I delete the UC Regents rights holder element while adding the dams:rightsHolderPersonal property for # 1 (rights holder: Rittermann, Philipp Scholz (American photographer, 1955 CE-)) and # 2 (V: Cohen, Becky (American photographer, contemporary)) in Issue 4 above?

**Comment by GregReser** [comment]
@lsitu yes, delete the UC Regents rights holder element if dams:rightsHolderPersonal is being added.  We want just one rightsHolder

**Comment by lsitu** [comment]
@GregReser I've updated the records in the Stuart collection on prod according to the action items in the description text above. It's ready for review now, http://library.ucsd.edu/dc/collection/bb9421444x. Could you take a look? Thanks.

**Comment by GregReser** [comment]
@lsitu The collection objects and the objects with dams:visibility value = "public" not visible to the public.  Is this because the collection has not ever been released?  Should I run the damsmanager/collectionRelease.do tool?  I'm always a little unsure if I select Release State - Public Access that it will turn all objects public.  This won't happen, right.  Does collectionRelease.do just re-index the objects so they display according to their metadata?

**Comment by lsitu** [comment]
@GregReser Yes, the Stuart collection is still in curator view and it isn't visible to public at this time. It hasn't been released yet and we can simply release it through [damsmanager/collectionRelease.do](https://librarytest.ucsd.edu/damsmanager/collectionRelease.do) tool.
If you select "Release State - Public Access", yes, we will update the visibility of the CLR to public and reindex (only) all the objects in the collection. This will make the collection record be available for public, while the objects in the collection will be off from the curator hood, and their visibility will be self described by its own rights metadata and access override.

**Comment by GregReser** [comment]
@lsitu Looks good.  This was a very complicated edit and you did a great job with it.  Thanks

**Comment by lsitu** [comment]
Thanks @GregReser. Yep, my codes are happy with the nice instructions you provided!
