### ISSUE TITLE
Change brief description for dataMares collection

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#144]
### Descriptive summary

We need a change to the "brief description" for the dataMares collection: http://library.ucsd.edu/dc/collection/bb08210169

There is already a [JIRA ticket DOMM-21](https://lib-jira.ucsd.edu:8443/browse/DOMM-21), but the brief description needs to be now: 
> This section contains robust, high-quality scientific information related to the Gulf of California and Mexico-specific ocean fisheries and their relationship to marine reserves, coastal and marine ecosystems, and climate change. This sub-collection also contains datasets with information on fishing activities collected with the participation of local fishermen.

### Rationale

I cannot make this edit via RDF because we no longer have the source CLR metadata or image, and there have been numerous RDF edits since then 

### Related work

[JIRA ticket DOMM-21](https://lib-jira.ucsd.edu:8443/browse/DOMM-21)

**Comment by gamontoya** [comment]
@mcritchlow No way to transfer a ticket to another repository, right? This probably should be in DAMSPAS.

**Comment by mcritchlow** [comment]
@gamontoya in this case, i think DAMS Manager is fine. That said, I agree it's worth checking out possible issues for ticket transfers between repos (like the one you found).

**Comment by lsitu** [comment]
@remerjohnson: Do we need to update the "Scope And Content" Note or the "dams:ScopeContentNote" here for the [dataMares Project: Fisheries](http://library.ucsd.edu/dc/collection/bb08210169) collection?

**Comment by lsitu** [comment]
@hjsyoo, @remerjohnson I've moved ahead to update the dams:ScopeContentNote since this what the brief description refers to, which will change the collection description text in the search result page https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=%22dataMares+Project%3A+Fisheries%22 but it won't change anything in the collection viewer (http://library.ucsd.edu/dc/collection/bb08210169). Could you take a look?

**Comment by hjsyoo** [comment]
@lsitu The Brief Description text and collection page have the correct content. Thank you!
