### ISSUE TITLE
DAMS Top 100s not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#148]
### Descriptive summary

DAMS Statistics include list out the top 100 objects accessed the most. The thumbnails have suddenly stopped working.

### Steps to reproduce the behavior

https://library.ucsd.edu/damsmanager/statsPopular.do

**Comment by lsitu** [comment]
@mcritchlow I think the missing thumbnail issue should be fixed with PR https://github.com/ucsdlib/damsmanager/pull/150. It's ready for review now. Thanks.
