### ISSUE TITLE
Move objects into new SIO photos ProvenanceCollectionPart - Milo Woodbridge Williams Photographs

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#151]
### Descriptive summary

For 299 objects with note:location of originals = "This digital image is a surrogate of an item from the Milo Woodbridge Williams Papers, 1914-2000"

1. Place each object into the collection "Milo Woodbridge Williams Photographs" (bb6248543w).  This is a ProvenanceCollectionPart of the Scripps Institution of Oceanography Photographs (bb20151229).

2. For each object, completely delete the note:note that begins with string "Note: In Williams Box*"

3. For each object, for note:location of originals,  delete substring ", 1914-2000"
CURRENT: "This digital image is a surrogate of an item from the Milo Woodbridge Williams Papers, 1914-2000"
NEW: "This digital image is a surrogate of an item from the Milo Woodbridge Williams Papers"

4. Make "Milo Woodbridge Williams Photographs" (bb6248543w) public.

**Comment by lsitu** [comment]
@GregReser I think all 299 objects with note:location of originals = "This digital image is a surrogate of an item from the Milo Woodbridge Williams Papers, 1914-2000" should be grouped under collection [Milo Woodbridge Williams Photographs](http://library.ucsd.edu/dc/collection/bb6248543w) now http://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Milo+Woodbridge+Williams+Photographs&id=bb6248543w.

Would you like me to do step # 4 to release collection "Milo Woodbridge Williams Photographs" (bb6248543w) for public access now?

**Comment by GregReser** [comment]
Yes, go ahead and release collection "Milo Woodbridge Williams Photographs"

**Comment by lsitu** [comment]
@GregReser The "Milo Woodbridge Williams Photographs" collection is available for public access now: http://library.ucsd.edu/dc/collection/bb6248543w. Could you take a look? Thanks.

**Comment by GregReser** [comment]
@lsitu Looks good.  Closed this issue
