### ISSUE TITLE
Update indexing rules for linked records

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#152]
### Descriptive summary
Update indexing rules for linked records
1. In all cases, only reindex records directly linked to the item updated. 
2. For CLR records, IF dams:relatedResource property is edited, THEN Re-index all directly linked OLRs
3. For CLR records, IF dams:title property is edited, THEN Re-index all directly linked OLRs and CLRs
4. For CLR records, IF the CLR is published, THEN Re-index all directly linked CLRs (as well as whatever it currently does for OLRs)
5. For CLR records, IF new record is created, THEN Re-index all directly linked OLRs and CLRs
6. For Authority records, IF any property is edited, THEN Re-index all directly linked records

### Rationale
The current, looser indexing rules create substantial re-indexing backlogs (and delays) by re-indexing records which would not be affected by the edits.  These edits should significantly reduce unnecessary re-indexing.

**Comment by arwenhutt** [comment]
@lsitu please let us know if these make sense, or if you have any reservations about them causing problems.  We don't want to omit important data from the index because of an oversight on our part.  Thanks!

**Comment by gamontoya** [comment]
@mcritchlow We should make this an R&D ticket and not so much implementation at this time.

**Comment by lsitu** [comment]
@arwenhutt The rules looks good but we may need to discuss #4, #5 and #6 a little bit for priorities and efforts:
4. For CLR records, IF the CLR is published, THEN Re-index all directly linked CLRs (as well as whatever it currently does for OLRs)
*Could we say this rule will apply for all public collections? I think this could introduce lots of unnecessary re-indexing of OLR in a collection when it's updated, especial for large collections like SIO Photographs. Could we just apply the rules in #1, #2 and #3?

5. For CLR records, IF new record is created, THEN Re-index all directly linked OLRs and CLRs
*When a new CLR record created, it won't link to any OLR. Do you mean the OLR in the collection CLR that directly linked to the new collection created? 
I think the new collection functions are from the Excel Input template and the web base [Collection Create/Update](ttps://library.ucsd.edu/damsmanager/collection.do) functions, which will require additional efforts.

6. For Authority records, IF any property is edited, THEN Re-index all directly linked records
*It looks like the [Subject Import Tool](https://library.ucsd.edu/damsmanager/subjectImport.do) won't allow update the authority records at this time. Could authority records update a dev task or we need to provide tools for curator access?
When an authority record need to be updated, I think devs will response for re-indexing of the linked records at this time. But yes we can automate the support for curator access, but as @gamontoya commented above, this may require additional implementations.

Can we concentrate more on the RDF Import tool to improve the SOLR re-indexing behavior now, and create tickets to for other tools? Thanks.

**Comment by lsitu** [comment]
@arwenhutt What's your thought regarding # 4, # 5 and # 6 in [#issuecomment-307230373](https://github.com/ucsdlib/damsmanager/issues/152#issuecomment-307230373) above? I think we could prioritize the features you want to implement now. Thanks.

**Comment by lsitu** [comment]
@arwenhutt I review damsmanager for the rules currently implemented, I see the following fields being updated in CLR will trigger the linked OLR and CLR being re-indexed recursively:
dams:title
dams:visibility
dams:relatedResource
predicates for collections hierarchy like dams:assembleCollection|dams:hasCollection etc.

It looks like the updating of these fields should trigger the reindexing of the directly linked objects, and the updating of dams:title and dams:visibility should trigger the re-indexing of all OLRs in the collection hierarchy recursively. Does it sounds correct? 
Currently updating any of the fields above in a CLR will trigger all OLRs linked to the collection hierarchy to be re-indexed, which could be a little bit overwhelming for the dams:relatedResource field and those predicates used for collection hierarchy.

Also, the RDF Import tool should work for updating of single authority record by the ARK, though we've never declared to support it and we may need to test it out, which will trigger the reindexing of all linked OLRs and CLRs. Does it what you want to to support?

**Comment by lsitu** [comment]
@mcritchlow I've created PR https://github.com/ucsdlib/damsmanager/pull/158 to update the SOLR re-index rules for RDF Import to avoid  re-indexing of referenced records from the parent collections. It's ready for review now. Thanks.
