### ISSUE TITLE
R&D: Investigate options for capturing object level view (analytics) for the Holocaust collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#154]
### Descriptive summary

Need object views for the Holocaust Living History Workshop collection. Google Analytics only tells us if a user landed on the page and not if they watched the video. Check to see if we can get statistics for watched data from Wowza/Splunk like Vivian is currently doing for DMR.

### Rationale

We need to give UCTV a way to aggregate our current usage statistics for the HLHW collection. They want stats to show the library so they can keep getting funding from the Library to do the series.

**Comment by mcritchlow** [comment]
@VivianChu - let's discuss in the planning mtg w/ @gamontoya

**Comment by VivianChu** [comment]
@gamontoya - DMR is using wowza log and splunk api to retrieve the data to report how long the user watched a video.  We can use that way to capture the data for the Holocaust collection to tells us if a user watched the video.  The wowza logs are already in splunk and ready to use.  We just need to decide where to implement this feature - in damsmanager or damspas.   What do you think?  Thanks

**Comment by gamontoya** [comment]
@VivianChu @mcritchlow I'm thinking we want to add this feature to DAMSManager with the other stats tool(s).

FYI: This work needs to be approved by the Products Group before any action is taken. Thanks Vivian!
