### ISSUE TITLE
Add file to existing dataMates: Fisheries object

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#155]
### Descriptive summary

Add one file, `f_gc_pfe.xlsx` to the existing [Potential Fishing Effort object](https://library.ucsd.edu/dc/object/bb7032714m). It should go in as the `data-service` file use. If more information is needed or an ingest sheet is needed, let me know. 

### Rationale

This object is no longer under embargo. Originally we had ingested this object without a file. This file should be added now.
[f_gc_pfe.xlsx](https://github.com/ucsdlib/damsmanager/files/1095732/f_gc_pfe.xlsx)

**Comment by lsitu** [comment]
@remerjohnson I've added the .xslx file to object https://library.ucsd.edu/dc/object/bb7032714m. I think you can download it now.

**Comment by mcritchlow** [comment]
@remerjohnson - is this done as expected?

**Comment by remerjohnson** [comment]
@mcritchlow Ah yes. Sorry, had reviewed this but hadn't closed it out. Thanks @lsitu
