### ISSUE TITLE
Release Dams Manager 2.58

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damsmanager#160]
### Descriptive summary

Version: 2.58
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv

**Comment by lsitu** [comment]
@gamontoya DAMS Manager release 2.58 is also available on staging for review now. This release  includes changes for the following tickets:
[Dedupe collection titles in Research Data Collections](https://github.com/ucsdlib/damspas/issues/319)
[Update indexing rules for linked records](https://github.com/ucsdlib/damsmanager/issues/152)

**Comment by gamontoya** [comment]
@lsitu Thank you Longshou. This is approved for production.

**Comment by lsitu** [comment]
Thanks @gamontoya .
@rstanonik @jhriv DAMS Manager release/2.58 is merged to the master branch and it's ready for prod now. Thanks.

**Comment by rstanonik** [comment]
I scheduled it to deploy tomorrow morning at 6:00am.

**Comment by lsitu** [comment]
Sounds good. Thanks @rstanonik .

**Comment by rstanonik** [comment]
It deployed this morning
