### ISSUE TITLE
Request for reports on usage of file-use values in D4

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#161]
### Descriptive summary
I would like to request two reports on file-use value usage in D4 to identify all the unique combinations of files use values and their frequency of use.  

### Rationale
Having a breakdown of the unique patterns of file use values and their frequency of use, will help to identify areas of our current data model that may not require replication in D5.  They will be useful for checking the impact of file use modeling decisions for D5, and help support any recommendations made to the products group for modifying D4 functionality in D5.

### Details
**Report 1 - Object level file-use values:**
- Identify each unique combination or "pattern of file-use values" [1] for all files directly related to an object.  This report would **not** include files associated with a component of an object, just those directly to the object.  
- For each unique pattern:
-- A count of how many objects have this pattern present 
-- The names of collections to which these objects belong
-- ARKS for 10 sample objects [2] with this pattern

**Report 2 - Component level file-use values:** [3] 
- Identify each unique combination or pattern of file-use values for all files directly linked to a component node of an object.  
- For each unique pattern:
-- A count of how many component nodes have this pattern present
-- The names of collections to which these objects belong
-- ARKS for 10 sample objects [2] containing component nodes with this pattern

#### Clarifications:
[1] for example this object https://library.ucsd.edu/dc/object/bb5325252j has the file-use pattern of:

> image-source
> image-service
> image-thumbnail
> image-preview
> image-icon

[2] for some of these patterns we may need a larger sample or even full listing after initial evaluation, in case it is easier to generate full lists rather than samples when doing these reports.

[3] I am asking for two reports to get an idea of the pattern of use at each node (object or individual component level).  The wide variance in the number and structure of components in hierarchical objects would make an object+component pattern report much less useful for identifying our core usage scenarios.

### Related work
Finalizing file use modeling: https://github.com/ucsdlib/horton/issues/111

**Comment by lsitu** [comment]
@arwenhutt Here are the reports of file-use values occurred in DAMS4 for objects and components, which are arranged in the following format:
[File-use Pattern] ( [Count/Occurrence] )
* [Collection ARK] ( [Collection Title] )
* ... ...
* Examples:
*    [Object ARK]
*    ... ...

Report 1 - Object level file-use values:
[object_file_use_report.txt](https://github.com/ucsdlib/damsmanager/files/1177569/object_file_use_report.txt)

Report 2 - Component level file-use values:
[component_file_use_report.txt](https://github.com/ucsdlib/damsmanager/files/1177574/component_file_use_report.txt)

Please let me know if you have any questions. Thanks.

**Comment by arwenhutt** [comment]
Wow, that was fast!  Thanks @lsitu 
I'll let you know if I have any questions after I have a chance to look at them.

**Comment by arwenhutt** [comment]
@mcritchlow @lsitu do you know if the files associated with these file-use values:
**image-huge
image-large
**image-icon**

could be outdated relics of a bygone era?  I'm not seeing them rendered anywhere (at least on desktop, maybe they're for mobile?) even when present.
example object: https://library.ucsd.edu/dc/object/bb9728253x/

**Comment by lsitu** [comment]
@arwenhutt I think we just once used image-icon in DAMS 3 but stoping using it for D4, and we've never used image-huge and image-large in any scenarios.

**Comment by arwenhutt** [comment]
Thanks! thats very helpful :)
