### ISSUE TITLE
MARC to CSV Mapping: add 79X, 245 $c

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#162]
## Export all MARC 79X fields to CSV DAMS4 transform 

- map to new column "79X  Local Added Entry" This column is invalid, but it will be reviewed and mapped manually to a valid DAMS template column for ingest.
- if there are multiple 79X fields, place each in a separate "79X  Local Added Entry" column
- include values from subfields $a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, $n, $p, $q, $t, $u, $x, $0, $3, $4, $5, $8
  - keep order of subfield values from MARC source (not the subfield order above )
  - replace subfield with whitespace (keep all other punctuation)

## Export 245 $c to new column "Statement of Responsibility"
- This column is invalid, but it will be reviewed and mapped manually to a valid DAMS template column for ingest.

## Additional request
It would help if we had documentation of our current MARC to CSV mapping.  Would it be possible to produce a simple list of our mapping?

**Comment by gamontoya** [comment]
@GregReser Is this still needed?

**Comment by GregReser** [comment]
@gamontoya yes please.  It was a request form Matt Peters

**Comment by gamontoya** [comment]
@GregReser We'll add it to the next Sprint.

**Comment by lsitu** [comment]
@GregReser To convert MARC 79X field and 245 $c field from MARC to CSV, we first need to convert these two fields to MODS, what MODS properties would you like to map these two fields to? I think we may need to use unique MODS property/predicate for this purpose so that it won't mix with other fields. Thanks.

**Comment by GregReser** [comment]
@lsitu 
For 245 $c, use mods:note type ="statement of responsibility", unless we are already mapping something else to that.

For 79X, I can't find any appropriate MODS property, sub-property, or attribute.  Since we are placing this in a single column for human review, it makes sense to use a simple custom MODS property/predicate localAddedEntry.  Do we need to use mods:extension for this?

**Comment by lsitu** [comment]
@GregReser For 245 $c, |'ll use mods:note type ="statement of responsibility" then. For 79X, what structure do you suggest with mods:extension?

**Comment by GregReser** [comment]
@lsitu Maybe this:

<mods:extension xmlns:ucsd="http://library.ucsd.edu/ontology/dams4.2#">
	<ucsd:localAddedEntry> </ucsd:localAddedEntry>
</mods:extension>

I'm hesitant to use ucsd because we don't actually use localAddedEntry in the DAMS5 data model, but the MARC to CSV conversion is an internal process so it shouldn't cause any problems.

**Comment by GregReser** [comment]
@lsitu re-thinking this - maybe we should make it simple and use mods:note type = "Local Added Entry"

These are all the 79X that would exist:

790 Local Added Entry--Personal Name
791 Local Added Entry--Corporate Name
792 Local Added Entry--Meeting Name
793 Local Added Entry--Uniform Title
796 Local Added Entry--Personal Name
797 Local Added Entry--Corporate Name
798 Local Added Entry--Meeting Name
799 Local Added Entry--Uniform Title

I'll have to look for an example

**Comment by lsitu** [comment]
@GregReser Thanks. It sounds good to use mods:note type = "Local Added Entry". Do we need to encode the values after '--' like Personal Name (790 Local Added Entry--Personal Name) into the mapping structure?

**Comment by GregReser** [comment]
@lsitu No, don't worry about the type values after "--".

Here is a simple example to test.  It only has a 790 and 793, but I will look for a better one.
b4104439

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/jollyroger/pull/1 in JollyRoger and PR https://github.com/ucsdlib/damsmanager/pull/223 in damsmanager for this support. Both PRs are ready for review now. Thanks.
