### ISSUE TITLE
Subject import tool - add closeMatch

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#164]
### Descriptive summary

Add a column to the subject import template for closeMatch

### Rationale

During reconciliation we often find a useful URI, such as Wikipedia, that we would like to store for reference in an authority record.  Adding this during import will save time rather than reconciling it later.

### Expected behavior

Add new template column "closeMatch"
 - map this to hasCloseExternalAuthority

**Comment by GregReser** [comment]
@arwenhutt this one might need more review.

**Comment by gamontoya** [comment]
@GregReser Not ready for the next Sprint then?

**Comment by GregReser** [comment]
@gamontoya just want to get Arwen's input first

**Comment by arwenhutt** [comment]
@gamontoya I think we discussed this in person, but wanted to put it here as well:  this looks good to me :+1:

**Comment by gamontoya** [comment]
@jessicahilt Here's a ticket for Longshou to work on when he has the bandwidth.

**Comment by lsitu** [comment]
@GregReser I've added the closeMatch column to Subject Import tool. See PR https://github.com/ucsdlib/damsmanager/pull/201.
@mcritchlow The PR is ready for review now. Thanks.
