### ISSUE TITLE
Provide report on current MARC to CSV mapping

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#167]
### Descriptive summary

It would helpful to DOMM to have documentation of the current MARC to CSV mapping. 

### Rationale

See [https://github.com/ucsdlib/damsmanager/issues/162](url)

**Comment by lsitu** [comment]
@gamontoya The mapping of MARC to CSV is indirect and not obvious. Actually we first convert the MARCXML to MODS with the JollyRogger app, and then convert the MODS metadata to the CSV format that is inline with the Excel InputStream template.
What would you like to have in the documentation? Do the XSL stylesheets that we use to transform MARCXML to MODS (JollyRogger), and convert MODS to CSV (DAMS Manager) help?

**Comment by gamontoya** [comment]
@GregReser Can you respond to Longshou's inquiry above?

**Comment by GregReser** [comment]
@lsitu We sometimes need to figure out why data is not appearing, or is appearing in an unexpected place, in the output of the MODS to CSV (DAMS Manager).  When specifying a change to the output, it would help to know which indicators and subfields are already mapped so we could say "add this tag or subfield, delete this tag or subfield from the mapping"

Would it be possible to use the Excel Input Stream template and, in the cell below each column header, place the MARC tag, indicators an subfields that would be mapped there?

Where are the XSL stylesheets that we use to transform MARCXML to MODS (JollyRogger), and convert MODS to CSV (DAMS Manager)?

**Comment by lsitu** [comment]
@GregReser Here is the XSL stylesheet to transform MARCXML to MODS in JollyRoger:
https://lib-stash.ucsd.edu/projects/OD/repos/jollyroger/browse/src/webinf/MARC21slim2MODS.xsl

And the links in DAMS Manager to convert MODS to JSON format, and then CSV with codes:
https://github.com/ucsdlib/damsmanager/blob/develop/WebContent/files/dams42json.xsl
https://github.com/ucsdlib/damsmanager/blob/develop/src/edu/ucsd/library/xdre/tab/RDFExcelConvertor.java

It looks like it won't be easy to precisely express the MARC mapping to the  Excel Input Stream template, while mapping MODS to CSV is more straight forward. Please let me know if there's anything else that you would like me to do.

**Comment by mcritchlow** [comment]
This does make me wonder if a more direct mapping would make more sense for DAMS5. There's a lot going on here, and I wonder if we should consider cutting out some of the middle-people.

For example, UCSB (along with other Hydra folks) use [traject](https://github.com/traject/traject)

Here are some UCSB mappings using traject: https://github.com/ucsblibrary/alexandria/tree/master/lib/traject

Just a thought to consider for the DAMS5 equivalent of all this

**Comment by GregReser** [comment]
@lsitu I don't have permission to access https://lib-stash.ucsd.edu/login?next=/projects/OD/repos/jollyroger/browse/src/webinf/MARC21slim2MODS.xsl

Even so, it is a three part puzzle that's hard to make sense of.  I like the idea of moving to a simpler approach like UCSB is using.  If we do, we might still need to know what we are currently mapping so we can duplicate it (for example, our mapping of MARC Title might be different)>

Maybe the best thing to do would be to make a MARC tracer record to see how things are mapped.  

Would it possible to make a simple report of the mapping in our JollyRoger MARCXML to MODS transform?

**Comment by lsitu** [comment]
@GregReser Here is the XSL stylesheet that was renamed:
[MARC21slim2MODS.txt](https://github.com/ucsdlib/damsmanager/files/1242697/MARC21slim2MODS.txt)

Yes, we could do that but I think we just start from a standard conversion in the past and customized over time per DDOM requests. I found the following link could help us understand the conversion: https://www.loc.gov/standards/mods/mods-mapping.html. Does this format work?

**Comment by GregReser** [comment]
@lsitu Yes, this format looks great https://www.loc.gov/standards/mods/mods-mapping.html

**Comment by GregReser** [comment]
Since this has a very high LOE, I'm going to close it.
@mcritchlow do you want to open a separate issue to look at using something like [traject](https://github.com/traject/traject) ?

**Comment by lsitu** [comment]
@GregReser I am on a middle of it an I could have it done by Monday. Would you like me to continue my work on it?

**Comment by GregReser** [comment]
@lsitu Yes,  I misunderstood and didn't know you could do it.  That's great.

**Comment by lsitu** [comment]
@GregReser That's Okay. I'll continue to work on it then.

**Comment by mcritchlow** [comment]
@GregReser - Yeah, let's setup another ticket to look into Traject for DAMS5. I'll do that on Monday. Thanks!

**Comment by lsitu** [comment]
@GregReser Attached is the mapping of MARCXML to MODS, which is following the basic pattern in https://www.loc.gov/standards/mods/mods-mapping.html with some manipulations that could help understanding of our mappings. Please let me know if you have any questions. 
[MARC_MODS_Mappings.txt](https://github.com/ucsdlib/damsmanager/files/1258771/MARC_MODS_Mappings.txt)

**Comment by GregReser** [comment]
@lsitu This is great.  Thanks.
