### ISSUE TITLE
Report on file sizes for files in the CCDB collection

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#170]
### Descriptive summary
Could I get a report on the files in the Cell Centered Database collection (currently in curator) like the one generated with the DAMS Manager "File report" utility but also including file size value.  Please include "size not available" for files which do not have a <dams:size> element and value:  
e.g. https://library.ucsd.edu/dc/collection/bb4814883t/rdf  file name spin_filt_img.tar

### Rationale
This will help us check for problems on ingest or problems with source data.

**Comment by lsitu** [comment]
@arwenhutt Here is the report for all 2767 files found in CCDB:
[FileReport_CCDB.txt](https://github.com/ucsdlib/damsmanager/files/1264522/FileReport_CCDB.txt)


It looks like that the following 4 .tar files are empty: 
spin_filt_img.tar:    https://library.ucsd.edu/dc/object/bb4814883t/_2_1.tar
osaka3_img.tar:    https://library.ucsd.edu/dc/object/bb91493870/_2_1.tar
1wk-ly5-proj.tar:    https://library.ucsd.edu/dc/object/bb4541830q/_2_1.tar
1wk-ly6-proj.tar:     https://library.ucsd.edu/dc/object/bb19138181/_2_1.tar

**Comment by arwenhutt** [comment]
Thanks @lsitu ! very helpful :)
