### ISSUE TITLE
List of arks for all roles in D4

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#173]
### Descriptive summary
We would like to get a list of the arks for all the role values in DAMS 4 with the role label, preferably in a delimited or tabular format.  

Like:
Role label, Role ARK
Principal investigator, http://library.ucsd.edu/ark:/20775/bb5735317d
etc., etc.

**Comment by gamontoya** [comment]
@hweng Is this a task you could normally do or does it require Longshou?

**Comment by hweng** [comment]
@gamontoya I will work with Juliana to query the production database to get the Role label, Role ARK list.

**Comment by gamontoya** [comment]
@hweng Great, thank you!

**Comment by hweng** [comment]
@arwenhutt Here you go. I made up the query to D4 database. Attached please find all dams roles and arks exist in D4 database.

[DAMS_role_ark_value_list.txt](https://github.com/ucsdlib/damsmanager/files/1342604/DAMS_role_ark_value_list.txt)

**Comment by arwenhutt** [comment]
thanks @hweng, looks great!
