### ISSUE TITLE
Re-ingest Objects to Peter Yates Sound Recording Collection

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#174]
### Descriptive summary

Ingest DAMS production objects from the modified standard ingest spreadsheet, matching simple and complex objects to the existing ARKs in column A.
- 223 simple objects
- 25 complex objects
### Rationale

Because of problems with the original ingest, all objects were removed from [Peter Yates Sound Recording Collection](https://library.ucsd.edu/dc/collection/bb68616527) but the ARKs were kept so they can be re-used with the new metadata.

### File location
- Spreadsheet: digital-staging:\Yates\Final_Metdata\OLR_Yates.xlsx
- Files: digital-staging:\Yates\Final_Files

### Access/Rights for all objects
- Copyright	= "Under copyright"
- copyrightJurisdiction = US
- RightsHolder = "Unknown"
- OtherRights Permission type = "localDisplay"
- OtherRights OtherRightsBasis = "fair use (UCSD)"
  - for example, see http://librarytest.ucsd.edu/dc/object/bd7457390c

### Additional work
- There will be 1 less object than in the original ingest, so one original ARK will not be re-used
- After re-ingest is complete, IF ARK http://library.ucsd.edu/object/bb9968412k is not used, delete it.

**Comment by gamontoya** [comment]
@mcritchlow Another ticket for this Sprint if you need it.

**Comment by lsitu** [comment]
@GregReser Where can I find the Excel source metadata file and the master files for ingest? Thanks.

**Comment by GregReser** [comment]
@lsitu digital-staging:\Yates\Final_Metdata\OLR_Yates.xlsx
If you don't have access to staging, you can also get is from https://github.com/ucsdlib/dams-metadata/blob/master/Yates/OLR_Yates.xlsx

**Comment by lsitu** [comment]
@GregReser I got status 404. Maybe I don't have access to it?

**Comment by GregReser** [comment]
@lsitu, oh yeah, that's DOMM only.  Attaching the file here.
[OLR_Yates.xlsx](https://github.com/ucsdlib/damsmanager/files/1369301/OLR_Yates.xlsx)

**Comment by lsitu** [comment]
@GregReser Got it. Thanks. Where are those .wav files located?

**Comment by lsitu** [comment]
@GregReser Thanks. Did you see any issues in staging when ingesting with those provided ARKs?

**Comment by GregReser** [comment]
I used the standard ingest tool and couldn't reuse those ARKs - just did a regular ingest with new staging ARKs.  The objects were successful and the metadata was approved by the provider.

**Comment by lsitu** [comment]
@GregReser I see. I'll look into it. Thanks.

**Comment by lsitu** [comment]
@GregReser I tested it with the internal ark format like http://library.ucsd.edu/ark:/20775/bb0036580h and it works. Attached is the preview RDF/XML with the provided arks assigned: 

[preview-Yates-rdf.xml.txt](https://github.com/ucsdlib/damsmanager/files/1369650/preview-Yates-rdf.xml.txt)

And the updated Excel source I used:
[OLR_Yates_ark_updated.xlsx](https://github.com/ucsdlib/damsmanager/files/1369659/OLR_Yates_ark_updated.xlsx)


We only support the internal ark: format the but not the object ark URL at this time. But we can update damsmanager to support the object ark URL as well if you want.

Would you like to give it a retry with the internal ark: format, or prefer me to move forward with the re-ingest process?

**Comment by GregReser** [comment]
@lsitu The important thing is that it works, so use the internal ARK format that you tested.

**Comment by lsitu** [comment]
@GregReser Okay. I would just move forward with the ingest process then.

**Comment by lsitu** [comment]
@GregReser I've done with the test to ingest the objects in Yates collection into staging with those provided ARKs (curator access): https://librarytest.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Peter+Yates+Sound+Recording+Collection+-+ARK&id=bd51366892.

Could you take a look? I think we can do the ingest on prod if it looks good. Thanks.

**Comment by GregReser** [comment]
@lsitu they look great.  Go ahead with production ingest.

**Comment by lsitu** [comment]
@GregReser I've changed the [CLR for Peter Yates Sound Recording Collection](https://library.ucsd.edu/dc/collection/bb68616527) to curator view and the ingest is started on prod now.

**Comment by lsitu** [comment]
@GregReser I think we've got all 248 objects in Yates collection re-ingested on prod now: 
https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Peter+Yates+Sound+Recording+Collection&id=bb68616527

**Comment by gamontoya** [comment]
@GregReser Do things look good? If so, feel free to close this ticket.

**Comment by GregReser** [comment]
@gamontoya will do as soon as project manager data provider has approved
