### ISSUE TITLE
Create report for IDEAS Performance Series collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#175]
### Descriptive summary

Create a report (tab delimited or csv) for the [IDEAS Performance Series collection](https://library.ucsd.edu/dc/collection/bb4029917n). The report should include:

- ARK
- Local filename
- Title
- Description

**Comment by hweng** [comment]
@gamontoya 
Just to clarify, the Local filename is for master filename, correct? 
And the description is retrieved from "<dams:Note><dams:type>description</dams:type><rdf:value>...", correct?  For the following example, it is "<rdf:value>IDEAS aims to encourage.........from the ongoing series. </rdf:value>"

<dams:note>
<dams:Note>
<dams:type>extent</dams:type>
<rdf:value>26 digital objects.</rdf:value>
</dams:Note>
</dams:note>
<dams:note>
<dams:Note>
<dams:type>description</dams:type>
<rdf:value>
IDEAS aims to encourage interdisciplinary artists and musicians, as well as engineers and scientists to take advantage of the Qualcomm Institute’s advanced audio-visual facilities, services and personnel in staging performances and presentations of new or existing works and research. This collection contains video, still images, audio, and text, documenting past performances and presentations from the ongoing series.
</rdf:value>
</dams:Note>
</dams:note>

**Comment by gamontoya** [comment]
@hweng That's correct.

**Comment by hweng** [comment]
@gamontoya Attached please find the report(tab delimited) that I made for IDEAS collection which includes all items title, local file name in the complex objects and the description and titles for all top level objects.
[IDEAS_report.txt](https://github.com/ucsdlib/damsmanager/files/1416364/IDEAS_report.txt)

**Comment by gamontoya** [comment]
@hweng Thank you. Looks good!
