### ISSUE TITLE
Report on roles used with authority records

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#176]
### Descriptive summary
Attached is a list of ARKS.  
[arks_for_role_report_request.txt](https://github.com/ucsdlib/damsmanager/files/1360505/arks_for_role_report_request.txt)

These are the ARKS included in the subject conversion work which have an existing record type of the name class, and which will continue to have a name class record type post conversion.  

Is it possible to get a report with:
- ARK
- Related to record type: direct subject, direct rights holder, relationship
- Roles related to relationships

### Rationale
For the subject conversion process, names are complicated by the different ways they can be associated with a record:
- directly linked to OLR/CLR => representing a name as a subject
- directly linked to OLR/CLR = > as a rightsHolder(Corporate|Personal)
- linked to an object through a relationship blank node

The last case is further complicated by there being additional role data in the relationship node. 

While role data was not included in the original authority record exports, @mcritchlow suggested that we ask if it's possible to get role data.  This data may help simplify the processing instructions for name records during subject conversion.

### Related work
https://github.com/ucsdlib/damspas/issues/355

**Comment by arwenhutt** [comment]
@mcritchlow I'm concerned that this will be a difficult report to generate, with low potential for being useful.  Take a look at it and see what you think.  Thanks!

**Comment by arwenhutt** [comment]
@mcritchlow I'm concerned that this will be a difficult report to generate, with low potential for being useful.  Take a look at it and see what you think.  Thanks!

**Comment by mcritchlow** [comment]
@arwenhutt - yeah, I'll defer to @lsitu on this regarding LOE. He should be able to start looking into this first thing next week and we can take it from there.

**Comment by arwenhutt** [comment]
Sounds good!

**Comment by lsitu** [comment]
@arwenhutt Finally my process for the roles used in the authority records was done over the weekend. Here is the report:
[report-roles.txt](https://github.com/ucsdlib/damsmanager/files/1388093/report-roles.txt)

The report includes the following fields:
DAMS ARK, Name Type, AuthoritativeLabel, Subjects Count, Subject Example, RightsHolders Count, RightsHolder Example, Relationships Count, Roles, Relationship Example

Note that some of the arks are not Name authorities but subject types like mads:Geographic. I hope the report includes all information you want. Please let me know if you need anything else. Thanks.

**Comment by gamontoya** [comment]
@arwenhutt Final report added here. Please close out this ticket unless you need something more.

**Comment by arwenhutt** [comment]
@lsitu thanks! I haven't had a chance to look at it yet, but will as soon as I can.
@gamontoya I'll close this then too.

**Comment by gamontoya** [comment]
@lsitu Good work!

**Comment by arwenhutt** [comment]
@lsitu I haven't had a lot of time with this, but it looks good!  Thanks!
