### ISSUE TITLE
Add otherRights override to Blackburn collection objects

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#179]
### Descriptive summary

The [Blackburn collection](https://library.ucsd.edu/dc/collection/bb8158593z) was ingested under copyright with rights holders, but with no override. Thus, when trying to release the collection as public, it remains curator-only.  

We need to assign the objects in the collection the 'Public - granted by rights holder' override, so that the collection can be publicly released.

**Comment by VivianChu** [comment]
@remerjohnson - The objects in this collection have been updated with license override.  They are publicly released now.  https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Paul+Blackburn+Audio+Collection&id=bb8158593z

**Comment by remerjohnson** [comment]
@VivianChu Thanks so much, Vivian :smile:
