### ISSUE TITLE
Excel input stream - add new director roles

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#180]
### Descriptive summary

Update Excel input template to support two new roles

Associate Director: http://library.ucsd.edu/ark:/20775/bb5429571b (http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb5429571b)

Co-Director: http://library.ucsd.edu/ark:/20775/bb67265096 (http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb67265096)

New valid column headers (case insensitive):
- Person:Associate Director
- Person:Co-Director

There are other new columns (V, W, X, Y) that will be used to track rights metadata, but they should be ignored during the ingest process.
These columns should not cause a validation error and should not create any properties on ingest:
- Access granted
- Copyright status
- Copyright holder
- CC license

New Excel template:
[xls_standard_input_template.xlsx](https://github.com/ucsdlib/damsmanager/files/1391844/xls_standard_input_template.xlsx)

### Related work
Addition of two roles to DAMS #57

**Comment by gamontoya** [comment]
@GregReser Is this for DAMS 4 or 5?

**Comment by GregReser** [comment]
DAMS 4.  See comment from Longshough in https://github.com/ucsdlib/damsrepo/issues/57

**Comment by gamontoya** [comment]
@lsitu Adding to this Sprint for you.

**Comment by lsitu** [comment]
@gamontoya Sure. It's done with PR https://github.com/ucsdlib/damsmanager/pull/181 now.
And I think we can move the PR forward once @mcritchlow is back from vacation.

**Comment by GregReser** [comment]
3 of the rights column headers are returning as invalid.  These need to be allowed, even though nothing is being ingested for them.
[xls_standard_input_test.xlsx](https://github.com/ucsdlib/damsmanager/files/1428311/xls_standard_input_test.xlsx)

Invalid control value(s) - 
* Row index 2 [Access granted => Access granted | CC license => CC license | Copyright status => Copyright status]

**Comment by lsitu** [comment]
@GregReser It looks like Access granted, Copyright status, Copyright holder, and CC license
are something new in the latest Excel Input Stream template that I don't aware of. And the value like "Access granted" used in your test is not a valid CV for header "Access granted", which should be one of the followings as defined in the "CV values" tab:
Library curators   only
UCSD IP only
The world - metadata and files
The world - metadata only
The world - cultural sensitivity click   through

So damsmanager complained about it with the "Invalid control value(s)" message. 

There will be a couple of issues in supporting these column headers:
- These headers may be conflicting with the fields in the Excel Import form https://library.ucsd.edu/damsmanager/excelImport.do. I think we may need some discussions regarding the implementation.
- We don't have any mapping implemented in damsmanager for these column headers in the Excel Import template yet. 

I think we had better create another ticket to discuss and implement the support for these column headers. What do you think?

**Comment by GregReser** [comment]
@lsitu The new columns were specified in this ticket (see the description at the top).
We do not need these columns to do anything at this time - they should just be ignored and not cause a validation error.  The cell contents for these columns should also be ignored.

We use these columns to help us identify rights for individual rows.  We want to leave them in the spreadsheet to help us track the rights before and after ingest.  We will still use the rights settings in https://library.ucsd.edu/damsmanager/excelImport.do - no change is necessary to this at this time.

When we move to DAMS 5, we will incorporate these columns into the ingest stream, but for now these columns should be allowed in the spreadsheet but completely ignored during ingest.
/xls_standard_input_template.xlsx)

**Comment by lsitu** [comment]
@GregReser Got it. Thanks. In this case, the issue is that damsmanager is able to identify and validate the columns headers and CVs automatically. I think it might not be a good approach to add custom codes to ignore some of the columns. Instead we can just do it in the following two ways:
1. Fix the test Excel source to use the valid CVs specified in the "CV values" tab for "Access granted", "Copyright status", and "CC license".
2. Use different headers in the "CV values" tab for "Access granted", "Copyright status", and "CC license", something like "Access  granted" (double white spaces), "Access-granted", "Access_granted" will work.

I think using valid CVs make sense since the purpose of those values will be used to identify rights for individual rows. What do you think?

**Comment by GregReser** [comment]
@lsitu OK, that is a good idea.
Let's use valid CVs.  Then I don't have to change the headers in the "CV values" tab, right?
Here is a new test file.
[xls_standard_input_test.xlsx](https://github.com/ucsdlib/damsmanager/files/1432144/xls_standard_input_test.xlsx)

**Comment by lsitu** [comment]
@GregReser Correct. The headers in the CV values tab doesn't need to change. I tested it with the test file above and it looks good. Thanks.

**Comment by GregReser** [comment]
@lsitu Excellent!  Is it in staging for testing?

**Comment by lsitu** [comment]
@GregReser Yes. Just test it on staging.

**Comment by GregReser** [comment]
@lsitu Looks great.  This will be very helpful for us.
