### ISSUE TITLE
Re-structure objects in Catalhoyuk collection

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#182]
### Descriptive summary

The [Catalhoyuk collection](https://library.ucsd.edu/dc/collection/bb16752349), within each object, has a certain component group of three files: a .obj file, a .jpg file and .mtl file. (These are all currently sub-components, if that has any relevance)  

We need to replace those 3 files in each object with one newly-created zip.  

Let me know exactly what information you would need from me for this, e.g. a tabular list of object ARK, current files, file to replace those, etc.  

### Rationale

In order for users to use this group of files in especially 3D applications, the filenames need to be preserved, and so we are going to package (zip) those 3 files together into one component for each object.

**Comment by mcritchlow** [comment]
@ucsdlib/developers could someone take this for next Sprint please?

**Comment by lsitu** [comment]
@remerjohnson Do you have the zip files for those three files (a .obj file, a .jpg file and .mtl file)  in each object that you want to replace?

**Comment by remerjohnson** [comment]
@lsitu I do have the zips, but was wondering what is the data that would most help here?
Column A - ARK
Column B - .obj .jpg .mtl files to replace
Column C - .zip file that replaces files in Column B

**Comment by lsitu** [comment]
@remerjohnson I think one ark for one row/Object works better. So either split Column B into three columns for each file, or put all the file names in column B will be fine.
Do you want to remove all the Sub-components for .obj .jpg .mtl files and ingest the .zip file into the parent component? 
Do you any metadata need to change, for example the component title?
Thanks.

**Comment by remerjohnson** [comment]
@lsitu Good questions. I'll have to get back to you on that, but I will be at Connect next week, so it might be a while before I could produce the data

**Comment by lsitu** [comment]
@remerjohnson No problem. I'll work on it once it's ready. Have a nice Trip!

**Comment by hjsyoo** [comment]
@remerjohnson As a reminder, we have an edited version of the OLR that could be rearranged to produce what @lsitu needs.
https://docs.google.com/spreadsheets/d/1t5AyXWNCLOzLQI52kboyltBMpdjpE7PvfXjS2bcgd4w/edit#gid=608775816
 If you'd like my proj assts to work on this, I can assign them the task. @lsitu, yes, I'd like all the subcomponents for .obj, .jpg, .mtl files to be removed, and Ryan's .zip's to be ingested into the parent component. The parent component titles (e.g., "Layer No. 21902") should be retained. In a few cases, the metadata from the subcomponents need to be moved up into the parent component, because the parent component should contain all the metadata that was in the subcomponents, before they are deleted. The google doc has the correct, full metadata for those parent components. @lsitu, let me know if there's anything you need us to do to make this task easier for you. Thanks.

**Comment by lsitu** [comment]
@hjsyoo Thanks. I think I only need the .zip files for those three components with the object ARK mapping.
@remerjohnson If all objects has three files with the same file extensions (.obj .jpg .mtl) and it won't conflict with other components in those objects, then I think we don't need "Column B - .obj .jpg .mtl files to replace", which could make your work easier.
Thank you both.

**Comment by hjsyoo** [comment]
@lsitu I should be able to get that list to you tomorrow afternoon.

**Comment by hjsyoo** [comment]
@lsitu The .zip file-to-object-ARK mapping file is ready for you: https://docs.google.com/spreadsheets/d/1t5AyXWNCLOzLQI52kboyltBMpdjpE7PvfXjS2bcgd4w/edit#gid=987009751.
The .zips are located in \rdcp-0098-catalhoyuk-bldg89\Final_Files. Please let me know if you need anything else.

**Comment by lsitu** [comment]
@hjsyoo Thanks. I don't have permission to access the mapping file. Could you attach/upload it here?

**Comment by hjsyoo** [comment]
@lsitu It's the Github #182 tab in this file:
[Restructuring Catalhoyuk Bldg 89.xlsx](https://github.com/ucsdlib/damsmanager/files/1451731/Restructuring.Catalhoyuk.Bldg.89.xlsx)

**Comment by lsitu** [comment]
@hjsyoo It looks good. Thanks. I see four other columns for descriptive metadata: Title, Note:description, Note:material details:relationship to other loci, Note:note. 
Do we need to deal with this columns?

**Comment by hjsyoo** [comment]
@lsitu No need to deal with the Note or TItle columns. I'll ask @remerjohnson directly to make any needed edits for the Note properties. I think there were only 1 or two objs that needed editing. Thanks.

**Comment by lsitu** [comment]
@hjsyoo @remerjohnson All objects in the collection are restructured and the replacement .zip files are ingested on prod now: https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Data+from%3A+Immersive+Visualization+and+Curation+of+Archaeological+Heritage+Data%3A+%C3%87atalh%C3%B6y%C3%BCk+and+the+Dig%40IT+App&id=bb16752349.
I see component with label "Layer No. 30928" (file U30928.zip) show up twice in objects https://library.ucsd.edu/dc/object/bb8398846n (row# 29) and https://library.ucsd.edu/dc/object/bb64193073 (row# 44). Please let me know if you need any changes.

**Comment by hjsyoo** [comment]
@lsitu Thanks! The replacements have been verified and everything looks great. @remerjohnson We just have some metadata that needs to be edited - those issues are reported in https://github.com/ucsdlib/dams-metadata/issues/45.
