### ISSUE TITLE
Change authority label matching in import tools: spaces and punctuation

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#183]
### Descriptive summary

Ignore leading, trailing, multiple spaces and punctuation when matching labels between import tools and DAMS authority records.  Also confirm that matches are not case-sensitive.
Tools affected:
- Subject Import Tool
- Collection Import Tool
- Excel Standard Import tool

### Rationale

We want to avoid creating new authorities for the same topic, name, or place because the import label contains extra spaces, punctuation, or has different capitalization. It is extremely unlikley that these differences would indicate an import label has a differerent meaning than an exisiting authority.

### Expected behavior

- Confirm label match is not case-sensitive
  - "Open-air zoos" == "open-air zoos"
- Ignore leading, trailing, multiple spaces
  - "Open-air zoos" == " Open-air zoos "
  - "Open-air zoos" == "Open-air&nbsp;&nbsp;&nbsp;zoos"
- Ignore spaces around punctuation
  - "Open-air zoos" == " Open - air zoos"
- Ignore punctuation
  - "Open-air zoos" == "Open-air zoos." 
  - "Open-air zoos" == "Open-air--zoos" 
  - "Open-air zoos" == "Open air zoos"  
  - "Open-air zoos" == "Open air, zoos" 
  - include all standard punctuation...

**Comment by lsitu** [comment]
@GregReser I think # 1 (Confirm label match is not case-sensitive) and the first part of # 2 (Ignore leading, trailing) should be supported at this time. Do you see any issues with it?

With # 4 (Ignore punctuation) , it looks like we may need new implementation strategics for matching since SPARQL won't work in this case and SOLR indexing is delayed, which will produce duplications. Do you have a full list of punctuations that we want to ignore?

**Comment by lsitu** [comment]
@GregReser Do we need to ignore all of the following punctuations?
\ / | [ ] ( ) { } , . : ; ? '  " ~ ` ! @ # $ % & * < > + - _ =

**Comment by GregReser** [comment]
@lsitu # 1 (Confirm label match is not case-sensitive) and the first part of # 2 (Ignore leading, trailing) should be supported at this time.  - this is currently working, just being clear about all all expected results.

Yes, that is a good list of punctuation to ignore.

**Comment by lsitu** [comment]
Thanks @GregReser. I'll use the punctuation list above as the starting point then.

**Comment by lsitu** [comment]
@mcritchlow PR https://github.com/ucsdlib/damsmanager/pull/188 is ready for review now. Thanks.
