### ISSUE TITLE
Fix database error for Oct 16 statistics

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#186]
### Descriptive summary

DAMS usage statistics for Oct. 16 are missing:

https://library.ucsd.edu/damsmanager/stats.do

### Per Longshou

I see it failed with a weird database insert error now. Somehow we have a wrong URL logged like:
 bb00695483/1.pdf&sa=U&ved=0ahUKEwjBtpmstvbWAhXEDxoKHdJUA-84FBAWCBQwBA&usg=AOvVaw3BYj0-Cp0-dQJLQnynQQuK%22.

There is no question mark to separate the parameters, which should be fed by someone else.

**Comment by lsitu** [comment]
Hi Gabriela,
I've added PR https://github.com/ucsdlib/damsmanager/pull/187 to ignore those invalid dams URL, which will avoid the database error. FYI, the hits for 10/16/2017 is 2062.
@mcritchlow The PR is ready for review now. Thanks.
