### ISSUE TITLE
Fix incorrect Component numbering in Catalhoyuk collection

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#189]
### Descriptive summary

Following on the work of https://github.com/ucsdlib/damsmanager/issues/182, a new issue has arisen. The components were properly compressed as requested, but component numbering and component advance arrow functionality are now messed up.

In all objects of the collection (https://library.ucsd.edu/dc/collection/bb16752349) that have more than one component titled "Layer No. #####", the last set of components are incorrectly numbered. For example, in https://library.ucsd.edu/dc/object/bb51564927, "Layer No. 21904" and "Layer No. 21907" are referenced as "Component 8 of 6" and "Component 9 of 6".

Also, when advancing through the components using the right arrow key, any layers after the first layer component can't be accessed. The component advance gets stuck, and no actual component is displayed. See screenshot (https://library.ucsd.edu/dc/object/bb51564927):

![image](https://user-images.githubusercontent.com/10660549/32911160-2f00b68c-cac0-11e7-8e51-a9cbbf45b751.png)

### Related work

https://github.com/ucsdlib/damsmanager/issues/182

**Comment by gamontoya** [comment]
@lsitu Let me know if the level of effort is high for this.

**Comment by lsitu** [comment]
@gamontoya It seems like that this is a damspas ticket for fixing the display issue for components. However, we can fix it in the metadata level but I don't know how many files were ingested in those components that has gaps in component numbers due the deletion of the files previously. We may need to re-ingest the files if we restructure the component orders. In this case, re-ingest those objects seem easier.

**Comment by lsitu** [comment]
@hjsyoo It's a nice to have that list. Thanks.

**Comment by gamontoya** [comment]
@lsitu So which do you prefer? Fixing at the metadata level or re-ingesting the collection?

**Comment by lsitu** [comment]
@gamontoya Let's see how many objects and files are affected. We don't need to ingest the whole collection but only those objects with component files that are affected.

**Comment by hjsyoo** [comment]
There are 20 objects:

https://library.ucsd.edu/dc/object/bb00028666
https://library.ucsd.edu/dc/object/bb0241779k
https://library.ucsd.edu/dc/object/bb13680656
https://library.ucsd.edu/dc/object/bb17093631
https://library.ucsd.edu/dc/object/bb21871842
https://library.ucsd.edu/dc/object/bb2801523b
https://library.ucsd.edu/dc/object/bb3825425n
https://library.ucsd.edu/dc/object/bb4303245q
https://library.ucsd.edu/dc/object/bb51564927
https://library.ucsd.edu/dc/object/bb5327150w
https://library.ucsd.edu/dc/object/bb5975614d
https://library.ucsd.edu/dc/object/bb64193073
https://library.ucsd.edu/dc/object/bb6794734s
https://library.ucsd.edu/dc/object/bb7784509z
https://library.ucsd.edu/dc/object/bb8091679t
https://library.ucsd.edu/dc/object/bb85353672
https://library.ucsd.edu/dc/object/bb85353693
https://library.ucsd.edu/dc/object/bb8569497r
https://library.ucsd.edu/dc/object/bb9354491t
https://library.ucsd.edu/dc/object/bb99346995

**Comment by hjsyoo** [comment]
I'm estimating, based on my worksheet, that 36 components (all starting with "Layer No....") will need renumbering.

**Comment by lsitu** [comment]
@hjsyoo Thanks. I think the component ordering issue in those 20 objects above should be fixed now.

**Comment by hjsyoo** [comment]
Thanks @lsitu! My student assistant, @anrastog, has verified that the fixes are correct. Closing the ticket.

**Comment by lsitu** [comment]
@hjsyoo I am glad it works for you.
