### ISSUE TITLE
Create a report of all objects in collection: INGEST Fletcher batch 4

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#194]
### Descriptive summary

Because the ingest to INGEST Fletcher batch 4 (bb4200993n) in production was interrupted by a restart of ActiveMQ server, only 229 or 360 objects were created.  No DAMS manager report was generated for the ingest, so we need to know which objects were created so we can ingest the remaining items in the spreadsheet.

### Task
Create a CSV report of all objects in the collection: https://library.ucsd.edu/dc/collection/bb4200993n

Report contents:

1. ARK
2. Title / authoritativeLabel
3. dams:hasFile / dams:use = image-source  / sourceFileName  (example: m81b81f34i003.tif)

**Comment by gamontoya** [comment]
@jessicahilt @mcritchlow Jessica: Do you have a developer that wants to take this on this Sprint?

**Comment by lsitu** [comment]
@gamontoya I can work on it.

**Comment by gamontoya** [comment]
@lsitu Thank you!

**Comment by lsitu** [comment]
@GregReser Attached is the report:
[report-Fletcher-btach4.txt](https://github.com/ucsdlib/damsmanager/files/1528016/report-Fletcher-btach4.txt)

**Comment by gamontoya** [comment]
Thank you @lsitu !

**Comment by GregReser** [comment]
@lsitu looks great, thanks.
