### ISSUE TITLE
Revise JIRA DAMS ingest workflow and template; create subtasks

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#195]
### Descriptive summary

We would like to modify the current JIRA DAMS ingest workflow in order to:

- Clarify and enforce requirements needed for ingest work to proceed
- Make workflow more self explanatory within JIRA so that external documentation doesn't need to be referred to as often
- Add explicit statuses for some workflow states that aren't currently represented
- Improve clarity of tracking QA work by using sub-tasks

### Modify DI workflow

- Using the diagram "new_jira_DI_workflow.jpg"
  - Create statuses and transitions
  - Add DI sub-task(s)
    - Require that a sub-task is closed before DI status change (DI Pending status can be applied at any time)
    - Would it be possible add multiple sub-task types?  How does this affect sub-task creation and display within the DI UI?  Would this help sub-task closed verification?

### Modify DI issue template

- Using the example "new_jira_DI.jpg"
  - Revise template fields

### Create DI subtask template

- Using the example "new_jira_DI_subtask.jpg"
  - Create template

**Comment by GregReser** [comment]
[di-workflow_2017-12-07.pptx](https://github.com/ucsdlib/damsmanager/files/1540071/di-workflow_2017-12-07.pptx)
![new_jira_di](https://user-images.githubusercontent.com/5453716/33730181-0939f18c-db34-11e7-92db-8edf07d02edc.jpg)
![new_jira_di_subtask](https://user-images.githubusercontent.com/5453716/33730182-09a33a16-db34-11e7-9a65-2779abf427c2.jpg)

**Comment by GregReser** [comment]
[di-workflow_2017-12-07.pptx](https://github.com/ucsdlib/damsmanager/files/1540073/di-workflow_2017-12-07.pptx)

**Comment by GregReser** [comment]
![new_jira_di](https://user-images.githubusercontent.com/5453716/33730214-226c640a-db34-11e7-8fcf-cada4d99fc16.jpg)

**Comment by GregReser** [comment]
![new_jira_di_subtask](https://user-images.githubusercontent.com/5453716/33730222-29711b9c-db34-11e7-87f4-a5ed6f4ef95e.jpg)

**Comment by mcritchlow** [comment]
@GregReser - I should be able to do this for ya'll. I'll start reading through this more carefully and let you know if I come up with any questions. One thing at a quick pass, is I'm not sure whether the Sub-Task form template is customizable, since it's a global thing to JIRA. I'll look into it, just a heads up that we may run into limitations there.

**Comment by mcritchlow** [comment]
@GregReser - Ok, I think I've got the DI Issue Template modified per your instructions. Can you take a look and let me know if things look  OK to you? Will look at the workflow stuff next.

**Comment by mcritchlow** [comment]
RE: Modify DI workflow

> Require that a sub-task is closed before DI status change (DI Pending status can be applied at any time)

I'm afraid there's no way to explicitly enforce this. The workflow for the DI issue type isn't really connected in any way to the child (sub-task) workflow. Can you all manage it via policy/best practice?

> Would it be possible add multiple sub-task types? How does this affect sub-task creation and display within the DI UI? Would this help sub-task closed verification?

I'm afraid not. Sub-task is a JIRA global issue type that are treated differently than the standard types. Sorry.

**Comment by mcritchlow** [comment]
@GregReser - Ok, I've done an initial pass at modifying the workflow. There are currently two issues I'm trying to sort out. Basically there are now two workflow steps (Ingest, Release QA) which are no longer linked to anything. For whatever reason, I'm having a hard time figuring out how to delete them.. But if you wouldn't mind creating a test ticket or two and running through the workflow I'd appreciate it. I _think_ I got all the transitions, but there are a lot :)

**Comment by GregReser** [comment]
@mcritchlow I see the requirements check boxes in the "Create Issue" screen but not on the issue screen.
Also, is it possible to require these be checked before moving from Open to MD wrangling?
![image](https://user-images.githubusercontent.com/5453716/33859739-2e680c24-de8a-11e7-989f-2a9ebbe4b57c.png)

**Comment by GregReser** [comment]
@mcritchlow I neglected to add "Embargo until" to the DI template.  Please add it beneath "Attachment"

**Comment by mcritchlow** [comment]
> I see the requirements check boxes in the "Create Issue" screen but not on the issue screen.

Could you give me a link of screenshot of where you were hoping to see it? Sorry, there are so many "screens" in JIRA..

> Also, is it possible to require these be checked before moving from Open to MD wrangling?

Nope, sorry :(

> I neglected to add "Embargo until" to the DI template. Please add it beneath "Attachment"

Ok this is done. Let me know if that's what you were expecting

**Comment by GregReser** [comment]
I was hoping to see the requirements in this view - the ongoing, working issue screens.  An issue might be opened with no requirement boxes checked.  After all boxes are checked, the issue would be ready for the MD wrangling step.  
Also, we want to see the "Embargo until" field in this same view.
![image](https://user-images.githubusercontent.com/5453716/33892589-0556376e-df0e-11e7-81d0-26197cd81ba5.png)

**Comment by GregReser** [comment]
@mcritchlow in the issue window, is it possible to control the order of the elements in the Workflow dropdown?  It would be much easier to select the next step from Pending if it followed the workflow.

MD Wrangling
Ingest MD QA
Staging Ingest
Staging QA
Production subject ingest
Production CLR ingest
Production OLR ingest
Production QA
Publish
Embargoed
Access verification
Close

![image](https://user-images.githubusercontent.com/5453716/33902319-7d45d6ce-df29-11e7-8142-81dd73bccad4.png)

**Comment by GregReser** [comment]
Updated status , transition labels and tooltips.
![image](https://user-images.githubusercontent.com/5453716/34123343-0e75f520-e3e4-11e7-9532-baa8d1669ccd.png)

**Comment by mcritchlow** [comment]
@GregReser - I think I addressed everything via our slack conversation. Are there other edits needed?

**Comment by GregReser** [comment]
@mcritchlow It's looking very good.  I've been using it for a new ingest and it works well.
One request: for the Requirements field, please change the label of the first checkbox to "[click to edit]"

**Comment by mcritchlow** [comment]
@GregReser - you got it, done.

**Comment by GregReser** [comment]
@mcritchlow this looks great.  If we need any changes, I'll open a new issue.  
Thanks for all your work on this.

**Comment by mcritchlow** [comment]
sounds like a plan, I hope it's a helpful improvement for your team's workflow!
