### ISSUE TITLE
Generate a table of Catalhoyuk-bldg89 component titles and URLs

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#197]
### Descriptive summary

The database manager for catalhoyuk.com would like to create links from his database to components within our Catalhoyuk collection at https://library.ucsd.edu/dc/collection/bb16752349. To facilitate this work, please generate a CSV table for all components within this collection, containing the following metadata for each component:

* Object title (e.g., Building 89, Model F3484_03_U30928_Skeleton)
* Object ARK (e.g., https://library.ucsd.edu/dc/object/bb8398846n)
* Component title (e.g., Layer No. 30928)
* Component URL (e.g., https://library.ucsd.edu/dc/object/bb8398846n/_4_1.zip/download)

### Related work

Link to related tickets or prior related work here.
https://lib-jira.ucsd.edu:8443/browse/CPP-98

**Comment by gamontoya** [comment]
@jessicahilt Here's another ticket that can be assigned.

**Comment by hweng** [comment]
@hjsyoo  Attached please find the report I made for Catalhoyuk collection objects and components. There are some components don't have downloadable urls, such as the 5th, 6th, 7th components in https://library.ucsd.edu/dc/object/bb13680656, which I left it blank.

[Catalhoyuk_collection_report.xlsx](https://github.com/ucsdlib/damsmanager/files/1583370/Catalhoyuk_collection_report.xlsx)

**Comment by hjsyoo** [comment]
Thanks, @hweng! One question - I can't access the ARKs in this format: http://library.ucsd.edu/ark:/20775/bb00028666
I'm assuming this is not a publicly accessible link, correct? If so, is there any reason for me to provide it to a non-Library party?

**Comment by hweng** [comment]
@hjsyoo I got "Service Temporarily Unavailable": https://library.ucsd.edu/dc,
I will try it late.

**Comment by hweng** [comment]
@hjsyoo Yes, the format http://library.ucsd.edu/ark:/20775/bb00028666 worked before but in DAMS4 it is not accessible link.
But In the report I provide the file(component) download url: https://library.ucsd.edu/dc/object/bb00028666/_1_2.jpg/download which is accessible links, which he can code using ARK as the above format.
There are a few object components which don't have downloadable files available, I left it as blank in the component URL column, such as https://library.ucsd.edu/dc/object/bb13680656, component 4, 5, 6,7 
Let me know if you have any other question, or need more data/information for the report?

**Comment by hjsyoo** [comment]
@hweng  I think he will only need the component URLs that are accessible, if I understand correctly. Yes, it's fine to leave blanks for components that do not have downloadable files, since I'm not sure if he needs to point to them, and since we don't have component-level ARKS yet. Thanks so much for your help!

**Comment by hweng** [comment]
@hjsyoo You are very welcome. Do you want me to update the report for ARK column to remove "http://library.ucsd.edu/ark:/20775/" since it is not working url?
This format of url was actually retrieved from RDFs: <dams:Component rdf:about="http://library.ucsd.edu/ark:/20775/bb00028666/1">

**Comment by hjsyoo** [comment]
No need! I'll modify it and send it along. Thank you!
