### ISSUE TITLE
Restrict ~135 images in CCAS Pickowicz collection to curator-only access

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#200]
### Descriptive summary

The researcher for the [CCAS Paul Pickowicz collection](https://library.ucsd.edu/dc/collection/bb5737145r) has indicated that around 135 of the images in production should be restricted. Please change the access state for these objects to curator-only access.  

Attached is a sheet with the data, most importantly the ARK and associated access level for each object. Let me know if the data needs to be changed. Thanks. 

**Also note:** The collection has not been released yet, if that is important information :smile: 
 
[ccas_pickowicz_access_levels.xlsx](https://github.com/ucsdlib/damsmanager/files/1627734/ccas_pickowicz_access_levels.xlsx)

**Comment by gamontoya** [comment]
@jessicahilt Can Longshou take this one on? @remerjohnson can confirm, but I think this needs to be done before next Wednesday.

**Comment by lsitu** [comment]
@gamontoya @jessicahilt Sure. I'll work on it.

**Comment by lsitu** [comment]
@remerjohnson What license would you like for those restricted objects? It look like these restricted objects currently have a public license as follows:
<dams:license>
<dams:License>
<dams:licenseNote>Public access granted by rights holder.</dams:licenseNote>
<dams:permission>
<dams:Permission>
<dams:type>display</dams:type>
</dams:Permission>
</dams:permission>
</dams:License>
</dams:license>

I think we could simply remove this public license if you want. Thoughts?

**Comment by remerjohnson** [comment]
@lsitu That may work. Do you know if that will be fine once those objects are released?

**Comment by lsitu** [comment]
@remerjohnson I think so if all these objects are "under copyright". But it will be safe to add a restricted license if you are not sure.

**Comment by remerjohnson** [comment]
@lsitu Yes, I believe they were all ingested with the "Copyrighted (Person)" selection in the ingest form, with Paul Pickowicz as the rights holder.

**Comment by lsitu** [comment]
@remerjohnson Then I believe it'll work.

**Comment by lsitu** [comment]
@gamontoya @remerjohnson I've deleted the "Public access granted by rights holder." license from  those 129 curator-only objects in the Excel source file ccas_pickowicz_access_levels.xlsx above. So all those objects should be curator-only access now. Could you take a look?

**Comment by remerjohnson** [comment]
@lsitu @gamontoya Sorry for the delay: this fix could only really be tested after releasing the collection. As of now, there are 556 public images, and 129 curator-only, which correctly adds up to the extent, 695. So we should be good. Thanks for the speed of this work.

**Comment by remerjohnson** [comment]
@gamontoya @lsitu I've released the collection in order to test the fix, and it all adds up. Thanks for the speedy work on this
