### ISSUE TITLE
Add PowerPoint file to a Holocaust Living History Workshop collection object

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#202]
### Descriptive summary

Dr. Grishaver would like to have his PowerPoint presentation added to his lecture: 
* Archival Footprints: In Search of the Grishavers
  * https://library.ucsd.edu/dc/object/bb19135044

This would turn bb19135044 into a complex object, with the existing video lecture being one component, and this PowerPoint becoming the second component.  

### Location of File
* digital-staging:\HLHW_lectures\Grishaver-2015 (ignore `README.txt`)

### Metadata
For metadata consistency's sake, we could take cues from the [IDEAS collection](https://library.ucsd.edu/dc/object/bb9320112b): 
* The existing lecture video will have the component title "Program"
* The PowerPoint will have the component title "Program Slides". 
  * The File Use value will be "data-service"

If any other metadata is needed, feel free to ask

### Related work

ucsdlib/dams-metadata/issues/58

**Comment by lsitu** [comment]
@remerjohnson We may need to re-ingest the existing lecture video master file. Do you know where's the original source file?

**Comment by gamontoya** [comment]
@lsitu I believe the original master file was deleted from digital-staging some time ago.

**Comment by lsitu** [comment]
@gamontoya Okay, I'll use the copy in the filestore for re-ingest then. Thanks.

**Comment by remerjohnson** [comment]
@hjsyoo I believe Gabriela is right, I cannot find the original video anywhere

**Comment by lsitu** [comment]
@remerjohnson Thanks. It seems like we have no other choices but the one in the filestore.

**Comment by lsitu** [comment]
@gamontoya @remerjohnson I've added the PowerPoint file to object https://library.ucsd.edu/dc/object/bb19135044 and restructure it to a complex object. It's ready on prod for review now. Thanks.

**Comment by gamontoya** [comment]
Looks great! Thank you @lsitu
