### ISSUE TITLE
Set 13 objects from Scripps Institution of Oceanography Photographs to "Curator Only"

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#203]
### Descriptive summary

~~At the request of Special Collections, delete the following objects from production:~~

#### Per DLDP, change the status of the following 13 objects to "Curator" mode:

bb7612027t
bb63150884
bb59737890
bb4676849d
bb0274077s
bb4847631v
bb0308339k
bb35848216
bb56326201
bb2253754v
bb4642849m
bb00011743
bb8977358t

**Comment by lsitu** [comment]
@gamontoya Is this ticket ready?

**Comment by gamontoya** [comment]
@lsitu Not yet Longshou. I'm checking on something.

**Comment by gamontoya** [comment]
@GregReser Policy for SIO images. We don't ever delete, we change their status to curator mode.

**Comment by gamontoya** [comment]
@lsitu It's ready now, but note that this is not a deletion, but instead a status change.

**Comment by gamontoya** [comment]
@GregReser @lsitu Am I imagining, or are these all already curator only?

**Comment by GregReser** [comment]
@gamontoya yes, they are already curator only.  Laurel requested they be deleted.  If we can only set to curator, then I'll let her know and I will close this issue.

**Comment by gamontoya** [comment]
@GregReser Yes, let her know that she can discuss with Roger if needed.

**Comment by gamontoya** [comment]
#### Status: Will not fix (already curator only)
