### ISSUE TITLE
Remove / deaccession Heat and Automation CLR 

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#205]
### Descriptive summary

**Background:** The only object within the collection [Data From: Heat Automation and Transfer...](https://library.ucsd.edu/dc/collection/bb45080154) has been moved to be a member of the [CAICE](https://library.ucsd.edu/dc/collection/bb96275693) collection. The former was also put into curator-only mode. 

We are requesting the CLR also be deaccessioned (or removed) so that it no longer can be accessed or assumed to be an existing collection on production.   

### Related work

ucsdlib/dams-metadata#61

**Comment by gamontoya** [comment]
@jessicahilt Can you assign this to whomever has the bandwidth on your team?

**Comment by lsitu** [comment]
@jessicahilt I can work on it.

**Comment by gamontoya** [comment]
@lsitu Thank you!

**Comment by lsitu** [comment]
@gamontoya I think the collection [Data From: Heat Automation and Transfer...](https://library.ucsd.edu/dc/collection/bb45080154) is gone now.

**Comment by gamontoya** [comment]
@lsitu Yes, thank you!
