### ISSUE TITLE
Remove two components from Fresno and Fontana object

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#206]
### Descriptive summary

Researchers have requested that two components (plots) be removed from object, https://library.ucsd.edu/dc/object/bb70335495:

* Component 5 ("Coating Thickness")
* Component 9 ("Organonitrate")

### Rationale

Scope and Contents note will be added to object to explain need for removal.

### Related work

https://lib-jira.ucsd.edu:8443/browse/CPP-93

**Comment by hjsyoo** [comment]
@gamontoya This is a high priority ticket for RDCP.

**Comment by gamontoya** [comment]
@lsitu This one is ready. Feel free to start on it.

**Comment by lsitu** [comment]
@gamontoya Sure.

**Comment by lsitu** [comment]
@hjsyoo We may need to re-ingest all the files in components with index larger than 5.  Where can I find the original files for this object?

**Comment by hjsyoo** [comment]
@lsitu This is the file/component list, starting with component #2.

SummaryPlot_Timeseries_Number_Distribution.jpg | image-source |   |   | Aerosol Particle Number   Distributions
-- | -- | -- | -- | --
SummaryPlot_Timeseries_sizedistribution_Non-refractory_Fresno_Fontana.png | image-source |   |   | Non-Refractory Aerosol Mass   Distributions
SummaryPlot_Timeseries_BlackCarbon_Massdistribution.jpg | image-source |   |   | Black Carbon Mass Distribution
SummaryPlot_Timeseries_CoatingThickness_Fresno_Fontana.jpg | image-source |   |   | Coating Thickness
SummaryPlot_Timeseries_Non_refractory_Aerosol_Mass_Concentrations.jpg | image-source |   |   | Non-Refractory Aerosol Mass   Concentrations
SummaryPlot_Timeseries_Organic_Aerosol_Factors.jpg | image-source |   |   | Organic Aerosol Factors – Mass   Based
SummaryPlot_Timeseries_Organic_Aerosol_Factors_LS.jpg | image-source |   |   | Organic Aerosol Factors - Number   Based
SummaryPlot_Timeseries_Organonitrate.jpg | image-source |   |   | Organonitrate
SummaryPlot_Timeseries_Organosulfate.jpg | image-source |   |   | Organosulfate
SummaryPlot_Timeseries_Amines.jpg | image-source |   |   | Amines
SummaryPlot_Timeseries_FunctionalGroups.jpg | image-source |   |   | Organic Functional Groups
Fresno_Fontana_Processed.zip | data-service |   |   | Fresno Fontana Processed Data
fresno_raw.zip | data-service |   |   | Fresno Raw Data
fontana_raw.zip | data-service |   |   | Fontana Raw Data

The original files are in \rdcp-0093-fresno-fontana\Final_Files. Is this enough info?

**Comment by lsitu** [comment]
@hjsyoo Yes. Thanks. So file SummaryPlot_Timeseries_CoatingThickness_Fresno_Fontana.jpg (component 5) and fileSummaryPlot_Timeseries_Organonitrate.jpg (component 9) will be removed from the object, right?

**Comment by hjsyoo** [comment]
Correct!

**Comment by lsitu** [comment]
@hjsyoo I think the re-ingest of the giant .zip date files in object https://library.ucsd.edu/dc/object/bb70335495 is done late yesterday evening. Could you take a look? 
It looks like that the zoomify tiles creation was failed for component 5 and component 9, which may still have the stale tiles. I'll see how to fix them. Could you verify that zoom for other components are correct? Thanks.

**Comment by lsitu** [comment]
@hjsyoo The zoomify tiles for component 5 and component 9 are fixed now. Let me know if you see anything else. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Thanks - component 7 seems to have lost its proper title. Can you rename it to: "Organic Aerosol Factors - Number Based"

**Comment by lsitu** [comment]
@hjsyoo The title for component 7 is fixed now.

**Comment by hjsyoo** [comment]
@lsitu Looks great. Thanks!

**Comment by hjsyoo** [comment]
@remerjohnson Since lsitu had to reingest this object, your Scope and Contents note disappeared. Please redo the edit.

**Comment by lsitu** [comment]
@hjsyoo @remerjohnson Just to clarify what we've done here to delete component 5 and component 9. We restructured the components of this object and all files in components starting from index 5 were re-ingested. I think the descriptive metadata should be retained. So please double check before you make any metadata changes. Thanks.

**Comment by remerjohnson** [comment]
Not sure, but in any event, I think the scope and contents note looks good, @hjsyoo?

**Comment by hjsyoo** [comment]
@remerjohnson @lsitu Yes, I now see that it's back. I'm pretty sure the S&C note had disappeared after the restructuring, as topics began after the Description note. At any rate, I believe the files weren't technically removed until yesterday (2017-02-14), but since the note was first posted on 02-13, I'm not sure which date makes the most sense. Perhaps when the files were actually removed?
