### ISSUE TITLE
Collections report not reporting all data

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#207]
### Descriptive summary

The Collections Report for DAMS collections is not reporting out correctly for a few collections:

- Cinewest Archive **(missing size count)**
- Committee of Concerned Asian Scholars Friendship Delegations **(missing searchable items, items and size count)**
- Meet the Scientist Lecture Recordings **(missing size count)**
- William A. Joseph Collection **(missing size count)**

Not sure if a re-indexing of these collections will solve the issue. I'm attaching the Excel spreadsheet to this ticket for convenience.

- [collections_report-021318.xlsx](https://github.com/ucsdlib/damsmanager/files/1721578/collections_report-021318.xlsx)

**Comment by gamontoya** [comment]
@lsitu You might have to take this one too since you're the expert on the statistics reports.

**Comment by lsitu** [comment]
@gamontoya No problem.

**Comment by lsitu** [comment]
@gamontoya It looks like that the total disk size of some of the single object collections are much smaller than one megabyte that we are counting for in the report. In this case it'll be rounded to 0 (MB).
Do we need to change the counting rule to include the precisions with two digits after the decimal point? Or just make it 1 megabyte when the total disk size of a collection is less than 1 megabyte? We may need code changes and it won't take effect until we deploy damsmanager to prod in this case.

**Comment by gamontoya** [comment]
@lsitu For those smaller than 1 megabyte, yes. We need to make it show up as 1 versus 0. 

However, the collections I list above, I believe those are all larger than 1 megabyte. Can you confirm.

**Comment by lsitu** [comment]
@gamontoya Yes, some are much larger than 1MB and I've recaptured the counts for those collections that are failed during the new year day 2018. I think you can log in and download the latest collection status now: https://library.ucsd.edu/damsmanager/collectionsReport.do.
Please let me know if there's anything else is still missing. Thanks.

**Comment by gamontoya** [comment]
@lsitu Awesome. Let me know when you've updated DAMS Manager so that I can confirm that collections with size smaller than 1 kb show up as 1 and not 0.

Thanks Longshou!

**Comment by lsitu** [comment]
@gamontoya Sure. I think there could be three of those "Date from: " single object collections in rdcp will be affected with the changing of 0 to 1.
