### ISSUE TITLE
Create ARK list for SIO Geological Collection 

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#208]
### Descriptive summary

There are 126 **curator only** objects in the [SIO Geological Collection](https://library.ucsd.edu/dc/collection/bb2936476d). 

Please produce a report listing the ARKs to only these 126 objects.

### Rationale

Ho Jung does not believe that there should be **curator only** objects in this collection. This report will help us to investigate if the visibility of these 126 is an error.

**Comment by lsitu** [comment]
@gamontoya Attached is the ark list for those 126 curator objects in SIO Geological Collection:
[report_sio-geological-curators.txt](https://github.com/ucsdlib/damsmanager/files/1732579/report_sio-geological-curators.txt)

**Comment by gamontoya** [comment]
@lsitu Thank you. We're investigating why these objects are curator only.

**Comment by lsitu** [comment]
@gamontoya Diving into some of the objects, it looks like the rights holder and/or license elements are missing. For example https://library.ucsd.edu/dc/object/bb98649978.

**Comment by gamontoya** [comment]
@lsitu Good detective work!
