### ISSUE TITLE
SIO photos: remove ". Date Unknown." from title

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#210]
### Descriptive summary

For all the items in collection = bb20151229 (Scripps Institution of Oceanography Photographs), delete the text substring = ". Date Unknown." in metadata field = Title (mads:Title/mads:authoritativeLabel AND mads:MainTitleElement/mads:elementValue)

### Example
https://library.ucsd.edu/dc/object/bb55984893

### Current value
Frogfish (Antennarius). Date unknown.

### Expected value
Frogfish (Antennarius)

**Comment by VivianChu** [comment]
@GregReser @gamontoya - The Title field has been updated for all the items in this collection.  The solr index process for this collection has been run.  I'll let you know when the solr index process is done.

**Comment by VivianChu** [comment]
@GregReser @gamontoya - The index process is done.  
For example 
https://library.ucsd.edu/dc/object/bb24585316
https://library.ucsd.edu/dc/object/bb1468761m

**Comment by gamontoya** [comment]
@GregReser Please close this ticket if this work is approved.
