### ISSUE TITLE
UCSD Guardian: delete duplicate fields

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#211]
### Descriptive summary
Objects may contain duplicate Title, Date, and Note fields (same property, type, value) that should be removed.

for all the items in collection = bb4847930p (UCSD Guardian)
 - remove duplicate metadata field dams:title if the values are the same
 - remove duplicate metadata field dams:date if the type and value are the same
 - remove duplicate metadata field dams:note if the type and value are the same

### Example

https://library.ucsd.edu/dc/object/bb9659875t
![image](https://user-images.githubusercontent.com/5453716/37103854-13dfa7b0-21e0-11e8-868c-fdc0cdeaed6a.png)

![image](https://user-images.githubusercontent.com/5453716/37103532-551e9c64-21df-11e8-81f4-75b9248d8b8f.png)

**Comment by lsitu** [comment]
@GregReser I found that there are total 60 objects in UCSD Guardian that have the issue with one or more duplicate fields in dams:title, dams:date, dams:note. Attached is the report for those 60 objects:
[report-UCSDGuardian-duplicate-fields.txt](https://github.com/ucsdlib/damsmanager/files/1972501/report-UCSDGuardian-duplicate-fields.txt)

Do you see any objects that has the issue but missing from the report above? Thanks.

**Comment by GregReser** [comment]
@lsitu your search is probably the most accurate way to find the duplicates - there are too many objects for me to do a visual search.  

The best thing to do is fix the objects on your list and close this ticket.  If any more duplicates are discovered after that, we will open a new ticket an re-evaluate the search criteria.

**Comment by lsitu** [comment]
@GregReser Thanks. It sounds good and I'll move ahead to fix these objects.

**Comment by lsitu** [comment]
@GregReser I've corrected those 60 objects in the report that have duplicate fields. I think they are ready on prod for review now. Could you take a look? Thanks.

**Comment by GregReser** [comment]
@lsitu Well done, they look much better now.  Thanks.
