### ISSUE TITLE
Add Excel file to a DataMares Collection object

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#212]
### Descriptive summary

The (Excel) data that is associated with [an object in DataMares](https://library.ucsd.edu/dc/object/bb4438832x) is now out of embargo. Due to lack of embargo support, we had simply ingested an empty object. So we now need that data to be attached to the object.

### Location of file

+ rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_2_updated_2017-05-18/collection_update_dataMares_fisheries/f_ug_acoustics.xlsx

**Comment by remerjohnson** [comment]
Looping in @hjsyoo to this as well

**Comment by lsitu** [comment]
@gamontoya @remerjohnson I've ingested the Excel data file to the DataMares object and it's ready on prod for review now:
https://library.ucsd.edu/dc/object/bb4438832x.

**Comment by gamontoya** [comment]
@remerjohnson Please close if this issue is resolved.

**Comment by remerjohnson** [comment]
This looks great. Thanks Longshou!

**Comment by hjsyoo** [comment]
Thanks all! @remerjohnson There are a few more action items for this object, listed here: https://lisn.ucsd.edu/display/datacuration/Action+Items+-+dataMares.

**Comment by remerjohnson** [comment]
@hjsyoo Okay. I think those changes should be visible now. If you need more for this, let me know on Slack
