### ISSUE TITLE
Harold Scheffler Photographs: remove "." from end of title

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#213]
### Descriptive summary

For all the items in collection = bb08204951 (Harold Scheffler Photographs), remove the trailing period "." at the end of metadata field = Title (mads:Title/mads:authoritativeLabel AND mads:MainTitleElement/mads:elementValue)

### Example

https://library.ucsd.edu/dc/object/bb4676786b

### Current value

Aerial view from airplane.

### Expected value

Aerial view from airplane

**Comment by hweng** [comment]
@GregReser  All the items in collection = bb08204951 have been removed the trailing period from end of title. Would you take a look and let me know if it looks fine to you? Thank you!

**Comment by hweng** [comment]
@GregReser I checked several items and it looks good to me now: 
https://library.ucsd.edu/dc/object/bb4676786b
https://library.ucsd.edu/dc/object/bb4676787v
https://library.ucsd.edu/dc/object/bb44378750

**Comment by GregReser** [comment]
@hweng They look good.  Thank you.
