### ISSUE TITLE
Add CC-BY licenses to all objects in SIO Geological Collections

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#214]
### Descriptive summary

For all objects in the [SIO Geological Collections](https://library.ucsd.edu/dc/collection/bb2936476d), we need to add the Creative Commons Attribution (CC-BY) license. 

### XML value
To be added to the RDF/XML at object level:
```xml
<dams:license>
  <dams:License>
    <dams:licenseNote>Creative Commons Attribution 4.0 International Public License</dams:licenseNote>
    <dams:licenseURI>http://creativecommons.org/licenses/by/4.0/</dams:licenseURI>
    <dams:permission>
      <dams:Permission>
        <dams:type>display</dams:type>
      </dams:Permission>
    </dams:permission>
  </dams:License>
</dams:license>	
```

### Related work

ucsdlib/dams-metadata/issues/72

**Comment by hweng** [comment]
@remerjohnson, the Creative Commons Attribution (CC-BY) license has been added for all objects in the SIO Geological Collections.
For example: https://library.ucsd.edu/dc/object/bb2970735b
Let me know if it looks fine to you.

**Comment by remerjohnson** [comment]
@hweng Thanks Huawei! Looks good. Closing
