### ISSUE TITLE
Add newer CC license and a rights holder to Santa Fe Collection

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#216]
### Descriptive summary

The current Creative Commons license for the objects in the [Santa Fe Light Cone Collection](https://library.ucsd.edu/dc/collection/bb1673671n) needs updating from 3.0 to 4.0 

In addition, there is currently no Rights Holder, which should be added to all objects as "UC Regents". 

### Related work

ucsdlib/dams-metadata/issues/75

**Comment by hweng** [comment]
@remerjohnson I've updated RDF for copyright and license, see following example RDF, Let me know if it is correct?
http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb2322141x/transform?recursive=true&xsl=normalize.xsl

<dams:copyright>
<dams:Copyright rdf:about="http://library.ucsd.edu/ark:/20775/bb1639537b">
<dams:copyrightJurisdiction>us</dams:copyrightJurisdiction>
<dams:copyrightNote>
Constraint(s) on Use: This work is protected by the U.S. Copyright Law (Title 17, U.S.C.). Use of this work beyond that allowed by "fair use" requires written permission of the copyright holder(s). Responsibility for obtaining permissions and any use and distribution of this work rests exclusively with the user and not the UC San Diego Library. Inquiries can be made to the UC San Diego Library program having custody of the work.
</dams:copyrightNote>
<dams:copyrightPurposeNote>
Use: This work is available from the UC San Diego Library. This digital copy of the work is intended to support research, teaching, and private study.
</dams:copyrightPurposeNote>
<dams:copyrightStatus>Under copyright</dams:copyrightStatus>
<dams:rightsHolder>UC Regents</dams:rightsHolder>
</dams:Copyright>
</dams:copyright>

<dams:license>
<dams:License rdf:about="http://library.ucsd.edu/ark:/20775/bb7748899s">
<dams:licenseNote>Creative Commons Attribution 4.0 Unported License</dams:licenseNote>
<dams:licenseURI>http://creativecommons.org/licenses/by/4.0/</dams:licenseURI>
<dams:permission>
<dams:Permission>
<dams:type>adapt</dams:type>
</dams:Permission>
</dams:permission>
<dams:permission>
<dams:Permission>
<dams:type>copy</dams:type>
</dams:Permission>
</dams:permission>
<dams:permission>
<dams:Permission>
<dams:type>distribute</dams:type>
</dams:Permission>
</dams:permission>
<dams:permission>
<dams:Permission>
<dams:type>display</dams:type>
</dams:Permission>
</dams:permission>
<dams:permission>
<dams:Permission>
<dams:type>transmit</dams:type>
</dams:Permission>
</dams:permission>
</dams:License>
</dams:license>

**Comment by remerjohnson** [comment]
@hweng The copyright note looks correct. Thanks!

For the license, I don't believe I've ever seen a Permission besides "display", as I believe that's what is applied by default when we select a CC license at time of ingest. Interesting! This is what the default is: 

```xml
<dams:license>
  <dams:License>
    <dams:licenseNote>Creative Commons Attribution 4.0 International Public License</dams:licenseNote>
    <dams:licenseURI>http://creativecommons.org/licenses/by/4.0/</dams:licenseURI>
    <dams:permission>
      <dams:Permission>
        <dams:type>display</dams:type>
      </dams:Permission>
    </dams:permission>
  </dams:License>
</dams:license>
```

@gamontoya Do we need to evaluate the default CC license behavior in applying Permission values? I am not sure if this is an issue at all or not...

**Comment by gamontoya** [comment]
@remerjohnson @hweng I think it's a good idea to review the default CC behavior for 4.0 if different from 3.0. @hweng are they different?

**Comment by remerjohnson** [comment]
@gamontoya This is currently happening as the default for 4.0 as well: only the "display" permission is used

**Comment by GregReser** [comment]
Looking at that full list of RDF CC permissions above, it looks like a list of permissions allowed under CC - "you are allowed to adapt, distribute, ect."   We don't need to include those in our RDF since the user can, and should, get that information at the CC URL.  We use dams:permission display to drive object visibility in the DAMS and since all CC objects would be visible, it seems unnecessary to include it, unless it's required if dams:license is used (I don't think it is).

**Comment by gamontoya** [comment]
@hweng Do the answers from Ryan and Greg help? Can we just use _display_?

**Comment by hweng** [comment]
@gamontoya @GregReser @remerjohnson Thank you for looking into it. Just confirm with you, the `<dams:license>` should update to the following format, correct?

```
<dams:license>
  <dams:License>
    <dams:licenseNote>Creative Commons Attribution 4.0 International Public License</dams:licenseNote>
    <dams:licenseURI>http://creativecommons.org/licenses/by/4.0/</dams:licenseURI>
    <dams:permission>
      <dams:Permission>
        <dams:type>display</dams:type>
      </dams:Permission>
    </dams:permission>
  </dams:License>
</dams:license>	
```

**Comment by remerjohnson** [comment]
@hweng Yes, that would be consistent with our current values, so I think that's fine. Thanks

**Comment by hweng** [comment]
@remerjohnson No problem, I'll update them. Thanks for confirming!

**Comment by hweng** [comment]
@remerjohnson They were updated. Let me know if it looks all fine to you now: http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb2322141x/transform?recursive=true&xsl=normalize.xsl

**Comment by hweng** [comment]
@remerjohnson  The solr was updated for Rights Holder, and it shows on UI now, see the examples:
https://library.ucsd.edu/dc/object/bb0718029h
https://library.ucsd.edu/dc/object/bb8192501m
