### ISSUE TITLE
DAMS Excel Import allows invalid Begin/End date - object is not visible

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#217]
### Descriptive summary

Currently, pre-ingest and ingest validation does not validate Begin date and End date values.  For example, 2018-02-31 is invalid because February does not have 31 days.
In addition to the current ISO date format (YYYY-MM-DD) validation, date values should also be validated.

### Rationale

This is a problem because an object containing an invalid Begin or End date value is not visible in the DAMS public or curator view, meaning the object cannot be found and inspected.  It might be that SOLR cannot index the Object.  When a large collection is ingested and the final object count is short, it is very difficult (and very time consuming) to determine which objects are missing and where the error is so they can be edited.

### Expected behavior
pre-ingest and ingest fail and report is sent: "Invalid begin date 2018-02-31 in record 10001. Must be a valid calendar date."
Rules:
MM must be at least 01 and no greater than 12
DD must be at least 01 and no greater than the maximum days for the month expressed in MM (must account for leap years)

January <= 31 days
February <= 28 days, 29 in leap years
March <= 31 days
April <= 30 days
May <= 31 days
June <= 30 days
July <= 31 days
August <= 31 days
September <= 30 days
October <= 31 days
November <= 30 days
December <= 31 days

### Actual behavior
pre-ingest and ingest succeed and object is not found in the DAMS (public, curator, data view, rdf view)

### Examples

Invalid Begin date of 2018-02-31. Not visible in curator mode
http://librarytest.ucsd.edu/dc/object/bd34316619
http://librarytest.ucsd.edu/dc/object/bd34316619/data
http://librarytest.ucsd.edu/dc/object/bd34316619/rdf

Valid Begin date of 2018-02-28. Visible in curator mode
http://librarytest.ucsd.edu/dc/object/bd0155180z
http://librarytest.ucsd.edu/dc/object/bd0155180z/data
http://librarytest.ucsd.edu/dc/object/bd0155180z/rdf

**Comment by GregReser** [comment]
Here is a test ingest spreadsheet:
[invalid_dates.xlsx](https://github.com/ucsdlib/damsmanager/files/1812923/invalid_dates.xlsx)

**Comment by lsitu** [comment]
@mcritchlow I've created PR https://github.com/ucsdlib/damsmanager/pull/220 for Begin/End date validation support. It's ready for review now. Thanks.
