### ISSUE TITLE
RDCP object views do not get logged uniquely

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#219]
### Descriptive summary

Under both curator and non-curator mode, when users/curators visit the same object page multiple times in a given time period, each visit is logged as a separate view instead of one unique count for the visits. The DAMS manager does not track unique counts based on users/curators.

### Rationale

When users/curators visit the object page to view object contents, it is possible for them to open one object two or more times under different tabs of one browser to check different components of that object. It is also possible for them to click “back arrow” to navigate between objects. If one user/curator visits an object multiple times in a given amount of time, it would be efficient to merge those visits into one single unique view count, since unique views from different users/curators are what we are looking for to examine the general public’s interests in that object.

### Steps to reproduce the behavior

- Our Testing Procedure: (This testing is done through Chrome under UCSD IP.)

1. Log in to curator mode if doing the curator-mode testing.
2. Browse to the object page by searching its title.
3. First set of testings (“back arrow”): 
a. Click on the back arrow on the top left corner
b. Click on the object’s title to navigate back to the object page.
c. Repeat the procedures a-b multiple times.
7. Second set of testings (“having multiple tabs of the same object opened in the same window”):
a. Under the object page, move the cursor on top of the hyperlink under Label "Collection" and click on the hyperlink with right mouse button, then click on "Open link in a new tab".
b. Open the collection and go in to the same object file that was being browsed in the previous tab.
c. Without closing any tabs, click on the first tab of the object page.
d. Repeat procedure a-c.
12. Third set of testings (“having multiple windows opened for the same object”)
a. Under the object page, move the cursor on top of the hyperlink under Label "Collection" and click on the hyperlink with right mouse button, then click on "Open link in a new window".
b. Open the collection and go in to the same object file that was being browsed in the previous tab.
c. Without closing any windows, click on the first window of the object page that was opened.
d. Repeat procedure a-c.

- Testing Documentation:
-- Google Spreadsheet links. Unique Views Testing_current version: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1962572560
-- Under the thirteenth tab/sheet of the google spreadsheet (Unique Views Testing_current version), line 7 to line 65 records the data from testing under non-curator mode, line 68 to line 95 records the data from testing under curator mode.
-- Taking line 37 in the “Unique Views Testing_current version” sheet as an example, we went through the testing procedure under non-curator mode to view the objects under multiple tabs of the same window(browser). Since we viewed the same object as a unique user, we expected the view counts to be one for our multi-entries to the object page within a short amount of time instead of the number of clicks. Cell E37 (Expected Unique Views for object “Data from: Automation and Heat Transfer Characterization of Immersion Mode Spectroscopy for Analysis of Ice Nucleating Particles”) indicates that we would expect one unique view being logged under non-curator views. Cell F37 (Expected Views based on clicks for object “Data from: Automation and Heat Transfer Characterization of Immersion Mode Spectroscopy for Analysis of Ice Nucleating Particles”) indicates that we opened the object four times within a short amount of time. Cell G37 (Observed Views for object “Data from: Automation and Heat Transfer Characterization of Immersion Mode Spectroscopy for Analysis of Ice Nucleating Particles”) indicates that in the DAMs report, all of the clicks were counted toward non-curator views, and views were not registered uniquely based on users.
- Clarification on Spreadsheet’s Header
-- Expected Views (Unique): Expected view counts when the DAMS System counts views uniquely per user. 
-- Expected Views (based on clicks): The number of clicks(separate visits).
-- Observed Views: The data difference between two consecutive days’ view counts in CSV report. (Note: CSV report totals up the new view counts with the previous view counts for that month at midnight.)

### Related work

- RDCP object views from external points of entry do not get logged at all #225
- RDCP objects JPG views in curator mode get logged as non-curator views #218
- RDCP object views from external points of entry in curator mode get logged as non-curator views #226
- RDCP object views get logged inconsistently from session to session #227
- RDCP object views do not get logged uniquely #219

**Comment by lsitu** [comment]
@hjsyoo Yes, we haven't tracked any accesses basing on the users yet. With the library weblog that the current implementation basing on, I think we can only extract the user's IP address for this purpose. Does using the user's IP address to determine the unique counts of object access work for you?

**Comment by hjsyoo** [comment]
@lsitu Using the user's IP address (which will be static for each session that a user on campus is connected to wireless continuously, correct?) sounds like the best solution. But can we put this work on hold for now, while my student assistants finish their testing? We're working on specifying a third related ticket on RDCP stats, and it will be difficult for them if any of the reporting methods change during this period. They are coming back from the break today and tomorrow, so this could take a couple weeks. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Great! In that case, please feel free to proceed, unless you think our next ticket could affect how you approach the work. Regarding campus IP, I checked with Tim M, and I think you're right, one access per IP address every day would do a good job of capturing unique views.

**Comment by lsitu** [comment]
@hjsyoo It's good that we move ahead with the user's IP address  for counting the unique access. But I don't want to know what are your two other tickets related so that we all agree on what can do and what can't before moving forward with the implementation. I see your second ticket here: https://github.com/ucsdlib/damsmanager/issues/218. But what's your third ticket about?

**Comment by hjsyoo** [comment]
@lsitu Here are summaries of the third ticket:
- RDCP object views do not get logged when user clicks on URL link (from a google sheet) 
- RDCP curator views under curator mode get logged into non-curator mode, when entering via Google search or Calisphere link.
- RDCP object views do not get consistently logged when user clicks on DOI link from an external publication or website.

We're more thoroughly testing the last item, as the results have been inconsistent.

**Comment by lsitu** [comment]
@hjsyoo Regarding your [comment](https://github.com/ucsdlib/damsmanager/issues/219#issuecomment-378395162) above for the third ticket, with the library weblog that our current implementation is relying on, I don't think we can count any accesses from a public URL link (eg. from a google sheet) out side of our dams4 curator view as curator access. Should this be dams 5 feature, or we should look for other approaches to support it in dams 4?

**Comment by hjsyoo** [comment]
@lsitu Let's see what the students find when they link from DataCite and various publications (PDFs and websites). We are getting some logged hits when accessing from a Google search or Calisphere, so there's an inconsistency we don't quite understand.
We very much need access from external sources to work in D5, however we can get that data. I think it would be informative for us to troubleshoot what's going on in D4, even if we don't end up putting further development effort into D4.

**Comment by gamontoya** [comment]
Google Analytics does this right. It registers unique views.

**Comment by lsitu** [comment]
@gamontoya /@hjsyoo Should I restart my work on it with the approach of counting views basing on client IP addresses daily?

**Comment by lsitu** [comment]
Here is the article regarding how pageviews and unique pageviews are counted by google analytics:
https://support.google.com/analytics/answer/1257084?hl=en

**Comment by hjsyoo** [comment]
@lsitu Thanks for the link - that description matches with my understanding of pageviews and unique pageviews. I believe @gamontoya will be adding this ticket to one of the upcoming sprints, but to answer your question, yes, we would want to report unique pageviews based on daily visits from unique IP addresses.

**Comment by lsitu** [comment]
@mcritchlow I'v added PR https://github.com/ucsdlib/damsmanager/pull/230 to support unique views for RDCP object access and file downloads. It's ready for review now. Thanks.
