### ISSUE TITLE
Stats summary not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#221]
### Descriptive summary

- https://library.ucsd.edu/damsmanager/statsSummary.do?start=2010-03-01

Getting zero hits for collections, total items, and size.

![stats1](https://user-images.githubusercontent.com/4314914/38339696-78aabba8-3824-11e8-9024-6ef266193d8b.png)

### Probable Cause
_It's something new. It seems like we got the error when damsmanager was trying to insert the records to database._

### Notes

- Fix issue
- If possible, rebuild the stats for the missing months.

**Comment by lsitu** [comment]
@rstanonik /@jgorney I see the following error with DAMS Statistic while inserting records into  table stats_dlc_quan: InternalError: ERROR: value too long for type character varying(200).
I think we have longer collection titles that are over 200 characters. Could we update the collection_title column in table stats_dlc_quan to varchar(500)? Thanks.

I've updated it in QA and we just need to updated it in staging and prod as well. Here is the query I used for QA:
ALTER TABLE stats_dlc_quan ALTER COLUMN collection_title TYPE varchar(500);

**Comment by jgorney** [comment]
@lsitu - I've updated both prod and staging.  Please let me know if everything is ok.

Juliana

**Comment by lsitu** [comment]
@gamontoya Thank you very much. I'll run a test and let you know.

**Comment by gamontoya** [comment]
@lsitu Please run them also for all the missing months. Thank you.

**Comment by lsitu** [comment]
@gamontoya It works now and I've generated the stats for all the missing months. Thanks @jgorney.

**Comment by gamontoya** [comment]
Awesome! Thank you @lsitu and @jgorney !
