### ISSUE TITLE
Ed Fletcher Papers: edit geographic subjects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#222]
### Descriptive summary

155 objects in Ed Fletcher Papers portraying "Hodges, Lake (Calif.)" incorrectly include the geographic subject Escondido (Calif.) - it should be "San Diego (Calif.)"

### Task

FOR all the items in collection = Ed Fletcher Papers bb55647135
IF dams:geographic = Hodges, Lake (Calif.) bb60436951 AND Escondido (Calif.) bb99682178
REPLACE Escondido (Calif.) bb99682178 WITH San Diego (Calif.) bb13324509

### Expected results

Old:
Geographics
 - Hodges, Lake (Calif.)
 - Escondido (Calif.)

New:
Geographics
 - Hodges, Lake (Calif.)
 - San Diego (Calif.)

**Comment by GregReser** [comment]
@gamontoya any chance this can be added to the next sprint?

**Comment by GregReser** [comment]
Closing this because I made the edits by hand.

**Comment by gamontoya** [comment]
@GregReser Thanks Greg. I was out a handful of days last week and we haven't had a Sprint lately. Sorry about the delay, but I'm glad you were able to tackle this.
