### ISSUE TITLE
dataMares: object update/restructure needed

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#224]
### Descriptive summary

The data providers for the dataMares collection have sent us updated data. One of these is for this object: https://library.ucsd.edu/dc/object/bb3757060t 

It is currently a simple object: we have a new data file, so we'd like to make this into a complex object. 

The _current_ file in the DAMS will become **component 2**, while the _new_ file (located at `//rdcp-staging/rdcp-0041-dataMares/trackers_update/f_gc_trackers.xls`) will become **component 1**. 

Also, that existing file that will become component 2: the (component) title should be "Version 1, released July 2017". For the new file that will become component 1: the title should be "Version 2, released April 2018".

**Comment by lsitu** [comment]
@remerjohnson I think we may need to re-ingest the existing file with the restructuring of the dataMeMares object. Do you know where can I find the original source for the existing file that will become component 2: the (component) title should be "Version 1, released July 2017", or can we just use the one in the file store instead? Thanks.

**Comment by remerjohnson** [comment]
@lsitu I have put that file in `//rdcp-staging/rdcp-0041-dataMares/trackers_update/` as `f_gc_trackers_old.xls` to differentiate it from the other newer file there.

So, that will be: 
* `f_gc_trackers.xls` -> Component 1, titled "Version 2, released July 2018" 
* `f_gc_trackers_old.xls` -> Component 2, titled "Version 1, released July 2017" 

Thanks!

**Comment by lsitu** [comment]
@remerjohnson I've restructured the dataMares object and ingested the files. It's ready for review now, https://library.ucsd.edu/dc/object/bb3757060t. Thanks.

**Comment by remerjohnson** [comment]
@lsitu Thanks @lsitu, it looks great. Going to close this out
