### ISSUE TITLE
RDCP object views from external points of entry do not get logged at all

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#225]
### Descriptive summary

A) When we directly click on the object page’s URL in a Google Sheet to open an object, no views are registered in either curator mode or non-curator mode. No views are registered in incognito mode. We found that no views are registered by directly clicking on an object’s DOI (which redirects the page to its object page’s URL).

B) When we directly click on the object’s URL to open an object from an external link through a PDF, ACS Publication Site, and DataCite, no views are registered in either curator mode or non-curator mode.

### Rationale

Most research data is likely to be discovered by users via external links and search engines, rather than by browsing the DC. Our stats reports may be missing a significant portion of actual RDC collections usage, because page visits via direct URL clicks are not always logged. It can be seen in the Google Analytics section of each testing we do that the views counted by Google Analytics are not always being captured by DAMS. 

### Steps to reproduce the behavior for Description A

* Our Testing Procedure: (This testing is done through Chrome under UCSD IP.)

1. Open the object page by directly clicking on the URL, which has been saved on a google doc/sheet.
2. Stay on the object page for about 20-30 seconds and click components under that object to imitate the user's viewing behavior (The URL address is not changed/ The page is not redirected ).
3. Close tab.
4. In the same window, repeat step 1-3. 

* Testing Documentation:
-- Google Spreadsheet links: 
  --- Testing URL direct clicks: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1673736810.
  --- Testing DOI clicks: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=350903719
-- Under the fourth tab/sheet of the google spreadsheet (Testing URL direct links), line 8 to line 38 records the data from testing under non-curator mode, line 43 to line 57 records the data from testing under curator mode, line 63 to line 77 records the data from testing under incognito mode. Under the fifth tab/sheet of the google spreadsheet (Testing DOI clicks), it records the data from testing DOI direct clicks.
-- Taking line 14 in the “Testing URL direct links” sheet as an example, we went through the testing procedure under non-curator mode and opened the object via direct URL clicks for four times. Cell F14 indicates that we would expect four separate views being logged. Cell H14 indicates that in the DAMs report, none of those views were counted.

* Clarification on Spreadsheet’s Header
-- Expected Views: The number of times we click on the URL link. 
-- Observed Views: The data difference between two consecutive days’ view counts in CSV report. (Note: CSV report totals up the new view counts with the previous view counts for that month at midnight.)

### Steps to reproduce the behavior for Description B

* Our Testing Procedure: (This testing is done through Chrome under UCSD IP.)

1. Open the external publication through the link provided in the google document. 
2. Search for the url/doi by using CTRL + F and copy and pasting from the “Ctrl F in search bar” column. 
3. Click on the URL which will lead you to the object page.  
4. Stay on the object page for about 20-30 seconds and click components under that object to imitate the user's viewing behavior (The URL address is not changed/ The page is not redirected ).
5. Close tab.
6. In the same window, repeat step 1-5. 

* Testing Documentation:
-- Google Spreadsheet links: 
  --- Testing PDF links and ACS Publication (Under Link from Publications): https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1777166268 
  --- DataCite Testing: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1360095813 
-- Under the 15th tab/sheet of the google spreadsheet (Link from Publications), starting at line 45 we have recorded the data from testing under non-curator mode (green) and curator mode (pink). We have compiled both observed Curator and Non Curator views for each test we did. 
-- Under the 16th tab/sheet of the google spreadsheet (DataCite Testing), we have recorded the data from testing under non-curator mode (green) and curator mode (pink). We have compiled both observed Curator and Non Curator views for each test we did. 

* Clarification on Spreadsheet’s Header
-- Expected Views: The number of times we click on the URL link (2). 
-- Observed Views: No views are logged in
-- Google Analytics PageViews: The number of times people have viewed the object page.
-- Google Analytics Unique Views: The number of times a unique IP address has viewed the object page.

### Related work

- RDCP object views from external points of entry do not get logged at all #225
- RDCP objects JPG views in curator mode get logged as non-curator views #218
- RDCP object views from external points of entry in curator mode get logged as non-curator views #226
- RDCP object views get logged inconsistently from session to session #227
- RDCP object views do not get logged uniquely #219

**Comment by lsitu** [comment]
@mcritchlow I just added a PR https://github.com/ucsdlib/damsmanager/pull/232 to exclude those invalid client requests from counting in dams statistics, which is found during examining the tests data. It's ready for review now. Thanks.

**Comment by lsitu** [comment]
@hjsyoo I think the major issue with the external links that do not get logged is fixed in ticket #227 through PR https://github.com/ucsdlib/damsmanager/pull/228. And once we deploy damsmanager to prod, when you perform those tests again, you will see the counts logged for those external links.

However, while examining your tests and the data in the weblog, I see there could be a browser caching issue with those tests with multiple clicks on the same external link, in this case only those clicks that hit our server will be counted. I think this could be avoided if you clear the cache of the browser before doing any single test. Also, as I mentioned in the past, with the current implementation basing on weblog, we are not able to count on the external links for curator views.
Is there anything else that you want me to do for this ticket or not? Thanks.

**Comment by hjsyoo** [comment]
@lsitu Thank you, it's fine that those external links will log as non-curator views. I think the unique views issue has been resolved as well, so we won't expect multiple clicks to register from the same user in a single session. @xiw391 won't be back until July to resume testing, so we should be able to report back some time in August. When do you expect to deploy to prod?
