### ISSUE TITLE
RDCP object views from external points of entry in curator mode get logged as non-curator views

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#226]
### Descriptive summary

Under curator mode, when curators visit the RDCP objects through the external sources Google Search or Calisphere, the views are being logged in as non-curator views.

### Rationale

Curator views should be reported as curator views, not as non-curator views, regardless of point of entry by user.

### Steps to reproduce the behavior

* Our Testing Procedure: (This testing is done through Chrome under UCSD IP.)

1. Log in to curator mode if doing the curator-mode testing.
2. Open a new google search page and insert the keyword under the “Searched Keyword” column in “Google Search” spreadsheet.
3. Look through the search results and look for the one that points directly to the DC object page/ Calisphere object page.
4. Click into the link (Calisphere testing will take another step clicking from the Calisphere object page to the DC object page).
5. Stay on the object page for about 20-30 seconds and click components under that object to imitate the user's viewing behavior (The URL address is not changed/ The page is not redirected ).
6. Close the tab and repeat procedure 1-5.

* Testing Documentation:
-- Google Spreadsheet links: Google Search: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1510193304
-- Under the fourteenth tab/sheet of the google spreadsheet (Google Search), line 2 to line 218 records four sets of testings on the view counts under curator mode and non-curator mode. We did curator mode view testing and non-curator mode view testing simultaneously in the first two sets of testings, and separately in the last two sets of testings.
-- Taking line 51 in the “Google Search” sheet as an example, we went through the testing procedure under non-curator mode, searched for the object via Google, and opened the DC object page two times. Cell E51(Expected Views (Based on clicks)) indicates that we would expect two separate views being logged under non-curator views. Cell F51(Observed Views) indicates that in the DAMs report, four of non-curator views were counted. Cell G51 (Searched Keyword) indicates the search string we put in google search that will return the dc object link. Cell H51 (Search Page) indicates  the google search page after we put in the searched keyword in google search. 
-- Taking line 72 in the “Google Search” sheet as an example, we went through the testing procedure under curator mode, searched for the object via Google, and opened the DC object page two times. Cell E72(Expected Views (Based on clicks)) indicates that we would expect two separate views being logged under curator views. Cell F72(Observed Views) indicates that in the DAMs report, zero of curator views were counted. Cell G72 (Searched Keyword) indicates the search string we put in google search that will return the dc object link. Cell H72 (Search Page) indicates  the google search page after we putting the searched keyword in google search.

* Clarification on Spreadsheet’s Header
-- Expected Views: The number of times we go into the dc object page (click the URL link from Google search). 
-- Observed Views: The data difference between two consecutive days’ view counts in CSV report. (Note: CSV report totals up the new view counts with the previous view counts for that month at midnight.)

### Related work

- RDCP object views from external points of entry do not get logged at all #225
- RDCP objects JPG views in curator mode get logged as non-curator views #218
- RDCP object views from external points of entry in curator mode get logged as non-curator views #226
- RDCP object views get logged inconsistently from session to session #227
- RDCP object views do not get logged uniquely #219

**Comment by gamontoya** [comment]
@hjsyoo Is this moot/closeable?

**Comment by hjsyoo** [comment]
Katherine is still testing this. I think it would be fine to close it, and we can report any potential issues in a new ticket.
