### ISSUE TITLE
RDCP object views get logged inconsistently from session to session

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#227]
### Descriptive summary

When we click directly on the object’s URL to open an object from an external link at Plos, Wiley, Oxford Academics, or DPLA, both curator views and non-curator views can be registered as non-curator views. However, this pattern is inconsistent from session to session. Occasionally, no views get logged in at all despite Google Analytics reporting >0 views. Specifically, in 3 out of 7 test sessions between 2018-03-13 and 2018-04-18, non-curator views were properly reported. In the remainder of the sessions, 0 views were reported for non-curator. In 6 out of 7 test sessions between 2018-03-14 and 2018-04-19, curator views were reported as non-curator views, while in 1 session, curator views were reported as 0.

### Rationale

Curator and non-curator views from external points of entry should be consistently and properly reported regardless of the day on which testing is done.

### Steps to reproduce the behavior

* Our Testing Procedure: (This testing is done through Chrome under UCSD IP.)

1. Open the external publication through the link provided in the google document. 
2. Search for the url/doi by using CTRL + F and copy and pasting from the “Ctrl F in search bar” column. 
3. Click on the URL which will lead you to the object page.  
4. Stay on the object page for about 20-30 seconds and click components under that object to imitate the user's viewing behavior (The URL address is not changed/ The page is not redirected ).
5. Close tab.
6. In the same window, repeat step 1-5. 

* Testing Documentation:
-- Google Spreadsheet links: Link from Publications: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1777166268 
-- Under the 15th tab/sheet of the google spreadsheet (Link from Publications), starting at line 45 we have recorded the data from testing under non-curator mode (green) and curator mode (pink). We have compiled both observed Curator and Non Curator views for each test we did. 

* Clarification on Spreadsheet’s Header
-- Expected Views: The number of times we click on the URL link (2). 
-- Observed Views: Sometimes, non-curator views are being accurately logged in, curator views are logged in as non-curator. Sometimes, Non-curator views are showing up as 0s, aka no views.
-- Google Analytics PageViews: The number of times people have viewed the object page.
-- Google Analytics Unique Views: The number of times a unique IP address has viewed the object page.

### Related work

- RDCP object views from external points of entry do not get logged at all https://github.com/ucsdlib/damsmanager/issues/225
- RDCP objects JPG views in curator mode get logged as non-curator views https://github.com/ucsdlib/damsmanager/issues/218
- RDCP object views from external points of entry in curator mode get logged as non-curator views https://github.com/ucsdlib/damsmanager/issues/226
- RDCP object views get logged inconsistently from session to session https://github.com/ucsdlib/damsmanager/issues/227
- RDCP object views do not get logged uniquely https://github.com/ucsdlib/damsmanager/issues/219

**Comment by lsitu** [comment]
@hjsyoo One of the issue I see is that some of the external links may be redirected with a pattern like most of the search engines do, which has "-" as the referral url logged in the weblog. We ignore this pattern from counting in dams statistics at this time. I'll look for other ways to exclude those search engine /bot/spider accesses from counting, which could be tricky regarding accuracy.

**Comment by lsitu** [comment]
@gamontoya / @jessicahilt / @mcritchlow It looks like it's hard to make it accurate to exclude all search engines/crawlers from counting in dams statistics. And I think google analytics by default may not exclude those hits from search engines from counting in as well.

After exploring the information regarding search engines and looking into some of our data in the weblog, I am thinking about using the pattern of the browser's User Agent to determine whether an access to dams is from search engine/crawler or not. Here are the rules that we can start with:
1. Any accesses with "-" as the referral url, and the user agents that contains text like (bot | crawler | spider | robot | crawling), which is general syntax search engine user agents.
2. Exclude any known user agents that may not follow the above pattern. I found the following search engines/crawlers list are relative new, and there is a pattern field that we can utilize to find a match efficiently: https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json.
3. I see most of the the accesses from search engines are excluded once the above rules applied but with few exceptions. For example, [SortSiteCmd](https://www.distilnetworks.com/bot-directory/bot/sortsitecmd5-24-7780-0/), [Siteimprove.com](https://siteimprove.com/en-us/), [Dispatch](https://www.webmasterworld.com/search_engine_spiders/4781523.htm), [Disqus](https://www.webmasterworld.com/search_engine_spiders/4806437.htm) etc.
And I think we can exclude the hits with any specific user agents that we don't want to count in, for example, [GoogleImageProxy](https://serverfault.com/questions/581857/apache-logs-flooded-with-connections-via-ggpht-com-googleimageproxy?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). Do you agree to exclude all the examples above for now or not? It looks like we should count the hits from GoogleImageProxy. And I also see some hits with "-" as its user agents, which are from aws with cloud service like [QUALYS, Inc.](https://www.qualys.com/apps/web-app-scanning/).
4. When we found a peak in dams statistics, we could examine it again to exclude those search engines with different patterns from counting in again.

What do you think? Any suggests, thoughts etc?

**Comment by mcritchlow** [comment]
@lsitu - Sorry for the delayed response. That general approach seems very sensible to me. It would definitely be nice, at least for now if we can, to leverage the crawler list you noted. Managing this entirely ourselves seems like biting off a lot.. Perhaps we can integrate a cron task into the solution that periodically updates the list automatically or something so we don't have to babysit it.

I do have a question about (4). Is it possible filter statistics that are in the DB tables already? By that I mean, if we see a spike, would it be possible to add the offending bot/IP to a blacklist filter that then, presumably with an updated deploy of damsrepo, would not show those hits anymore in the statistics? So I guess it would be filtering/blacklisting in a different place. The former via the robots.txt method, the latter being sort of an acceptance that things like this are going to come through no matter how diligent we are (or if there are bots that simply ignore robots.txt), but we can still filter them out for reporting.

**Comment by lsitu** [comment]
@mcritchlow For question# 4, yes, we could make the changes to choose to filter statistics that are in the DB tables already but I am afraid that the query will be very slow, which could take us too long to wait for the result. 
Currently, the search engines filter is configurable, so we don't need to redeploy damsmanger but only need to update the configuration for the bot/crawler list to have those bots excluded from the statistics in the future. And we can correct that peak by running the statistics again for days after that peak to excluded that bot(s) from counting in dams statistics.
What do you think?

**Comment by mcritchlow** [comment]
Yeah that's a good point about query times. I wonder how different it would be in practice, but it's true that it would definitely slow down the reporting by some amount. I ask because I'm pretty sure that's what GA and Matomo do. It sounds like you already have a plan in place for regenerating statistics, which works as well. Perhaps that the path of least resistance (and additional work) for now :)

**Comment by lsitu** [comment]
@mcritchlow Then I'll create a PR with the current implementation for now, and we can change it later if we see a fit. Currently we store the stats data item by item daily and I see the queries are slow with aggregation. So I am afraid that any such filters with a list of search engine user agents will slow down the aggregation queries a lot. Maybe we could try doing filtering and aggregation at the client side to see how it goes if we want to try out that approach later?

**Comment by lsitu** [comment]
@mcritchlow I've created PR https://github.com/ucsdlib/damsmanager/pull/228 to exclude search engines /crawlers from counting in dams statistics. It's ready for review now. Thanks.
