### ISSUE TITLE
NAAMES: components not displaying in zoom viewer

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#229]
### Descriptive summary

In https://library.ucsd.edu/dc/object/bb0856963d, components 12 and 14 are not displaying in zoom viewer when components are clicked:
* https://library.ucsd.edu/dc/object/bb0856963d/zoom/12
* https://library.ucsd.edu/dc/object/bb0856963d/zoom/14

According to @remerjohnson , "Re: the component images, nothing stands out for the two .png files, besides the fact they seem to have different vertical/horizontal orientation and are much bigger in filesize than their other objects' counterparts. They both passed validation, but I don't think much validation occurs for images. We also tend to not ingest .png images as "source", so that could be a factor"

### Related work

https://lib-jira.ucsd.edu:8443/browse/DI-209

**Comment by gamontoya** [comment]
@lsitu Do you have time to create these tiles?

**Comment by lsitu** [comment]
@gamontoya Yes. I'll take a look.

**Comment by lsitu** [comment]
@gamontoya It looks like that the formats/mimetype of the source .png  for component 12 (`image/jpeg`) and the source .jpg file for component 14 (`application/octet-stream`) are not correct. I think this could be part of the reason that the tiles didn't get created for component 12 and 14, while the tiles for other components were created.
```
<dams:File rdf:about="http://library.ucsd.edu/ark:/20775/bb0856963d/12/1.png">
...
<dams:formatName>JPEG</dams:formatName>
<dams:mimeType>image/jpeg</dams:mimeType>
<dams:sourcePath>/pub/data2/dams/localStore/bb/08/56/96/3d</dams:sourcePath>
<dams:sourceFileName>
NAAMES-RUSSELL-SEMSNumberSizeDistribution_Atlantis_Summaryplot-APS-OPS-SEMS_R0.png
</dams:sourceFileName>
<dams:use>image-source</dams:use>
<dams:formatVersion>1.01</dams:formatVersion>
<dams:quality>4625x2308</dams:quality>
</dams:File>
```
```
<dams:File rdf:about="http://library.ucsd.edu/ark:/20775/bb0856963d/14/1.jpg">
<dams:mimeType>application/octet-stream</dams:mimeType>
<dams:crc32checksum>e85ec7b3</dams:crc32checksum>
<dams:formatName>bytestream</dams:formatName>
...
<dams:sourceFileName>
NAAMES-RUSSELL-SP2NumberSizeDistribution_Atlantis_Summaryplot_R0.jpg
</dams:sourceFileName>
<dams:sha1checksum>68c22d663bd920b47290a2db3ea46cd59deaf7df</dams:sha1checksum>
</dams:File>
```
Is it possible to correct the formats/mimetype of the .png (component 12) and the .jpg (component 14) and replace them?

**Comment by remerjohnson** [comment]
@lsitu That makes sense, Longshou. Should I do that and then attempt a file replace?

**Comment by lsitu** [comment]
@remerjohnson Yes. I think you can just go ahead with the File Replace tool in damsmanager to replace the master files. Thanks.

**Comment by remerjohnson** [comment]
@lsitu When I attempt the file replace, the tool complains: 
> File extensions for the ark file name and the selected source file are not matched.  

Which is what I need to do. The (hopefully) corrected images are in `//rdcp-staging/rdcp-0112-naames/file_replace/`

**Comment by lsitu** [comment]
@remerjohnson Yes, for File Replace, the file URI and the file extension need to be matched. For example, the values in File Replace form (https://librarytest.ucsd.edu/damsmanager/fileReplace.do) need to be as follows:
ARK File:       http://library.ucsd.edu/ark:/20775/bb0856963d/14/1.jpg
File location: /rdcp-staging/rdcp-0112-naames/file_replace/NAAMES-RUSSELL-SEMSNumberSizeDistribution_Atlantis_Summaryplot-APS-OPS-SEMS_R0.jpg

Would you like to give it another try or like me to do it? Thanks.

**Comment by lsitu** [comment]
@remerjohnson I've replaced the files for component 12 and 14. The tiles for these two components are created now.

**Comment by remerjohnson** [comment]
@lsitu Looks good. Thanks, Longshou! 

@hjsyoo If it looks good to you, I think you can close this out

**Comment by hjsyoo** [comment]
Looks great. Thanks @lsitu @remerjohnson !
