### ISSUE TITLE
Make 4 dataMares embargoed objects metadata-only

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#235]
### Descriptive summary

Although 4 dataMares objects were ingested with metadata-only overrides, the data is appearing publicly. 

These objects are under embargo, so need to be hidden from public view.

The objects are:
https://library.ucsd.edu/dc/object/bb3826323k (Note; this object has been deleted https://github.com/ucsdlib/damsmanager/issues/236)
https://library.ucsd.edu/dc/object/bb3519154g
https://library.ucsd.edu/dc/object/bb28365530
https://library.ucsd.edu/dc/object/bb7648882b

**Comment by hjsyoo** [comment]
@lsitu @gamontoya Please note that this is high priority ticket for RDCP. The data were not supposed to be publicly available at all, but they have been public for a week now.

**Comment by gamontoya** [comment]
@lsitu Can you take care of this asap? Thank you.

**Comment by lsitu** [comment]
@gamontoya Sure. I'll start to work on it.

**Comment by lsitu** [comment]
@gamontoya It seems like those four records above are all under copyright "UC regents". I think what we've implemented in the past for access overriding is just for those records that have a third party copyright status but not for those record with public copyright status and/or held by UC regents. So these records are public accessible without overriding by default. 
Do we want to change the access control rules to allow overriding any records for metadataDisplay, or just those hold by UC regents? Or do you just want to change the "UC regents" copyright holders for now?

**Comment by hjsyoo** [comment]
@remerjohnson Can these 4 objects be put back in Curator view until the issues are resolved?

**Comment by remerjohnson** [comment]
@hjsyoo I don't know how to do that on a per-object basis.

**Comment by hjsyoo** [comment]
@remerjohnson Ah, okay. 
@gamontoya @lsitu If I understand lsitu's question correctly, we should have access override capability for records held by UC Regents.

**Comment by lsitu** [comment]
@gamontoya @hjsyoo If we decide to change the access overriding for records held by UC Regents, we need to deploy damsrepo to prod. But the deployment of damsrepo is held by the UCSD IP/metadata-only feature at this time, which is still under review. Does the timeline works for you?

**Comment by remerjohnson** [comment]
@lsitu Is there a way to just for now, put those 4 objects into curator-only mode manually?

**Comment by hjsyoo** [comment]
@gamontoya @lsitu This sounds a lot more involved than I thought. As @remerjohnson asked, can we put these into curator only mode or delete the files from those 4 objects for now?

**Comment by lsitu** [comment]
There is another way that we can do is to create a temporal curator collection and move those four objects there, which make them under the review stage. We could release the collection back to dataMares collection once it's ready.

**Comment by hjsyoo** [comment]
@lsitu I favor the first option - remove UC Regents to make them metadata only. But any of those 3 options are viable to me. @remerjohnson Do you have a preference?

**Comment by remerjohnson** [comment]
@hjsyoo I favor the first option as well, @lsitu

**Comment by lsitu** [comment]
Okay. I'll remove the UC Regents copyrights holder then.

**Comment by hjsyoo** [comment]
@lsitu @gamontoya Thanks so much for your prompt attn to this.

**Comment by lsitu** [comment]
@gamontoya @hjsyoo @remerjohnson I think those four objects above in metadata-only view now. No public access to the files now and curator will have full access to the files.
However, the metadata-only viewer with anchor for files won't be available until we deploy the UCSD IP/metadata-only feature to prod.
Could you take a look?

**Comment by remerjohnson** [comment]
Yes, I've tried the 4 links while logged out, and the data are not accessible. Thanks @lsitu

**Comment by gamontoya** [comment]
@remerjohnson Does the bigger issues of overriding UC Regents need to be discussed by DOMM?

**Comment by remerjohnson** [comment]
@gamontoya good question. I'm not sure where it came from that UC Regents overrides an override of metadata-only. I think we can dig around for old documentation @GregReser ?

**Comment by mcritchlow** [comment]
That sounds like it was likely decided back when the data model we're using was originally created, it sounds kinda familiar. Clearly we would have been better off creating a completely separation between access state/visibility predicates and the (somewhat) related metadata. Probably impractical to fix in DAMS4 now, but I'm glad we will w/ DAMS5.

**Comment by lsitu** [comment]
@mcritchlow Yes, I think the case like visibility override in the collection level to make all objects (including those public and held by UC Regents objects) in a collection curator-only before the collection is released to public should be that decide back case. I recalled that at that time we discussed a lot with the capability to override objects held by a third party for public access but it seems like we've never touched the issue of overriding any single public object or UC Regents held object. I think that should be the gap.

**Comment by GregReser** [comment]
I can't find documentation about UC Regents overriding an override of metadata-only, but we probably assumed UC Regents would never need to be embargoed.

We have objects with UC Regents as rights holder and a cultural sensitivity override, so why can't metadata only work?
https://library.ucsd.edu/dc/object/bb1366376q

**Comment by remerjohnson** [comment]
@gamontoya It is mostly a use case for RDCP collections. The default owner is UC Regents, yet we allow for embargoes/metadata-only due to publisher/publishing issues. Is that correct, @hjsyoo? @arwenhutt

**Comment by hjsyoo** [comment]
Yes. @gamontoya, we have had a specific request for metadata pages in a collection to be made public, but for the data itself to be embargoed until future dates. Going forward, since the fix won't be applied to D4, we'll continue with the previous method of not ingesting those data files at all. As embargoes are released, @remerjohnson submits tickets to Dev requesting that the files be added to those objects.

**Comment by gamontoya** [comment]
@lsitu Shouldn't these four objects be hidden from a search? When I search bb3826323k (not logged in), I see this:

![curator](https://user-images.githubusercontent.com/4314914/43545105-cb7e5372-9589-11e8-8a47-66d0fdcc3314.png)

**Comment by lsitu** [comment]
@gamontoya I think these four dataMares objects are metadata-only, which will be searchable but no file access/download for public users.
However, the metadata-only viewer with placeholder anchor and the "Restricted View" label in the metadata section won't be available until we move the UCSD IP/metadata-only feature to prod. So I think that's why you still see the "Curator Only" label above, which will be corrected to "Restricted View" once metadata-only display feature is deployed.

**Comment by gamontoya** [comment]
@lsitu Great, something more to test :-)

**Comment by hjsyoo** [comment]
@remerjohnson @gamontoya Today, we had a new release for the DAMS. The 3 metadata-only objects that were ingested with their files (see Description above) now display this message: 
Not Found
The page you were looking for does not exist.
Home · Contact Us
Response Status Code 404

I think this is a new behavior. We used to see the landing page (metadata), but not the file. Is this your recollection?

**Comment by lsitu** [comment]
@hjsyoo / @remerjohnson I found those three records (exception bb3826323k) was edited with the a timestamp like `2018-08-17T08:43:46+0000`, and I see a weird element `<dams:visibility>curator</dams:visibility>` was added to each object. For example, http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb7648882b. It seems like these items were changed to curator display last month but not related the the dams deployment today.

Do you want to change it back to metadata-only display?

**Comment by gamontoya** [comment]
@hjsyoo @remerjohnson Can you wait until I confirm with Longshou that this collection has been re-indexed?

**Comment by gamontoya** [comment]
@hjsyoo @remerjohnson Confirming it's been re-indexed. Do you want Longshou to set back to metadata only?

**Comment by remerjohnson** [comment]
@hjsyoo @lsitu 
> I found those three records (exception bb3826323k) was edited with the a timestamp like 2018-08-17T08:43:46+0000, and I see a weird element <dams:visibility>curator</dams:visibility> was added to each object. For example, http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb7648882b. It seems like these items were changed to curator display last month but not related the the dams deployment today.
> Do you want to change it back to metadata-only display?

Yes, this editing occurred on August 17... I was out on vacation and we had an urgent embargo request come in for several objects, which must have included these 3 objects. 

@hjsyoo Would putting these back as metadata-only be okay? I was unsure if the dataMares team wanted any metadata for these emergency embargo objects.

**Comment by hjsyoo** [comment]
@gamontoya @remerjohnson @lsitu Apologies - Ryan is right. These 3 objects (the only metadata-only embargoed objects in this collection that have files ingested) were included in the list of 8 objects that the depositors requested be embargoed immediately on Aug 17. I hadn't made that connection previously, but it's in my documentation now. Thanks everyone, we're done with this work so I'll close the ticket.
