### ISSUE TITLE
Delete dataMares object

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#236]
### Descriptive summary

This metadata only object was accidentally ingested: https://library.ucsd.edu/dc/object/bb3826323k
Please remove completely from the DAMS, as it is a duplicate of a pre-existing object.

Link to related tickets or prior related work here.
https://lib-jira.ucsd.edu:8443/browse/DI-213 - dataMares Collection-batch3
https://github.com/ucsdlib/damsmanager/issues/235 - Make 4 dataMares embargoed objects metadata-only #235

**Comment by gamontoya** [comment]
@jessicahilt This can be assigned.

**Comment by lsitu** [comment]
@gamontoya I think object https://library.ucsd.edu/dc/object/bb5463148r is gone now.

**Comment by lsitu** [comment]
@gamontoya /@hjsyoo I've deleted object https://library.ucsd.edu/dc/object/bb3826323k and I think it's gone now.

**Comment by hjsyoo** [comment]
Confirming I can't find it using a search on its title. Thanks @lsitu !
