### ISSUE TITLE
Add Excel file to DataMares Collection object

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#239]
### Descriptive summary

The Excel data that is associated with the [bb5258779d object](https://library.ucsd.edu/dc/object/bb5258779d) in DataMares is now out of embargo. Due to lack of embargo support, we had simply ingested an empty object. So we now need that data to be attached to the object.

### Location of file

+ //rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_2_updated_2017-05-18/collection_update_dataMares_fisheries/f_ug_acoustics_corvina_length.xlsx

### Related work 
ucsdlib/dams-metadata/issues/84
#212

**Comment by hjsyoo** [comment]
@gamontoya Do we have an ETA on this work? I was hoping we'd get this up relatively quickly, but @remerjohnson and I are both out of office from tomorrow until Aug 20. It might be best to put this on hold until then, as Ryan will need to apply some metadata edits in conjunction with data release.

**Comment by gamontoya** [comment]
@hjsyoo There is no ETA as we have not a Sprint. However, if you push tickets out and expect them to be worked on immediately, it would be nice if you somehow added some label for High Priority (we not all mind readers :-))

**Comment by gamontoya** [comment]
@hjsyoo This is currently on hold. Once you and Ryan are back, let me know if you'd like to proceed.

**Comment by hjsyoo** [comment]
@gamontoya I'm back, and we should be fine to proceed. The researchers asked on Friday for an emergency embargo on some existing objects, but this wasn't one of them.

**Comment by remerjohnson** [comment]
@gamontoya 
> it would be nice if you somehow added some label for High Priority (we are not all mind readers :-))  

I don't see a priority type of label available for issues. How would you like us to denote priority?

**Comment by gamontoya** [comment]
@remerjohnson How about create a new label?

**Comment by lsitu** [comment]
I've added the file to object https://library.ucsd.edu/dc/object/bb5258779d and it's ready for review now.

**Comment by remerjohnson** [comment]
Thanks Longshou, looks good. @hjsyoo Feel free to close this out if it looks good to you.

**Comment by hjsyoo** [comment]
Thanks all, looks good.
