### ISSUE TITLE
Delete Baja postcard object

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#240]
### Descriptive summary

This is a duplicate object, please delete at the request of Special Collections:
https://library.ucsd.edu/dc/object/bb5463148r

**Comment by gamontoya** [comment]
@jessicahilt This is a quickie and can be assigned.

**Comment by lsitu** [comment]
@gamontoya @jessicahilt I will work on it shortly.

**Comment by lsitu** [comment]
@gamontoya I think object https://library.ucsd.edu/dc/object/bb5463148r is gone now.

**Comment by GregReser** [comment]
Looks like it's gone to me, thanks
