### ISSUE TITLE
Update `Restricted - cultural sensitivity` access override

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#243]
### Descriptive summary

DAMS Manager currently has the `Restricted - cultural sensitivity` access override which isn't behaving as expected. Update DAMS Manager to make it become metadata-only with a cultural sensitivity note.

### Expected output

1. Make this note internal (curator only)
`<dams:Note>
<dams:type>note</dams:type>
<rdf:value>Image not available due to cultural sensitivities of the community 
depicted.</rdf:value>
</dams:Note>
</dams:note>`

2. Display the "Restricted View" banner -- Behave as metadata-only object
` <dams:restriction>
<dams:Restriction>
<dams:type>display</dams:type>
</dams:Restriction>
</dams:restriction>
<dams:permission>
<dams:Permission>
<dams:type>metadataDisplay</dams:type>
</dams:Permission>
</dams:permission>`

3. Example:

https://library.ucsd.edu/dc/object/bb9011283p/rdf

* Note that the above object may still retain the embargo date.

**Comment by lsitu** [comment]
@gamontoya Currently the access control rule is implemented to restrict those objects with License restriction and embargo date from curator only access. So for object https://library.ucsd.edu/dc/object/bb9011283p, if we need to retain the embargo date with the restriction license, we won't get the `Restricted View` at all.
Do you want to change the access control rule to allow metadata-only display for any embargoed objects?

**Comment by gamontoya** [comment]
@lsitu Yes, we need to support metadata-only (restricted view) if a person selects metadata-only AND also adds a restriction license/embargo.

**Comment by gamontoya** [comment]
@lsitu @VivianChu Also, if a person only selects restriction license/embargo and NO metadata-only, then it will remain locked down to curator only.

**Comment by lsitu** [comment]
@gamontoya Could we say that if an object with a third party license (except those public objects and UC Regents hold objects) has OtherRights=metadataDisplay, then the object will be overridden as metadata-only and it will be displayed with a `Restricted View` banner?

**Comment by gamontoya** [comment]
@lsitu Yes, absolutely!

**Comment by lsitu** [comment]
@gamontoya I've added PR https://github.com/ucsdlib/damsmanager/pull/244 to change the note for `Restricted - cultural sensitivity` and make it internal-only. I think access control and damspas UI display should be working as expected with the new note above on staging and QA now. Please let me know if you see anything else that still need change. Thanks.

**Comment by lsitu** [comment]
@mcritchlow I think PR https://github.com/ucsdlib/damsmanager/pull/244 is ready for review now. Thanks. 
Should we make a new release for damsmanager once it's merged so that @gamontoya can test it since it's related to the metadata-only display feature?

**Comment by mcritchlow** [comment]
@lsitu - Yes, in fact could we use this as an opportunity to move dams manager to using the `master` plus release tags? I noted that still hasn't happened.

**Comment by lsitu** [comment]
@mcritchlow Yes. I think we can start with it now. Once we merge the latest two commits to master, we can simply delete the develop branch.

**Comment by gamontoya** [comment]
@lsitu Thank you. I'll test it now on QA.
