### ISSUE TITLE
Update `Restricted - cultural sensitivity` access override to allow for license restriction

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#246]
### Descriptive summary

Currently, when setting an object to `Restricted - cultural sensitivity` although a license restriction is set, DAMS Manager is ignoring it. The RDF output is:

`<dams:otherRights>
<dams:OtherRights>
<dams:restriction>
<dams:Restriction>
<dams:type>display</dams:type>
</dams:Restriction>
</dams:restriction>
<dams:permission>
<dams:Permission>
<dams:type>metadataDisplay</dams:type>
</dams:Permission>
</dams:permission>
<dams:otherRightsBasis>cultural sensitivity</dams:otherRightsBasis>
</dams:OtherRights>
</dams:otherRights>`

### Expected output

`<dams:license>
<dams:License>
<dams:restriction>
<dams:Restriction>
<dams:endDate>2059-01-01</dams:endDate>
<dams:beginDate>2009-01-01</dams:beginDate>
<dams:type>display</dams:type>
</dams:Restriction>
</dams:restriction>
<dams:permission>
<dams:Permission>
<dams:type>display</dams:type>
</dams:Permission>
</dams:permission>
<dams:licenseNote>Display currently prohibited.</dams:licenseNote>
</dams:License>
</dams:license>`

### Expected display behavior

`Restricted - cultural sensitivity` + `metadataDsiplay` access overridden until end of license date. "Restricted View" label will display to public and campus users.

### Related 

#243 
#244

**Comment by lsitu** [comment]
@gamontoya For the behavior of `access overridden until end of license date` in `Restricted - cultural sensitivity + metadataDsiplay`, do you expect an automatic releasing of the embargoed object for public view, or manual release the it like what we did in the past for ETD after the embargoed object is reviewed? It seem like currently those embargoed objects in DAMS4 could have around 50 years of embargoed period that we don't have to worry about though ...

**Comment by gamontoya** [comment]
@lsitu No, let's not do that because I'm hoping that our new system will auto-release and will be in place before 2059 :-)

**Comment by lsitu** [comment]
@mcritchlow I've added license with the embargoed date for the access overridden option with `Restricted - cultural sensitivity` in PR https://github.com/ucsdlib/damsmanager/pull/247. It's ready for review now. Thanks.
