### ISSUE TITLE
Allow license to be added to metadata-only override

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#248]
### Descriptive summary

As a rights holder, I want to be able to add license restrictions to my dataset and have it set to metadata-only visbility as well.

### Rationale

RDCP collections currently need and expect this combination.

### Expected behavior

Public and campus users will see the "Restricted View" banner and the metadata. The object will be accessible **ONLY** to curators.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/249 for it. It's ready for review now. Thanks.

**Comment by gamontoya** [comment]
@lsitu Is this working on stage and QA?

**Comment by lsitu** [comment]
@gamontoya Yes. I think you can test it on staging and QA now.
