### ISSUE TITLE
Resolve encoding/display errors on 3 Catalhoyuk Digipres staging objects

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#250]
### Descriptive summary

Despite a successful test ingest log ([damslog-2099381761.txt](https://github.com/ucsdlib/damsmanager/files/2336843/damslog-2099381761.txt)) of 13 objects, only 10 objects are visible in the [Catalhoyuk Digipres Test Collection](https://librarytest.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Data+from%3A+Spatial+Analysis+and+Heritage+Conservation%3A+Leveraging+3-D+Data+and+GIS+for+Monitoring+and+Assessing+%C3%87atalh%C3%B6y%C3%BCk+Earthen+Architecture&id=bd2615124z&sort=title_ssi+asc).  

@lsitu reported that: 
> I found there is an encoding issue with the special character `ETX`. There is an error `com.hp.hpl.jena.shared.CannotEncodeCharacterException: cannot encode (char)  ETX in context XML` while retrieving the RDF XML.

The source OLR metadata:
[OLR_catalhoyuk_digital_preservation.xlsx](https://github.com/ucsdlib/damsmanager/files/2336855/OLR_catalhoyuk_digital_preservation.xlsx)

### Expected behavior
All 13 objects should appear

### Actual behavior
Only 10 objects appear

I am labeling this high priority as per @hjsyoo discussions. Thanks

**Comment by hjsyoo** [comment]
By any chance, would saving the XLSX file as CSV, then saving again as XLSX remove all encoded characters? We would then need to replace all instances of Catalhoyuk with the properly MS-formatted version of the word. Not that this would address the cause of the original problem, but is this even a possible quick fix?

**Comment by remerjohnson** [comment]
@lsitu Ah, that's great Longshou. I found some suspect line breaks, but that wasn't the real issue, and couldn't find other suspects. I can see how a slash like that would not be kosher in Excel. I'll try that fix and report back if that resolves the issue. 

I could see this happening again if someone were putting Windows-style file paths in for some reason, but I don't anticipate that realistically. But, it may be good to ignore such characters going forward. What do you think @hjsyoo @mcritchlow

**Comment by hjsyoo** [comment]
Thanks for catching that so quickly, @lsitu. I tentatively agree with Ryan that ignoring the chars going forward might be best. It's hard to anticipate every data file coming in, but ignoring sounds safer than replacing.

**Comment by mcritchlow** [comment]
Nice catch @lsitu! I'm not as familiar with the Jena parsing library as Longshou is, but I agree that ideally we would ignore or otherwise escape characters that can't be encoded.

**Comment by remerjohnson** [comment]
Going to close this ticket out for now since it's been resolved. Do we need another ticket for ignoring invalid characters like these? @lsitu @mcritchlow

**Comment by lsitu** [comment]
@remerjohnson I am fine with either way, work on this ticket or open a new one. Thanks.

**Comment by lsitu** [comment]
@remerjohnson Will you open a new ticket for handling those control characters, or reopen this ticket for me to work on? Thanks.
