### ISSUE TITLE
Ignore or escape control characters upon metadata validation

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#251]
### Descriptive summary

When the metadata source contains a control character (example "[end-of-text](https://www.fileformat.info/info/unicode/char/0003/index.htm)" as '`\3`'), the metadata passes the RDF/XML validation in the report, yet fails on the server side with an error such as: 
`com.hp.hpl.jena.shared.CannotEncodeCharacterException: cannot encode (char)  ETX in context XML` 

### Rationale

It can take a long time to examine which characters are special and will cause these errors, so it'd be great if the system can highlight or even ignore these characters

### Expected behavior
System will ignore or escape the control characters, and/or report the error to a metadata analyst via the RDF/XML validation reports

### Actual behavior
The system raises no error in reports, but silently fails and does not show the object. Example: https://librarytest.ucsd.edu/dc/object/bd9611798m 

### Related work

#250

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/252 for it. It's ready for review now. Thanks.

**Comment by lsitu** [comment]
@remerjohnson I reopen the ticket as the result of our discussion this Tuesday for the control characters like `LINE FEED (LF)` that you expect to have, and the values in multiple columns could be merged together.
Could you give me a list of control characters that you don't want to ignore?

**Comment by remerjohnson** [comment]
@lsitu the only ones I can think of right now are Line Feed and possibly Carriage Return.  It's crucial that we have support for as you say:
> the values in multiple columns could be merged together. 

Do you think that's being affected by Line Feed, or something else?

**Comment by lsitu** [comment]
@remerjohnson It could be but I need to dive deeper into it since I have the codes for automatic test with multiple values and it passes.

**Comment by lsitu** [comment]
@remerjohnson Are you seeing the issue that header `Identifier:identifier` with multiple fields are merged together on staging?

I created more automatic tests with multiple values that include control character [Line Feed] and I don't see the problem. So I think this is not related to the control characters handling here.

And I tested it with the Excel that you provided, I see there are two columns `Related resource:related` and it is handled correctly with two RelatedResource elements. So I think header `Identifier:identifier` is assumed to be single value and it's implemented this way from the very beginning! It seems like it's a different thing that we may not want to mix it with this ticket. 

Do you think creating another ticket for this support is better or not? I can just create another PR for it if you update the ticket for this support. Thanks.

**Comment by remerjohnson** [comment]
@lsitu Thanks for looking into that Longshou. I thought that might be the case. So in the future, if I simply separated multiple values with the `|` character for `Identifier:identifier`, would it render properly? 

I can test this and get back to you if you'd prefer...

**Comment by lsitu** [comment]
@remerjohnson I think we can support multiple values for header `Identifier:identifier`, either separated by | character or with multiple `Identifier:identifier` columns.

**Comment by remerjohnson** [comment]
@lsitu Oh, great. Will that have to be a new ticket or not?

**Comment by lsitu** [comment]
@mcritchlow / @remerjohnson I've created PR https://github.com/ucsdlib/damsmanager/pull/257 to keep Line Feed (LF) and Carriage Return (CR) control characters. 
@remerjohnson I'll work on another PR to enable support for header `Identifier:identifier` with multiple values. Would you like me to work on this ticket or create a new ticket for it?

**Comment by lsitu** [comment]
@remerjohnson I can just work on this ticket if you update the description text above. It seems like a new ticket for this support might be clearer but it's not a must.

**Comment by remerjohnson** [comment]
@lsitu It seems it would be better to keep track of if you created a new ticket for that, since it's fairly unrelated

**Comment by lsitu** [comment]
@remerjohnson I agree. Though the change is straight forward. I've created ticket https://github.com/ucsdlib/damsmanager/issues/258 for it.

**Comment by remerjohnson** [comment]
@gamontoya Yup! I will make some tests for this today. Thanks

**Comment by remerjohnson** [comment]
@gamontoya @lsitu This object's Excel source had the line feed character, as well as multiple `Identifier:identifier` fields (and one that had a `|` character to delimit within the cell): 
https://librarytest.ucsd.edu/dc/object/bd2478683d 

Everything seems to be rendering correctly.
