### ISSUE TITLE
Add banner to DAMS Manager (staging environment)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#254]
### Descriptive summary

Please add a "staging" banner to the DAMS Manager `staging environment` to help users note that they in the right environment (staging and not production).

### Rationale

Oftentimes I catch myself doing a "test" ingest in the production environment. It would help if I saw the staging banner as a clue that I'm in the right place.

**Comment by gamontoya** [comment]
@jessicahilt This is ready for assignment.

**Comment by lsitu** [comment]
@jessicahilt @gamontoya Sure. I'll find a way to add the "staging" banner to damsmanager for the staging environment.

**Comment by lsitu** [comment]
@gamontoya \ @mcritchlow I've created PR https://github.com/ucsdlib/damsmanager/pull/256 to add the banner/ribbon to staging environment (see screenshot above). It's ready for review now. Thanks.

**Comment by lsitu** [comment]
<img width="1439" alt="screen shot 2018-09-21 at 4 03 16 pm" src="https://user-images.githubusercontent.com/2430784/45909773-ce71d980-bdb8-11e8-8c28-4629382044e0.png">

**Comment by gamontoya** [comment]
@lsitu Looks great!

**Comment by gamontoya** [comment]
@lsitu Can you assign the PR review to another dev since Matt is out?

**Comment by gamontoya** [comment]
@gamontoya Confirming that this is working on staging.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damsmanager](https://github.com/ucsdlib/damsmanager/issues/261)
