### ISSUE TITLE
Support 9 digit bibs for MARC/MODS Import

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#255]
### Descriptive summary
Per Matt Petters @mdpeters,
```
I'm getting a java.lang.NullPointerException trying to export the Roger record for the peptide video to csv in production, it looks like JollyRoger is checking if the bib number length is greater than 8 and truncating it if it is... unfortunately we now have some records with 9 digit bibs

and the peptide video is one of them
```

### Rationale

DAMS Manager will produce error java.lang.NullPointerException when export csv for bib records with 9 digits. This is caused by JollyRoger fails to retrieve the bibs is more than 8 digits. For example, http://roger.ucsd.edu/record=b10409153~S6.

**Comment by lsitu** [comment]
@mcritchlow I've added JollyRoger PR https://github.com/ucsdlib/jollyroger/pull/3 for it. Thanks.

**Comment by gamontoya** [comment]
@mdpeters Can you confirm this is working on staging?
