### ISSUE TITLE
Add multiple values support for header Identifier:identifier

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#258]
### Descriptive summary
Add support for header Identifier:identifier with multiple columns or delimited by | character for multiple values.

### Rationale 
Currently, DAMS Manager assumes header `Identifier:identifier` to be single value and will merge multiple `Identifier:identifier` columns together into a single identifier note. While in object https://library.ucsd.edu/dc/object/bb0515927k, it has multiple values for the identifier note. We need to separate them. 

### Expected behavior
Multiple columns of `Identifier:identifier` should be separated with multiple Identifier notes. 

### Actual behavior
Multiple `Identifier:identifier` columns is merge together into a single Identifier note delimited by | character.

### Related work
#251

**Comment by lsitu** [comment]
@mcritchlow / @remerjohnson I've added PR https://github.com/ucsdlib/damsmanager/pull/259 for the support.

**Comment by gamontoya** [comment]
@remerjohnson or @GregReser This ticket needs confirmation that this is working on staging.

**Comment by gamontoya** [comment]
@remerjohnson Can you confirm this one is working as expected?

**Comment by remerjohnson** [comment]
@gamontoya Yup! Confirmed this as working on staging
