### ISSUE TITLE
Add banner to DAMS Manager (QA environment)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#261]
### Descriptive summary

Please add a "quality assurance" banner to the DAMS Manager `QA environment` to help users note that they in the correct environment. Spell out "quality assurance" instead of QA.

### Rationale
It is helpful for users of DAMS Manager to know what working environment they are in.

**Comment by gamontoya** [comment]
@lsitu Maybe a yellow banner for QA?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll make it happen on QA as well.

**Comment by lsitu** [comment]
@mcritchlow I've created PR https://github.com/ucsdlib/damsmanager/pull/267 to add banner/ribbon to all environments except production, including QA. Thanks.
