### ISSUE TITLE
R&D: Collections reporting tool

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#262]
### Descriptive summary

Investigate feasibility of creating a tool that dynamically generates a report to denote if a collection:

1. is newly released
2. has had objects added
3. has had objects removed
4. has had metadata edits to 1 or more objects

- Two event types that may already be recorded are `record created` and `record edited` (which don't really = `released`). Per Arwen, we might need to add a new event to what's recorded. If so, what is the recommendation for No. 1?

- What about the current process that edits the extent value in the collection level record when it's released? Does it leave a distinct footprint (agent or event:detail?). Can this be used to calculate Nos. 2-3?

- `record edited` for No. 4?

### Rationale

At the beginning of each month, Gabriela harvests new collections, and re-harvests collections that have had updates (objects added, removed, metadata edits) to Calisphere -> DPLA. Folks in DOMM report this information to Gabriela in a Slack channel, but there should be a way to query for this automatically/dynamically generate a report.

**Comment by gamontoya** [comment]
@jessicahilt This is ready for R&D/assignment.

**Comment by lsitu** [comment]
@jessicahilt / @gamontoya Sure. I'll look into this potential support.

**Comment by lsitu** [comment]
@mcritchlow / @gamontoya I've added damsrepo PR https://github.com/ucsdlib/damsrepo/pull/70 and damsmanager PR https://github.com/ucsdlib/damsmanager/pull/283 for Collection Report. Both PRs are ready for review now. Thanks. 
Here is the screenshots for begin date selection and the report page (CSV exportable):
<img width="1046" alt="screen shot 2018-11-08 at 10 38 12 am" src="https://user-images.githubusercontent.com/2430784/48234931-90347780-e370-11e8-8a3b-331c5e273e91.png">
<img width="1061" alt="screen shot 2018-11-08 at 10 38 44 am" src="https://user-images.githubusercontent.com/2430784/48234936-962a5880-e370-11e8-8dfd-0be47c4fc508.png">

**Comment by gamontoya** [comment]
@lsitu Very nice work. Shouldn't we have an `end date` option too?

**Comment by lsitu** [comment]
@gamontoya I think we can compare the date range with SPARQL for the `end date` option. And we can see what's the performance looks like.

**Comment by lsitu** [comment]
@mcritchlow I was just thinking about adding the optional `End date` field as @gamontoya suggested. So if leaving the `End date` field empty, then it's the `start date` up until now. If specify any end date values, then it's a date range for searching. This could slow down the query a little bit but I think it should be fine:

<img width="1063" alt="screen shot 2018-11-09 at 11 32 43 am" src="https://user-images.githubusercontent.com/2430784/48286923-04782500-e41c-11e8-91f3-2f8adaad02bd.png">

**Comment by gamontoya** [comment]
@lsitu Yes, that's exactly what I expected to see.

**Comment by lsitu** [comment]
@mcritchlow / @gamontoya I've added commit https://github.com/ucsdlib/damsmanager/commit/98e26878cc60f03fabc5e4f3cd6e4df3bb708dc1 for the `end time` option above. It's ready for review now. Thanks.
