### ISSUE TITLE
Batch edit 

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#263]
### Descriptive summary
DOMM would like to be able to make batch edits.  We're flexible about the details.

### Rationale
We frequently need to edit multiple records, our most frequent use cases are:
1. replacing, adding, or removing variable fields/values
2. replacing, adding, removing constant fields/values (which can include changing collection membership)

Currently such edits need to either be made on an item by item basis or by submitting a request to ITD.  DOMM having batch edit capabilities would save time for both units, as well as reduce overhead in managing requests/tickets and errors which naturally may arise from information passing through longer communication chains.

**Comment by jessicahilt** [comment]
This is huge and has a lot of ambiguity that we'll need to sort out.

**Comment by jessicahilt** [comment]
This conversation can probably start now to get what is wanted/expected first.

**Comment by arwenhutt** [comment]
@jessicahilt Yeah, the request was intentionally vague, we wanted to communicate that we're flexible : )

There are lots of different ways this could be done, but maybe help get the conversation started, here are two ideas that represent the two ends of the LOE/functionality spectrum:
1) on the lowest end would be allowing us to edit/upload multiple RDF records at once using the same process as we currently use for RDF edits.  This would allow us to use find and replace (mostly) to more easily replace/add/remove data which is constant across multiple records.  Probably the most common/relevant use case for this would be moving a subset of items from a single collection, into a new collection by changing the collection membership metadata.)  

2) on the high end would be the ability to export records in an "ingest" template format, perform edits and then re-import (or overlay) them.  This would allow us to do much more complex batch clean-up and would be very valuable.

**Comment by arwenhutt** [comment]
Oh, and I want to ping @GregReser that this conversation may be starting up.  He's done a lot of work/thinking about these things both locally and as part of the Hyrax Batch Ingest WG.

**Comment by gamontoya** [comment]
@GregReser Going along with what we discussed and saw demo'd in the Hyrax Batch Import/Exprt WG, can you come up with a `spec` that aligns with that for our currently DAMS workflow?

**Comment by gamontoya** [comment]
@arwenhutt Sounds good. But a spec is what we're shooting for, for sure.

**Comment by lsitu** [comment]
@arwenhutt / @GregReser Is the spec ready for me to work on? Thanks.

**Comment by GregReser** [comment]
@lsitu The batch edit spec is ready https://docs.google.com/document/d/17e921jvvjhFXJA_y1VaDyi9Qmsg_ZNYv4UFSyxACQDM/edit?usp=sharing

The input for the edit tool will be an Excel file based on the output from the batch metadata export spec https://github.com/ucsdlib/damsmanager/pull/302

Many of the functions in the edit spec are similar to the current Excel ingest and CLR Edit tools, though some new features (linked headings) and columns (collection, rights) have been added.

If there are functions in the edit spec that would require a very high LOE that might block development, let us know and we can re-evaluate them.

**Comment by arwenhutt** [comment]
Per discussion in DAMS-WG 3/5 we're going to try breaking up the work into smaller chunks and link them via an epic or binder ticket.  I'm going to close this ticket as I think it has served the purpose of initial discussion and getting the ball rolling on how we can approach this high level goal

Next steps will be tracked in the **Batch edit functionality (epic) #309** ticket
