### ISSUE TITLE
Compromised Tokens

### ISSUE THREAD

**Issue by jhriv** [ucsdlib/damsmanager#274]
### Descriptive summary

Configuration files with access tokens were inadvertently committed to the repository. Those files have been obliterated from history. The tokens still require changed.

### Rationale

Plain text access tokens were committed - anyone could have cloned and now have access.

**Comment by gamontoya** [comment]
@jessicahilt @lsitu Can this ticket be closed?

**Comment by lsitu** [comment]
@gamontoya I don't know about the context of this ticket. Maybe @mcritchlow know more about and we can wait until he's back? Thanks.

**Comment by mcritchlow** [comment]
@lsitu @gamontoya - I checked with John and he can't recall any specifics about this. He did remember that at some point the situation he described did happen. But the details are lost to history/memory. I propose that we close this out at this point.
