### ISSUE TITLE
MARC to CSV Mapping: map 510 to Note:bibliography

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#276]
### Descriptive summary
For the MARC Import Tool, conversion to CSV, the 510 tag is incorrectly exporting to Title Variant

### Request
Change the 510 export to Note:bibliography

- Place multiple 510 in separate Note:bibliography columns
- Include all 510 fields with any indicator
- Include all subfields
  - Replace each subfield with a space, e.g., "Rocq|c7897" = "Rocq 7897"

**Comment by gamontoya** [comment]
@lsitu You'll probably have to work on this in the next Sprint since you'll be out on vacation.

**Comment by lsitu** [comment]
@gamontoya Sure. Thanks.

**Comment by lsitu** [comment]
@GregReser Do you have an example that I can use for test? Thanks.

**Comment by GregReser** [comment]
@lsitu b7209364

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/jollyroger/pull/5 to JollyRoger for the conversion. It's ready for review now. Thanks.
