### ISSUE TITLE
Find way to pull in orphan objects into collection statistics 

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#279]
### Descriptive summary

There are currently some objects in the DAMS that are not attached to a collection record. These objects are not being counted in our collections statistics. For example:

- https://library.ucsd.edu/dc/search?_=1540424124377&f%5Bobject_type_sim%5D%5B%5D=video&f%5Bsubject_series_sim%5D%5B%5D=East+Asia+Film+Collection.+Underground+films%2FIndependent+films

- https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=scarare

- https://library.ucsd.edu/dc/object/bb3246040b

The first set is found using a "series" facet and the second set is retrieved using a local note `scarare`. For the third, there is nothing aiding in retrieval.

### Task
Recommend a way to pull together these counts into our statistics. Must consider too what repo they belong to.

### Consider
It could be a search for the absence of a collection reference, rather than the presence of a hook.

**Comment by lsitu** [comment]
@gamontoya Do you mean to include those orphans in the [collections report (quantity )](https://library.ucsd.edu/damsmanager/collectionsReport.do) spreadsheet and group them by unit `Library Digital Collections` and `UCSD Research Data Collections`?

**Comment by gamontoya** [comment]
@lsitu Yes. The hook(s) could be the collection name, like scarare-orphans and series-orphans.

**Comment by lsitu** [comment]
@gamontoya There will be some gaps there since there are no collections these orphans belong to. May be we need some customs rules if we want to give a set of orphans a name?

**Comment by gamontoya** [comment]
@lsitu That's the thing Longshou. They do not want these orphans collections to be given a collection name. Since this is R&D sort of work, can you think of another suggestion? 

What if we just did something like:

![001](https://user-images.githubusercontent.com/4314914/51351089-c1ab7c80-1a5e-11e9-9ff2-662065fc31ce.png)

**Comment by lsitu** [comment]
@gamontoya Yeah, That sounds good! And all orphans are grouped by units (dlp and rdcp).

**Comment by gamontoya** [comment]
Oh, well that's a nice surprise. Okay, then just change the collection title to be _Library Digital Collections Orphans_ and _Research Data Collections Orphans_ (yes, get rid of the preceding _UCSD_.

Thank you.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/303 fro the title change that @gamontoya suggested. It's ready for review now. Thanks.
