### ISSUE TITLE
RDCP download counts are inaccurately reported

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#280]
### Descriptive summary and Steps to Reproduce Behavior

DAMS manager (DM) reports download counts inaccurately and inconsistently for RDCP components. Four tests have been run so far during different intervals in September and October, all on Chrome while on the UCSD domain:

1. 2018-09-04:
* In non-curator mode, tester searched the DC or browsed to object, then downloaded a selected component once. 
* DM reported 1 download, correctly.
* Documentation: https://docs.google.com/spreadsheets/d/1Q19_pP9l_5B6KVBhztpeMSW3Clm4gdoz09bnFg6OiuM/edit#gid=272013537 (rows 181-271)

2. 2018-09-12 and 2018-09-17: 
* In non-curator mode, tester entered the object URL in the address bar, then downloaded a selected component once. Tester repeated this procedure on a separate computer. 
* DM consistently reported 4 downloads rather than the expected 2. 
* Documentation: https://docs.google.com/spreadsheets/d/1Q19_pP9l_5B6KVBhztpeMSW3Clm4gdoz09bnFg6OiuM/edit#gid=272013537 (rows 292-326)

3. 2018-10-23: 
* In non-curator mode, tester cleared the cache, entered the object URL in the address bar, then downloaded a selected component once. Testers repeated this procedure on 2 additional computers. 
* DM consistently reported a suspiciously high number of downloads for the day (i.e., downloads were incremented by anywhere from 6 to 30 for the tested components, rather than the expected 3). 
* Documentation: https://docs.google.com/spreadsheets/d/1lR2ZaGQLUgwInN-ff6RfmP6WgdLX-OdgKTX92PgdaVA/edit#gid=0 (rows 2-17)

4. 2018-10-24: 
* In non-curator mode, tester cleared the cache, searched the ARK in Google, clicked on the search result to get to the correct object, then downloaded a selected component once. Testers repeated this procedure on 3 additional computers. 
* DM consistently reported negative downloads for the day (i.e., the cumulative download count for each component tested was far less than the cumulative count reported on the previous day). 
* Documentation: https://docs.google.com/spreadsheets/d/1lR2ZaGQLUgwInN-ff6RfmP6WgdLX-OdgKTX92PgdaVA/edit#gid=0 (rows 19-34, but tests are ongoing)

**Comment by lsitu** [comment]
@hjsyoo I can't access any of the google share spreadsheets above. Could you give me the access to those four spreadsheets above so that I can take a look? Thanks.

**Comment by hjsyoo** [comment]
@lsitu I gave you access to the sheets just now. I tried to give you access to the entire folder in which we're doing our work, but for some reason Google isn't letting me.

**Comment by lsitu** [comment]
@hjsyoo Can you repeat those negative results and those high volume download tests? It seems like something may be going wrong with the test. For example, in test `3. 2018-10-23:` https://docs.google.com/spreadsheets/d/1lR2ZaGQLUgwInN-ff6RfmP6WgdLX-OdgKTX92PgdaVA/edit#gid=0, I see item bb0549894r in row#51 for component `3-D render of all superimposed buildings in the sequence` has 32 downloads, while I only see 31 counts today:
<img width="1440" alt="screen shot 2018-10-31 at 2 05 33 pm" src="https://user-images.githubusercontent.com/2430784/47819735-9f844700-dd18-11e8-862a-3b0586e634c0.png">

Here are what I am wondering:
1. Was the downloads counts for the same component? I see three components for item bb0549894r.
2. Was the result compared with the `Unique View` or `Page View`? 
3. Recently we regenerated the stats starting from July, will it affect you test or not?
So I think it's be helpful if you can repeat those tests with unexpected downloads and attached the screenshots if you see something odd. Thanks. 

Just let me know if it's too much for repeating these tests and I can see whether there are other ways that can prove the correctness of the unexpected results that you observed.

**Comment by hjsyoo** [comment]
@lsitu Those roller-coaster counts are exactly the problem we're seeing. They seem to alternate between high positive increments on one day, followed by highly negative increments the next day. I don't really believe these components are seeing that much activity in one day. I took screenshots of the download reports for 10/23 to 10/25:
![downloads_2018-10-23_3drender](https://user-images.githubusercontent.com/10660549/47821029-89788580-dd1c-11e8-9b5b-98425371fe5a.PNG)
![downloads_2018-10-24_3drender](https://user-images.githubusercontent.com/10660549/47821032-8d0c0c80-dd1c-11e8-9c99-2de40ca40f1a.PNG)
![downloads_2018-10-25_3drender](https://user-images.githubusercontent.com/10660549/47821035-8f6e6680-dd1c-11e8-8b79-cbbbe42f075c.PNG)

**Comment by lsitu** [comment]
@hjsyoo Do you still seeing the same behavior now?

**Comment by hjsyoo** [comment]
@lsitu Actually, we didn't look at any of the *unique download* stats reports. We are primarily concerned about the component *download* stats reports behaving oddly. The object views aren't quite correct, either (they frequently show one more view than was actually performed), but we wanted to address the roller coaster download reports here first. @anrastog , can you paste for us the exact link you used to obtain the download stats (screenshots above), so we're all on the same page?

**Comment by anrastog** [comment]
Yes. Our main focus was to look at the download stats by component and we used the RDCP File Download by month: 
https://library.ucsd.edu/damsmanager/statsRdcpDownload.do?unique

We did also note down our views and unique views as well, but more for context. 
https://library.ucsd.edu/damsmanager/statsRdcpDownload.do (for views)
https://library.ucsd.edu/damsmanager/statsRdcpDownload.do?unique (for unique views)

![screenshot 3](https://user-images.githubusercontent.com/27264283/47869040-18d87400-ddc3-11e8-9974-5887382a0dd9.png)

**Comment by hjsyoo** [comment]
@lsitu Hang on, Anushka and I are troubleshooting some link issues on our end.

**Comment by lsitu** [comment]
@hjsyoo / @anrastog Sorry I meant the unique component downloads (https://library.ucsd.edu/damsmanager/statsRdcpDownload.do?unique) and all download (https://library.ucsd.edu/damsmanager/statsRdcpDownload.do). If you look at the title of the table on the left, you will see `Views
RDCP Downloads by Month (Unique Views)` for unique downloads. I could disable the other view if that confuses you guys.

**Comment by hjsyoo** [comment]
@lsitu You're right, it looks like there may be some confusion on our end regarding whether we're consistently downloading total or unique stats. We'll do another round of tests next week and make sure we've bookmarked the correct pages rather than navigating from https://library.ucsd.edu/damsmanager/statsRdcpUsage.do.

Can you verify that these URLs are correct?
• For (total) downloads: https://library.ucsd.edu/damsmanager/statsRdcpDownload.do
• For unique downloads: https://library.ucsd.edu/damsmanager/statsRdcpDownload.do?start=2017-12-01&unique
• For (total) views: https://library.ucsd.edu/damsmanager/statsRdcpUsage.do
• For unique views: https://library.ucsd.edu/damsmanager/statsRdcpUsage.do?start=2017-12-01&unique

**Comment by hjsyoo** [comment]
@lsitu One helpful fix might be to label the CSV exports differently. We always export the CSV to harvest stats, but I believe total and unique downloads, for example, both get named "rdcp_downloads" by default. Would it be an easy fix to have unique downloads get named "rdcp_unique_downloads", and unique views to be named "rdcp_unique_views"?

**Comment by lsitu** [comment]
@hjsyoo Yes. The above links are correct. And I think we can update the file name for CSV download to "rdcp_unique_downloads.csv" and "rdcp_unique_views.csv".

**Comment by lsitu** [comment]
@mcritchlow Per discussion with @hjsyoo above, I just added PR https://github.com/ucsdlib/damsmanager/pull/281 to rename the CSV export filename for unique views/file downloads. It's ready for review now. Thanks.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damsmanager](https://github.com/ucsdlib/damsmanager/issues/284)
