### ISSUE TITLE
RDCP download counts are inaccurately reported

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#284]
### Descriptive summary and Steps to Reproduce Behavior
DAMS manager (DM) reports download counts inaccurately and inconsistently for RDCP components. Four tests were run on separate days, all on Chrome while on the UCSD domain. All testers shared this behavior:
* Clear cache and sign out of DAMS (non-curator mode)
* Search for a designated object's ARK in Google. Click on the object URL in search results.
* Find the designated component on the page and download the object once.
* Repeat for all objects on the test list, on a separate computer. (The number of tests performed per object varied by day.)

Documentation: https://docs.google.com/spreadsheets/d/1lR2ZaGQLUgwInN-ff6RfmP6WgdLX-OdgKTX92PgdaVA/edit#gid=1826356290

1. 2018-11-05: 5 downloads were performed. DM reported 4 downloads and 4 views.
2. 2018-11-06: 2 downloads were performed. DM reported 0 downloads and 0 views.
3. 2018-11-07: 4 downloads were performed. DM reported 0 downloads and 0 views.
4. 2018-11-08: 1 downloads were performed. DM reported 0 downloads and 0 views.

**Comment by anrastog** [comment]
Also, when I looked at the testing we conducted two weeks ago, I added the downloads over a two day period. We had downloaded an object 7 times over the span of 2 days, but it showed up on the DAMS stats as 6 downloads.

**Comment by lsitu** [comment]
@hjsyoo Thanks for performing the tests. I think we may have to compare what's in the library weblog and the database for the period that you performed the tests to see what's going wrong.
@jgorney Is it possible to export the records in stats_file_download table for period from 2018-11-05 to 2018-11-08 (join table web_stats and stats_file_download)? Thanks.

**Comment by jgorney** [comment]
Sorry, I didn't see this.  I will do it right now.

**Comment by jgorney** [comment]
@lsitu , this is in production, correct?

**Comment by lsitu** [comment]
@jgorney Yes, it's prod. Thanks.

**Comment by jgorney** [comment]
@lsitu Do you want all fields from table stats_file_download for that period, or just select columns (like file_id, etc) ?  I assume the join between the two tables is columns stats_file_download.stat_id = web_stats.id? Just making sure I get the right data.

**Comment by lsitu** [comment]
@jgorney Yes, I need all the fields from table stats_file_download and web_stats (WHERE stats_file_download.stat_id = web_stats.id) for that period.

**Comment by jgorney** [comment]
Hopefully this is what you want - let me know.  You will note that there are two "client_ip" columns - this field occurs in both tables.  The first "client_id" column is from web_stats, the second is from stats_file_download:

[DAMS_webstats.xlsx](https://github.com/ucsdlib/damsmanager/files/2784121/DAMS_webstats.xlsx)

**Comment by lsitu** [comment]
@hjsyoo I found the problem that prevents it from counting the RDCP downloads with a direct URL, which is caused by the last implementation for request IP filtering support. And I've added a PR to fix it. Thank you very much for catching that.
@mcritchlow The PR https://github.com/ucsdlib/damsmanager/pull/305 is ready for review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu @gamontoya Is this issue ready for my review?

**Comment by lsitu** [comment]
@gamontoya /@hjsyoo I think we can release a new version of damsmanager with the fix for RDCP stats at any time. But it carries the codes for CIL Harvest processing which may need to review at the same time. Do you want to release damsmanager with these changes now?

**Comment by gamontoya** [comment]
@lsitu No. We will wait for the CIL Harvest work to be completed.

**Comment by hjsyoo** [comment]
@gamontoya Was this download count fix ever deployed? I'm hoping my student assistant will be able to resume testing this summer.

**Comment by lsitu** [comment]
@hjsyoo / @gamontoya Yes, it's deployed there on prod for some time already.

**Comment by hjsyoo** [comment]
@lsitu Do you recall the date the fix was deployed?

**Comment by lsitu** [comment]
@hjsyoo I think it was deployed April 9th. See https://github.com/ucsdlib/damsmanager/issues/314.
