### ISSUE TITLE
Add files to dataMares objects

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#288]
### Descriptive summary

Several dataMares objects without files need new files added. I'm attaching a spreadsheet of the object URIs and the files that need to be added. Let me know if more information is needed.

[dataMares_object_list.xlsx](https://github.com/ucsdlib/damsmanager/files/2621471/dataMares_object_list.xlsx)

### Rationale

Before we had 'metadata-only' functionality, a kludge solution for embargoes was to have a curator-only object without a file ingested, but these objects should have files so that they can have the correct functionality. Now that the dataMares team has edited the files to strip out sensitive data, those files can be added to objects.

### Related work

#239 
ucsdlib/dams-metadata/issues/105

**Comment by lsitu** [comment]
@gamontoya Is the ticket ready for the sprint?

**Comment by gamontoya** [comment]
@lsitu Yes. Feel free to take it.

**Comment by lsitu** [comment]
@remerjohnson I think all 22 file in the excel file dataMares_object_list.xlsx above are ingested and available for review now. Thanks.

**Comment by remerjohnson** [comment]
@lsitu I checked and they all seem good. What do you think @hjsyoo?

**Comment by hjsyoo** [comment]
@remerjohnson @lsitu Confirmed! Closing the ticket as they all look good.
