### ISSUE TITLE
CIL Harvesting - Download source JSON metadata files and retrieve master source files from Github

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#297]
### Descriptive summary
This task is to download JSON metadata files from Github https://github.com/slash-segmentation/CIL_Public_Data_JSON, convert to CSV format (OLR ingest file), and retrieve source files for CIL Harvest. The JSON files, OLR ingest file, and the master source files need to store in the location as required in https://docs.google.com/document/d/1Eg2024XATxuwdzFtoLTNujalK2SDR_s6-Sg6zyUC9wE/edit#. Thanks @mcritchlow for R&D and the codes https://gist.github.com/mcritchlow/f133e8bacd32a7d9daaa4b74af4cbcab that can utilize for this support.  

### Rationale
In CIL Harvesting, DAMS Manager will traverse the source JSON metadata location location in `/rdcp-staging/rdcp-0126-cil/cil_harvest_[YYYY-MM-DD]/metadata_source`
 to retrieve the new JSON files added and covert them to CSV format with Excel headings for review and ingest.

### Related work
#289, #291, #292

**Comment by lsitu** [comment]
@mcritchlow Would you mind setup your codes in https://gist.github.com/mcritchlow/f133e8bacd32a7d9daaa4b74af4cbcab as a UCSD Github repository that can be used for this support? Thanks.

**Comment by mcritchlow** [comment]
@lsitu - I'm happy to help with this if I can. From the gist, what would you like to see in the new github repo? What would be most helpful as a starting point? Would you like the `cil_download` and `git_changes` files there so you can iterate on those?

**Comment by lsitu** [comment]
@mcritchlow Thanks. Yeah, I think we need the `cil_download` and `git_changes` files. And we may need `cil_csv.rb` as well since @arwenhutt mentioned it in section 4.b.i.1 that we may need to store the csv format source files  there.

**Comment by mcritchlow** [comment]
@lsitu - Ok sounds good, i'll create an initial repo with those files and then let you assess next steps from there.

**Comment by mcritchlow** [comment]
@lsitu - here's the initial repo https://github.com/ucsdlib/cil-sync

**Comment by lsitu** [comment]
@mcritchlow That's great! Thanks.

**Comment by lsitu** [comment]
@rstanonik As suggested by @arwenhutt in [CIL Ongoing Harvesting Process](https://docs.google.com/document/d/1Eg2024XATxuwdzFtoLTNujalK2SDR_s6-Sg6zyUC9wE/edit#), I think we may need write access to rdcp-staging with the following paths:
/rdcp-staging/rdcp-0126-cil/cil_harvest_[YYYY-MM-DD]/metadata_source
/rdcp-staging/rdcp-0126-cil/cil_harvest_[YYYY-MM-DD]/metadata_processed

Is it possible to write to run the script in https://github.com/ucsdlib/cil-sync/blob/master/git_changes.sh to download the files and write to the directories above in rdcp-staging? And damsmanager (the tomcat user) may need to access the downloaded source files to perform the actually CIL Harvesting process, which need to write to `/rdcp-staging/rdcp-0126-cil/cil_harvest_[YYYY-MM-DD]/metadata_processed` as well. Thanks.

**Comment by lsitu** [comment]
@rstanonik Do you think is possible to download and store all those files for CIL harvesting  to rdcp-staging or not? Thanks.

**Comment by rstanonik** [comment]
Yes, I'm sure it can be run.  I ran it and it didn't do anything.

**Comment by lsitu** [comment]
@rstanonik Thanks. I am working on it now and will let you know once it's ready. I think if the tomcat user and the process running the script (https://github.com/ucsdlib/cil-sync/blob/master/git_changes.sh) can have write access to /pub/data2/damsmanager/dams_staging/rdcp-staging/rdcp-0126-cil on rdcp-staging will help.

**Comment by lsitu** [comment]
@mcritchlow / @rstanonik I've added PR https://github.com/ucsdlib/cil-sync/pull/1 for the support. Thanks.

**Comment by lsitu** [comment]
@rstanonik / @mcritchlow Basing on the discussion with @arwenhutt ( https://github.com/ucsdlib/damsmanager/issues/289#issuecomment-456912792), is it possible to setup a process or a Jenkins plan to automatically run the program (https://github.com/ucsdlib/cil-sync) every month? Thanks.

**Comment by mcritchlow** [comment]
@lsitu - seems like we should be able to do either. With a recent cron need for ldap syncing, we actually deployed via a Kubernetes CronJob. So I think the general answer is yes, though there are a few scripts in that repo, so perhaps we should document this in that repo in a new or existing ticket?

**Comment by lsitu** [comment]
@mcritchlow That sounds great and we can update README of the repo (https://github.com/ucsdlib/cil-sync) once the CronJob is setup. Let's open a new ticket for this purpose then. Thanks.

**Comment by lsitu** [comment]
@mcritchlow I've created ticket https://github.com/ucsdlib/cil-sync/issues/2 for the Kubernetes CronJob to run the script on the repo https://github.com/ucsdlib/cil-sync and assigned it to you and @rstanonik. Thanks.
