### ISSUE TITLE
Create DAMS events report

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#306]
### Descriptive summary

Create a report from our db that contains events from 11:00 am Feb. 6, 2019 to 11:00 am Feb. 7, 2019

- event ark
- event type
- timestamp
- agent name
- ark of the record "touched"

### Rationale

Within the last 24 hours, a handful of objects became orphaned from the parent [Data from Scripps Research Expeditions](https://library.ucsd.edu/dc/collection/bb29737300)

Longshou was able to piece them back together, but we need to start investigating how this happened. This report is an initial attempt.

**Comment by gamontoya** [comment]
@lsitu High priority task

**Comment by lsitu** [comment]
@gamontoya / @arwenhutt The events report that contains the fields above (.csv format) is ready:
[eventsReport.csv.txt](https://github.com/ucsdlib/damsmanager/files/2845774/eventsReport.csv.txt)

There are a couple of issues I found in the report:
1. The timestamp has 4 hours delayed with the PST time here. For example, I fixed the collection CLR https://library.ucsd.edu/dc/object/bb5021535s at 9:42am yesterday, but it's showing up as `2019-02-07T05:42:20+0000`.
2. The following two records that were pushed for DOI yesterday afternoon (at around 1:44pm and 2:08pm) are credited me as the editor:
https://library.ucsd.edu/dc/object/bb0584631v (DOI push: 2019-02-07T09:44:44+0000)
https://library.ucsd.edu/dc/object/bb5021535s (DOI push: 2019-02-07T10:08:47+0000)

Could we have a ticket to fix it? Thanks.

**Comment by arwenhutt** [comment]
Awesome, thanks Longshou!
But let's hold off on changing anything until we figure out what caused the data loss.  Otherwise it'll get harder to know what we're looking at.

**Comment by arwenhutt** [comment]
@lsitu to double check, does this report include all event metadata for the time period for everything in the DAMS?

**Comment by lsitu** [comment]
@arwenhutt That's all I can get with sparql. So I'll say yes. Just let me know if you need to review events in different date range.

**Comment by lsitu** [comment]
@arwenhutt I think the issue I raised above for the wrong editor credited for DOI update are fixed in PR https://github.com/ucsdlib/damsrepo/pull/79. So fell free to close the ticket now. Thanks.
