### ISSUE TITLE
Excel Ingest Tool - add Person:Advisor & add valid values for Level

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#307]
### Descriptive summary

1. In the Excel standard input template,  add creator role Person:Advisor to the list of valid values
**Rationale**
Approved by DMPS in [dams-metadata issue 107](https://github.com/ucsdlib/dams-metadata/issues/107)

2. Add `"  \Component"` & `"    \Sub-component"` as valid values for "Level"
Valid values should be:
`"Object"`
`"Component"`
`"  \Component"`
`"Sub-component"`
`"    \Sub-component"`
**Rationale**
Currently, the Excel template uses "  \Component" & "    \Sub-component" in Level (for human readability) but DAMS Manager flags them as invalid.  This requires that we edit the Excel templete before ingest.  We should be able to use "Component" & "Sub-component" with or without the spaces and "\"

**Comment by hjsyoo** [comment]
HDSI will need to start using the Person:Advisor role as early as end of spring quarter.

**Comment by lsitu** [comment]
@GregReser Could we prefix double slash `\\` like`\\Component``\\Sub-component` instead of using single slash? With single slash, it will be interpreted as the escape character for control characters as what we've seen in the past.

**Comment by GregReser** [comment]
@lsitu Maybe we could use something else, like this an asterisk
Object
* Component
  * Sub-component

Also allow no spaces or asterisk
Object
Component
Sub-component

**Comment by hjsyoo** [comment]
@GregReser Would it at all be helpful to change the controlled values in the Excel template? For the RDCP side, I think it would be easy enough for us to switch to plain text without the leading slashes. Some folks are still using old templates I've sent out, but we could change them on our end and they'd eventually phase out.

**Comment by GregReser** [comment]
@hjsyoo Yes, if you think having added punctuation is not really helpful.  The template still changes the cell color automatically when Component or Sub-component is selected.

**Comment by GregReser** [comment]
@arwenhutt @remerjohnson @abbypenn93 any thoughts?  Maybe using " \Component" & " \Sub-component" isn't very helpful and we should just use:
Object
Component
Sub-component

**Comment by GregReser** [comment]
@lsitu Let's not change the validation for Object, Component, and Sub-component at this time so we can add Person:Advisor and close this ticket.

Unless there is other feedback, I think we should change the Excel template to remove "/" from Component and Sub-component.  That change wont affect the ingest validation code.

**Comment by hjsyoo** [comment]
The punctuation doesn't help me personally, maybe neither for researchers unfamiliar with our processes. If you want to update that column, please share your latest version of the template. The one I share out to researchers could very well be an older version (2018)!

**Comment by lsitu** [comment]
@GregReser / @hjsyoo Thank you very much for your feedback. I've added Person:Advisor to the Excel Standard InputStream template.
@mcritchlow Basing on our discussions above, I've added Person:Advisor and the PR https://github.com/ucsdlib/damsmanager/pull/313 is ready for review now. Thanks.

**Comment by arwenhutt** [comment]
@GregReser I think updating our template to remove the / from component and sub-component values makes sense.  Thanks!

**Comment by remerjohnson** [comment]
@GregReser I feel like you could retain the color coding (dark to light green I believe?) so it makes sense on our end or to users, which would not affect. Otherwise, yes, I agree we should stick to the plain values.

**Comment by lsitu** [comment]
Thank you all for your feedback. I've updated it to remove the slash from the template used by damsmanager.
