### ISSUE TITLE
Remove 6 components from CCR2 object

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#319]
### Descriptive summary

The following components (metadata and files) should be removed from https://library.ucsd.edu/dc/object/bb3963059d.

1. Jupyter notebook for identifying and extracting the apo clusters (component 10)
2. Jupyter notebook for identifying and extracting the holo clusters (component 11)
3. Jupyter notebook for SASA calculations, distances analyses, and chi angle calculations (component 15)
4. Jupyter notebook for RMSF analysis (component 16)
5. Jupyter notebook for water analysis (component 17)
6. Jupyter notebook for sodium analysis (component 18)

### Related work

Link to related tickets or prior related work here.

**Comment by gamontoya** [comment]
@lsitu Do you have the bandwidth to do this?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll work on it.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo I think we may have to restructure the component orders and re-ingest the files with component index larger that 12. Where can I find the source files for the object? Thanks.

**Comment by hjsyoo** [comment]
@lsitu They're here:
Metadata file location: //rdcp-staging/rdcp-0141-ccr2-landscape/Final_Metadata/
Content files location: //rdcp-staging/rdcp-0141-ccr2-landscape/Final_Files/
Final_Files still contains the component files that should be removed from prod.

**Comment by lsitu** [comment]
@hjsyoo It looks like there are some files in //rdcp-staging/rdcp-0141-ccr2-landscape/file_replace, which were ingested for the object. Should I use those files as well?

**Comment by lsitu** [comment]
Also, I can't find file `ccr2_apo_123_aligned_nopopc.dcd` and `ccr2_holo_234_aligned_nopopc.dcd` in both locations.

**Comment by lsitu** [comment]
Never mind, I found both file ccr2_apo_123_aligned_nopopc.dcd and ccr2_holo_234_aligned_nopopc.dcd in sub-directory.

**Comment by hjsyoo** [comment]
@lsitu I’ve already moved the two files needed from file_replace into Final_Files, so please don’t use that folder. The remaining files in file replace are old versions.

**Comment by lsitu** [comment]
It looks like files `placeholder_text_conda_environment.yml` and `placeholder_text_pip_environment.txt` that we need are still in the `file_replace` folder.

**Comment by hjsyoo** [comment]
No, those were placeholders that we put in temporarily, until the researcher confirmed that the originals were correct. So the files we should use are the ones indicated in the OLR. The OLR is correct with respect to filenames, except for the 6 components that should be removed.

**Comment by lsitu** [comment]
@hjsyoo Okay, I'll use those two files in [ucsdlib/dams-metadata#120](https://github.com/ucsdlib/dams-metadata/issues/120). Yes, you don't need ticketucsdlib/dams-metadata#120 since I have to re-ingest those two files.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo I've deleted all components and files above and restructure those components with index larger than 12. Those files attached to the components restructured are also re-ingested.
I think the restructured object https://library.ucsd.edu/dc/object/bb3963059d is ready for review now.

**Comment by hjsyoo** [comment]
@lsitu Thank you! Looks great.
