### ISSUE TITLE
VRR PDF watermarking: Use python script

### ISSUE THREAD

**Issue by hweng** [ucsdlib/damsmanager#320]
### Descriptive summary

Assess/review the python script, and determine whether it needs to be a python script or if it can be rewritten in java (in dams-manager directly).
If ultimately it does need to be in python, then it needs to be put in version control somewhere, either vendored into dams-manager or otherwise, documented, and setup in our deployment process.

### Related work

- ucsdlib/damspas#654
- ucsdlib/damsmanager#332
- ucsdlib/damsmanager#331

**Comment by lsitu** [comment]
@gamontoya Basing on the discussions on the `#vrr` channel this morning https://ucsdlibrary.slack.com/messages/GA10S5DPW/. I think we may need decisions regarding how the watermark derivatives for PDFs and Images should be created, and `spec` regarding how this process is related to damsmanager and the ingest workflow.

What should be done for this ticket? Thanks.

**Comment by gamontoya** [comment]
@lsitu Let's leave it open and I'll put this on the DAMS Working Group's agenda for discussion this Thursday.

**Comment by jessicahilt** [comment]
We're going to keep the python script and r&d swapping to ruby by the end of the summer. See #623.

**Comment by hweng** [comment]
@lsitu For your question about the command to apply watermark to image. Here is the  basic syntax:  `$COMPOSITE -gravity SouthEast watermark.png input.jpg output.jpg`

There are several options to adjust such as: `$composite -quality 100 -gravity South -density 400 VRR_SCA_watermark.png -resize 500x300 -geometry +100+20 test_image/input.jpg result/output.jpg`

Here is the reference: https://imagemagick.org/Usage/annotating/#wmark_image

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damsmanager](https://github.com/ucsdlib/damsmanager/issues/331)

**Comment by lsitu** [comment]
@mcritchlow I've created the following two PRs to utilize the Python script for PDF watermarking PDF:
https://github.com/ucsdlib/damsmanager/pull/335
https://github.com/ucsdlib/private_config/pull/15

Both PRs are ready for review now. Thanks.
