### ISSUE TITLE
RDCP download counts and view counts are inaccurately reported

### ISSUE THREAD

**Issue by xiw391** [ucsdlib/damsmanager#325]
Descriptive summary and Steps to Reproduce Behavior
DAMS manager (DM) reports download and view counts inaccurately (counts are doubled) and consistently for RDCP components while reporting unique download and view counts accurately. Six tests were run on separate days. All testers shared this behavior:

Tested on Chrome
Clear cache and sign out of DAMS (non-curator mode)
Search for a designated object's ARK in Google. Click on the object URL in search results.
Find the designated component on the page and download the object once.
Repeat for all objects on the test list, on a separate computer. (The number of tests performed per object varied by day.)
Documentation: https://docs.google.com/spreadsheets/d/1vbGlLbAXtCNGCS859SkWuT6CROa9nr6K22PrgsnLY8I/edit#gid=1826356290

2019-4-15: 3 downloads were performed (Two on personal computers, and one on desktop). DM reported 6 downloads and 6 views.
2019-4-16: 2 downloads were performed (One on personal computers, and one on desktop). DM reported 4 downloads and 4 views.
2019-4-17: 1 downloads were performed. (One on desktop) DM reported 2 downloads and 2 views.
2019-4-23: 1 downloads were performed. (One on personal) DM reported 2 downloads and 2 views.

**Comment by gamontoya** [comment]
@lsitu While you did a great job the last time around, it looks like we are still not correctly capturing unique views/downloads.

**Comment by lsitu** [comment]
@hjsyoo / @xiw391 I am not able to access the test documentation https://docs.google.com/spreadsheets/d/1vbGlLbAXtCNGCS859SkWuT6CROa9nr6K22PrgsnLY8I/edit#gid=1826356290. Could you give me access? Thanks.

**Comment by hjsyoo** [comment]
@lsitu For clarification, the unique downloads and views counts were correct. But the total downloads and views counts were twice as large as they should have been. During testing, separate users/computers accessed each object only once per day, so total counts should have been the same as unique counts.

**Comment by lsitu** [comment]
@hjsyoo Thank you so much for the clarification. I will look in to the total count issue. Thanks.

**Comment by lsitu** [comment]
@rstanonik While looking into those records that were tested in https://docs.google.com/spreadsheets/d/1vbGlLbAXtCNGCS859SkWuT6CROa9nr6K22PrgsnLY8I/edit#gid=1826356290, I found all trequests were logged twice in the weblog. I tested downloading files in object bb8260985q several times  and see all those download requests were logged twice in the weblog. Is it possible to eliminate the duplicate lines from weblog? Thanks.

Here are the logs with object bb8260985q that were tested by @hjsyoo 's group in Apr. 15:
```
Apr 15 14:36:37 library apache[20795]: library.ucsd.edu 137.110.46.0 - - [15/Apr/2019:14:36:37 -0700] "GET /dc/object/bb8260985q/_4_1.gz/download HTTP/1.1" 200 261189 "https://library.ucsd.edu/dc/object/bb8260985q" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
Apr 15 14:36:37 library apache[20796]: library.ucsd.edu 137.110.46.0 - - [15/Apr/2019:14:36:37 -0700] "GET /dc/object/bb8260985q/_4_1.gz/download HTTP/1.1" 200 261189 "https://library.ucsd.edu/dc/object/bb8260985q" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
Apr 15 14:36:45 library apache[20795]: library.ucsd.edu 24.215.142.16 - - [15/Apr/2019:14:36:44 -0700] "GET /dc/object/bb3618599q/_4.jpg HTTP/1.1" 200 13196 "https://library.ucsd.edu/speccoll/dswenttowar/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36"
Apr 15 14:36:45 library apache[20796]: library.ucsd.edu 24.215.142.16 - - [15/Apr/2019:14:36:44 -0700] "GET /dc/object/bb3618599q/_4.jpg HTTP/1.1" 200 13196 "https://library.ucsd.edu/speccoll/dswenttowar/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36"
```

**Comment by rstanonik** [comment]
John found and fixed it, so shouldn't have duplicate entries in the future.  Fixing past logs might be possible, but might confused splunk.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo Should we leave it as it for now?

**Comment by hjsyoo** [comment]
@lsitu Sure, if the doubling issue has been resolved, then we'll do some more testing and let you know if we find anything else. Thank you!

**Comment by gamontoya** [comment]
@lsitu Thank you!
