### ISSUE TITLE
Replace invalid personalName ARKs in History of the UC San Diego Visual Arts Department

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#329]
### Descriptive summary

This is a high priority because the collection is public.

In the History of the UC San Diego Visual Arts Department, some personalName properties for "Lonidier, Fred 1942-" were created with an invalid ARK which results in the name and role not displaying:
<dams:personalName rdf:resource="http://library.ucsd.edu/ark:/20775/75f9542697244934y"/>

### Task
FOR every object in History of the UC San Diego Visual Arts Department (https://library.ucsd.edu/dc/collection/bb5533548r)
IF  personalName ARK == "75f9542697244934y"
REPLACE with "bb2700755z"

Old: 
dams:personalName rdf:resource="http://library.ucsd.edu/ark:/20775/75f9542697244934y"
Display result = null

New:
dams:personalName rdf:resource="http://library.ucsd.edu/ark:/20775/bb2700755z"
Display result: Lonidier, Fred 1942-

**Comment by gamontoya** [comment]
@hweng Do you have time to work on this high priority ticket?

**Comment by hweng** [comment]
@gamontoya Yes, I can take it.

**Comment by hweng** [comment]
@GregReser @gamontoya The objects in History of the UC San Diego Visual Arts Department have been updated to fix dams:personalName.  And the solr index finished updating too.

I've seen the Display result: "Lonidier, Fred 1942-"
For example: https://library.ucsd.edu/dc/object/bb15403545, 
could you take a look if it looks good to you too?

**Comment by GregReser** [comment]
@hweng looks good.  Thank you
