### ISSUE TITLE
VRR image watermarking: Use ImageMagick

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#331]
### Descriptive summary

Use ImageMagick to create watermarked images for VRR. 

### Related ticket

ucsdlib/damsmanager#320 

### Huawei notes

@lsitu For your question about the command to apply watermark to image. Here is the basic syntax: $COMPOSITE -gravity SouthEast watermark.png input.jpg output.jpg

There are several options to adjust such as: $composite -quality 100 -gravity South -density 400 VRR_SCA_watermark.png -resize 500x300 -geometry +100+20 test_image/input.jpg result/output.jpg

Here is the reference: https://imagemagick.org/Usage/annotating/#wmark_image

### Related work

- ucsdlib/damspas#654
- ucsdlib/damsmanager#332
- ucsdlib/damsmanager#320

**Comment by lsitu** [comment]
@gamontoya / @mdpeters Do we have the watermark image that can be used for image watermarking? Also, do we need to watermark all derivatives like image-large, image-huge, image-service, image-preview, image-thumbnail, image-icon? And how about the watermark image use for for each size? Thanks.

**Comment by mdpeters** [comment]
![vrr_sca_watermark](https://user-images.githubusercontent.com/22665238/59522445-939e5d00-8e83-11e9-8f95-5b8afae0e529.png)

@lsitu watermark image above. I think it should only be necessary for the larger images sizes (probably image-service and larger) and for the zoom tiles.

**Comment by lsitu** [comment]
@gamontoya / @arwenhutt Which watermarking derivative are we going to use for zoom tiles creation? Should we need to create a new derivative for it or use image-huge instead?

**Comment by gamontoya** [comment]
@lsitu What is image-huge? Does that exist already?

**Comment by lsitu** [comment]
@gamontoya It's a derivative added for DAMS4 but we haven't use it yet. And yes, it's created on ingest for every image file with size 1600x1600.

**Comment by gamontoya** [comment]
@lsitu That makes sense. I say go ahead and use that derivative.

**Comment by gamontoya** [comment]
@lsitu Should this ticket be open?

**Comment by lsitu** [comment]
@gamontoya Yes. I am reopening it now.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/336 for image watermarking support with ImageMagick convert. It's ready for review now. Thanks.
