### ISSUE TITLE
Give dams-curator group access to the DAMS Collection Status Report and File Report Tool

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#349]
### Descriptive summary

Please update DAMS Manager to give the `dams-curator` group access to the [DAMS Collection Status Report](https://library.ucsd.edu/damsmanager/collectionStatusReport.do)

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/350 for it. Thanks.

**Comment by gamontoya** [comment]
@lsitu Sorry about this Longshou, but it needs to be set for dams-curators since there are others that shouldn't be editors but want access to the reports. Is this easy re-do?

**Comment by gamontoya** [comment]
@lsitu Also, can add dams-editors (not curators) to the file report tool 

https://library.ucsd.edu/damsmanager/fileReport.do

**Comment by lsitu** [comment]
@gamontoya Yes, will do.

**Comment by lsitu** [comment]
@gamontoya / @mcritchlow I've added dams-curator group for accessing the collection status report. For the file report tool https://library.ucsd.edu/damsmanager/fileReport.do, dams-editor group should have access to it at this time.

**Comment by gamontoya** [comment]
@lsitu Does this take a deploy to prod before Matt P. can test?

**Comment by lsitu** [comment]
@gamontoya I think we can deploy it along with damsmanger [Release 2.72](https://github.com/ucsdlib/damsmanager/issues/339) once the PR https://github.com/ucsdlib/damsmanager/pull/350 is merged.

**Comment by gamontoya** [comment]
@lsitu Okay, just make sure both the Collection Status and File Report tools are in this code update. Thank you!

**Comment by lsitu** [comment]
@gamontoya No problem. I am working on https://github.com/ucsdlib/damsmanager/issues/351 for Collection Status report now.

**Comment by cgarciaspitz** [comment]
Has this gone into effect? If so, how do I login?

**Comment by lsitu** [comment]
@cgarciaspitz Yes. Here are the urls to login the Collection Status Report and File Report tool:
https://library.ucsd.edu/damsmanager/collectionStatusReport.do
https://library.ucsd.edu/damsmanager/fileReport.do
