### ISSUE TITLE
Improve output  of the DAMS Collection Status Report

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#351]
### Descriptive summary

Determine best way to accurately report a recently release/added collection. A collection should only report itself as new once only. 

- https://library.ucsd.edu/damsmanager/collectionStatusReport.do

### Rationale

Sometimes a collection is listed as newly released when it was released months ago.

Per Longshou:

> So collection bb1745304h should be just release to public last month. But it looks like it was release at 2019-06-05T10:31:48+0000 as well. So maybe someone performing a reverse release? Collections with new object added should show up in group Collections with objects added. The Collection Release group will show those collections that were release June 1 - June 30 . Since collection has a release bb1745304h timestamp 2019-06-14T08:21:54+0000, it will show up in the group Collection Release. The event shows Greg run the release at that time. Maybe we can open a ticket so that we can inspect the results and make the rule change for it when needed.
 
### Expected behavior
Collections should only show up in a report once for a given month.

![release](https://user-images.githubusercontent.com/4314914/61498098-b76b2c00-a976-11e9-9698-4bd336f0f4a9.png)

In the above example, 4 of the 5 listed new collections are not new. They were released months ago so something is triggering them to be listed again as new.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/352 that will prevent those collections that were released in the past from adding the record released event again so that it won't be reported more than once.

**Comment by lsitu** [comment]
@gamontoya The PR https://github.com/ucsdlib/damsmanager/pull/352 won't fix the current collection status report but it will prevent new released collections from reporting more than once in the feature. Does it sounds good?

**Comment by gamontoya** [comment]
@lsitu Yes, sounds great!
