### ISSUE TITLE
Add component to NAAMES 3 object

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#354]
### Descriptive summary

In the NAAMES 3 object, https://library.ucsd.edu/dc/object/bb7512314s, a new component (#33) should be added to the end of the component list (currently n=32).

Component Title: Raw data for NAAMES3 LS
File location: \rdcp-0112-naames\Final_Files_N3\NA3-raw\LS.zip
File use: data-service

### Related work
https://lib-jira.ucsd.edu:8443/browse/CPP-112

**Comment by gamontoya** [comment]
@lsitu Can you please add the component?

**Comment by lsitu** [comment]
@gamontoya Sure. Will do.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo  The new component `Raw data for NAAMES3 LS` for object [NAAMES 3](https://library.ucsd.edu/dc/object/bb7512314s) is added and it's file is ingested on prod. It's ready for review now  Thanks.

**Comment by hjsyoo** [comment]
@lsitu @gamontoya Perfect, and thank you for the speedy turnaround!
