### ISSUE TITLE
VRR Watermarking at ingest not working on production

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#358]
### Descriptive summary
The process for ingesting pdf's with generation of watermarked service files that was tested and works in staging does not work in production.  

I ingested a VRR collection - [Layard papers](https://library.ucsd.edu/dc/collection/bb24279581) to production with file use value of "document-source" and the "Generate watermarked document and image service files" option selected -- watermarked service images not generated.

Replicated with a second test ingest on production (derivatives not generated): 
- [Item 1](https://library.ucsd.edu/dc/object/bb27693246)
- [Item 2](https://library.ucsd.edu/dc/object/bb21208532)

Also duplicated the test ingest in staging (derivatives were created):
- [Item 1](https://librarytest.ucsd.edu/dc/object/bd4015199g)
- [Item 2](https://librarytest.ucsd.edu/dc/object/bd0772851r)

**Comment by lsitu** [comment]
@rstanonik I found the following error in the log:
java.lang.IllegalArgumentException: Can't find command: /usr/local/bin/watermark.sh

It looks like that the watermark.sh program from github https://github.com/ucsdlib/watermark hasn't been on prod installed yet. Could you take a look? Thanks.

**Comment by rstanonik** [comment]
@lsitu  I installed it on lib-hydratail-prod just now.
Please try again.
Ron

**Comment by arwenhutt** [comment]
@rstanonik & @lsitu I retried the test ingest but still no derivatives:
https://library.ucsd.edu/dc/object/bb6899053h
https://library.ucsd.edu/dc/object/bb7547524c

**Comment by rstanonik** [comment]
@lsitu damsmanager.properties in prod doesn't have any configuration information about watermark.

**Comment by rstanonik** [comment]
Looks like I need to jenkins deploy private_config to prod.  Let me know if that sounds correct.

**Comment by lsitu** [comment]
@rstanonik Could you check whether the following lines are there https://github.com/ucsdlib/private_config/blob/develop/damsmanager/production/damsmanager.properties#L113-L116? I think we just redeployed it from master last week.

**Comment by lsitu** [comment]
@rstanonik I think you've setup a plan in Jenkins for it. And I recalled that you mentioned it was setup to deploy from development branch in the past. But last weekTuesday you talked about to deploy it from master branch so I merged the codes to master and you'd deployed it https://ucsdlibrary.slack.com/archives/C04R0LJSU/p1565119925065100.

**Comment by rstanonik** [comment]
My mistake.
I installed on lib-hydratail-prod, but damsmanager in production runs on lib-ingest.
I installed on lib-ingest just now.

Please try again.

Ron

**Comment by lsitu** [comment]
Thanks @rstanonik . @arwenhutt Could you try it again?

**Comment by arwenhutt** [comment]
Yay - it seems to be working now. 
@lsitu how can we get the watermarked service files generated for the Layard collection https://library.ucsd.edu/dc/collection/bb24279581

**Comment by arwenhutt** [comment]
@lsitu we need the watermarked service files generated for the Layard collection (the ingest which led to this ticket) - can you do that?

**Comment by lsitu** [comment]
@arwenhutt Do you mean it's still not watermarking as expected?

**Comment by arwenhutt** [comment]
@lsitu when I do a new ingest it watermarks as expected, but I ingested a collection (Layard) before the code was added to production on 8/12.  At that point the derivative creation did not work so the 1139 items ingested do not have watermarked service files.  If you click on one of the items you will see that there is no pdf available, and if you look at the metadata there is no file generated at the time of ingest.

**Comment by lsitu** [comment]
@arwenhutt I am not sure what's the better way to fix it in this case but re-ingest the collection with the ARK for the objects ingested (add `ARK` column to the spreadsheet) .

**Comment by arwenhutt** [comment]
@lsitu Ah, so if I add an ARK column and use the excel ingest tool it won't create duplicate records?  Would I replace the unique ID with the ARK column or include both?

**Comment by lsitu** [comment]
@arwenhutt It won't create duplicate object as long as you use the same ARK. We need both the unique ID and the `ARK` column.

**Comment by arwenhutt** [comment]
@lsitu I added an ARK column to the ingest spreadsheet for two of the test objects, and then re-imported but got "execution failed"
the ingest file and damsmanager reports are here: rdcp-staging\zz_Test\vrr-test

**Comment by lsitu** [comment]
@arwenhutt Could you use the ARK url in the `ARK` column like `http://library.ucsd.edu/ark:/20775/bb27693246`,
`http://library.ucsd.edu/ark:/20775/bb21208532`? Thanks.

**Comment by arwenhutt** [comment]
@lsitu woohoo!  it worked!
