### ISSUE TITLE
Add more component specificity to RDCP Download report

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#362]
### Descriptive summary

In https://library.ucsd.edu/damsmanager/statsRdcpDownload.do, downloads are currently reported for each component, by component title. There are a non-trivial number of objects, however, that have more than one child component with the same title. For example, https://library.ucsd.edu/dc/object/bb7920789g has 12 "Readme", 10 "Raw data" and 10 "Image Analysis" child components. In the download report, we cannot distinguish between these components. One way to help identify the exact component is to include in the component column the parent component title, since the combined names, [ParentComponentTitle]:[ChildComponentTitle] will be unique within each object. So for the above example, Component 2 would be titled "Code: Readme", followed by "Code: MATLAB scripts", and so on.

### Related work

Link to related tickets or prior related work here.

**Comment by jessicahilt** [comment]
Can you take a look at this and see what you think as far as level of effort?

**Comment by lsitu** [comment]
@jessicahilt Sure. I think it's doable. I'll see how to build the component title.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/370 for it. Thanks.

**Comment by gamontoya** [comment]
@hjsyoo @abbypenn93 Are you able to confirm that this is fixed?

**Comment by hjsyoo** [comment]
Looks good on prod. Thanks, @lsitu .
