### ISSUE TITLE
Batch Export uses old Creative Commons license boilerplate text

### ISSUE THREAD

**Issue by abbypenn93** [ucsdlib/damsmanager#367]
### Descriptive summary

Production and Staging Batch Export replaces Creative Commons license boilerplate text with outdated text. Note that I originally blamed Batch Edit.

For example, the **Copyright** section looks like this in the Production object:

![image](https://user-images.githubusercontent.com/48562617/65055596-533bf880-d924-11e9-8737-297351a67d00.png)

but the exported object looks like this in Excel:

![image](https://user-images.githubusercontent.com/48562617/65055576-49b29080-d924-11e9-806a-4b3d37f8fe31.png)

### Rationale

Update Creative Commons license boilerplate text utilized by Batch Export to latest Creative Commons license text.

### Expected behavior

Batch Export will retain existing in-object Creative Commons license boilerplate text when generating an output file.

### Actual behavior

Batch Export will retain existing in-object Creative Commons license boilerplate text when generating an output file.

### Steps to reproduce the behavior

1. Run Batch Export on https://library.ucsd.edu/dc/object/bb4782925w
2. Review text in copyrightNote field.

**Comment by lsitu** [comment]
@abbypenn93 I think the context of the ticket is not correct for Batch Export. Batch Export will only export the metadata from the triplestore without altering the values. The issue here for the CC license template is altered by damspas UI display and Batch Export won't retrieve display values from damspas UI.

Instead of requiring the change in Batch Export, there are two tickets may needed:
1. Update Excel Standard InputStream in DAMS Manager to use the expected CC copyright Use Constrain(s) template.
2. Revert the codes on damspas that apply the CC template for UI display.

**Comment by lsitu** [comment]
Maybe we need global data cleanup to change the existing old Use Constraint(s)  (`dams:copyrightNote`) to the new CC copyright Use Constraint(s) template?

**Comment by abbypenn93** [comment]
Ah, I see. Now I mistakenly blamed Batch Export. :)
Let's pause while Arwen and I take a closer look.

**Comment by arwenhutt** [comment]
@lsitu I think your suggestions make sense, to confirm that includes:

1. Global data cleanup to change the existing old Use Constraint(s) (dams:copyrightNote) to the new CC copyright Use Constraint(s) template for objects with a cc license
2. Update Excel Standard InputStream in DAMS Manager to use the expected CC copyright Use Constrain(s) template on object creation
3. Revert the codes on damspas that apply the CC template for UI display.

**Comment by gamontoya** [comment]
@lsitu Is this ticket in progress?

**Comment by arwenhutt** [comment]
@gamontoya @lsitu 
a note that we've (@abbypenn93 @hjsyoo @remerjohnson) found some other bugs related to the boilerplate text - we're investigating more at the moment to try and get a little more information about when problems are occurring

**Comment by lsitu** [comment]
@gamontoya @arwenhutt No. I don't think it's in progressing. I think it's not the Batch Export issue itself but related to damspas UI display and the copyright metadata in Excel Standard Input tool. I think we may need decisions to move it forward.

**Comment by jessicahilt** [comment]
Global data cleanup to change the existing old Use Constraint(s) (dams:copyrightNote) to the new CC copyright Use Constraint(s) template for objects with a cc license #386

Update Excel Standard InputStream in DAMS Manager to use the expected CC copyright Use Constrain(s) template on object creation #387

Revert the codes on damspas that apply the CC template for UI display. #388

**Comment by arwenhutt** [comment]
@abbypenn93 @hjsyoo All of the tasks/tickets listed above have been completed and I think this is fixed!
