### ISSUE TITLE
Searchable Item displays count of 0

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#369]
### Descriptive summary

In the DAMS Collections report (collectionsReport.do), column D ("Searchable Items") reports a 0 on some RDCP collections (see screenshot)

It is possible that this is a special characters encoding bug.

![rdcp_collections_report](https://user-images.githubusercontent.com/4314914/66227014-0df02880-e691-11e9-996f-3608eb1d01ff.png)

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/373 to correct the Searchable Item count issue, which is caused by title encoding and spaces in titles. And I also fixed the corrupted diacritics in the Excel exported that I found. It's ready for review now. Thanks.
