### ISSUE TITLE
 DAMS Collection Status Report not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#382]
### Descriptive summary

When trying to run a report using the DAMS Collection Status Report, user receives the following error:

`Error: Error on line -1 of document : Premature end of file. 
Nested exception: Premature end of file.`

- https://library.ucsd.edu/damsmanager/collectionStatusReport.do

**Comment by arwenhutt** [comment]
@gamontoya @lsitu I was just able to generate a report for September, and then one for October and November.  Not sure if this is relevant to tracking down the bug, or it's because something was done (super speedy) to fix it.

**Comment by lsitu** [comment]
@arwenhutt Are you still seeing the error now? I tried to generate and export the report for the following periods but I don't see the error:
2019-09-01 to 2019-09-30
2019-10-01 to 2019-10-31
2019-11-01 to 2019-11-30
2019-12-01 to 2019-12-31

**Comment by arwenhutt** [comment]
@lsitu I just tried:
2019-08-01 to 2019-12-17 and got the same error

**Comment by lsitu** [comment]
@arwenhutt I see the error now. It seems like error just occurred for August 2019, which is cause by logging some error ingest. We may need to look in to the database for the error evens. Do you know what's going wrong with prod ingest during that time?

**Comment by arwenhutt** [comment]
@lsitu I don't know.  Looking through past tickets this seems like a possibility though: https://github.com/ucsdlib/damsmanager/issues/358

**Comment by lsitu** [comment]
@arwenhutt Thanks. Maybe we need to export all events in the events database for August 2019 to see what's going wrong. 
@rstanonik @jgorney Is it possible to export the event metadata from the evens_triples table for period 08/01/2019 to 08/25/2019? Thank you.

**Comment by jgorney** [comment]
Yes, I can export that data.  I'll let you know when it's ready.

**Comment by jgorney** [comment]
In preparing to export this data, I realized that the events_triples table does not have time stamps.  Unless there is another way to identify which records were added when, I'm going to load (in a separate area) a backup file from Aug 1 2019 and a backup file from Sep 1 2019 (I don't have any in between for that long ago), and export the files added after Aug 1.  I hope this will be ok!

**Comment by jgorney** [comment]
One limitation of this method, btw, is that without a timestamp on the records in events_triples, I will not be able to identify records created before Aug 1 that were updated during Aug 2019.  @lsitu , is there a way to identify when events_triples records were modified ? 

Has adding a timestamp to tables dams_triples and events_triples tables been considered?

**Comment by lsitu** [comment]
@jgorney How about export the results basing on the `ID` column? We may not need to exact results. So if we can find out the sequence/range of the ids created over that period should help. Thanks.

**Comment by jgorney** [comment]
Hi @lsitu - that was my plan.  I've now extracted the events_triples records with ID > (max(ID) at 2:00 AM on Aug 1 2019) and ID < (max(ID) at 2:00 AM on Sep 1 2019).  

The file is in CSV format (comma delimited).

The zipped file is about 6 MB.  Is it too big to attach here?

**Comment by lsitu** [comment]
@jgorney Yep, it looks like it's too big to attached here. Can you put it in \\darry\dams_staging\collection_report? Thanks.

**Comment by jgorney** [comment]
This export was made from a backup made on Sep 1, 2019.  I can create the same export, but from the current production database.  It will be the same set of records (same IDs) in this initial file, but maybe there are differences because of any updates?

I just transferred the file - let me know if you can see it.  Also let me know if you want me to produce the report from the current production db.

**Comment by lsitu** [comment]
@jgorney That works, Thank you very much.

**Comment by lsitu** [comment]
@arwenhutt It looks like the ARK minter was down in the early morning of August 21, 2019, which recorded errant message `subject` in the evens triplestore like:
```
<http://library.ucsd.edu/ark:/20775/EN">
<html><head>
title>
head><body>
h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
p>
<hr>
address>
html>>
```
I think your team should got some failed ingest that night. And I need to update my codes to ignore those errant event IDs for collection status report to avoid the error. With that said, some records created that night will be missed from the collection status report. Does this work for you?

**Comment by arwenhutt** [comment]
@lsitu I'm fine with the collection status report being a few records off for that night.

**Comment by arwenhutt** [comment]
@lsitu I'm fine with the collection status report being a few records off for that night.

**Comment by lsitu** [comment]
@arwenhutt I've added the PR https://github.com/ucsdlib/damsmanager/pull/384 for it. But we only can test it on prob to see how it goes.

**Comment by arwenhutt** [comment]
reopening for testing

**Comment by arwenhutt** [comment]
@lsitu @gamontoya verified this is working on production 👍
