### ISSUE TITLE
CIL Harvesting - update to notification email addresses

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#383]
### Descriptive summary
Update the email addresses for the "CIL Harvesting Status Report"

Please remove: ahutt@ucsd.edu

And add: Digital_Object_Metadata_Unit@ucsd.edu

### Rationale
This will enable everyone in the unit to receive notification without requiring future edits when new staff join.

### Expected behavior
Email notifications should be sent to the Digital Object Metadata Unit email and Ho Jung Yoo

### Related
#316 
#289

**Comment by arwenhutt** [comment]
@jessicahilt & @gamontoya 
Hopefully this has a low LOE (and will save future hassle with updating the list as staffing changes.) 
Thanks!

**Comment by gamontoya** [comment]
@jessicahilt Can Vivian do this?

**Comment by lsitu** [comment]
@jessicahilt @gamontoya It's a configuration issue in damsmanager and I'll take care of it.

**Comment by gamontoya** [comment]
@lsitu Thank you!

**Comment by arwenhutt** [comment]
reopening for testing/verfication

**Comment by arwenhutt** [comment]
@lsitu is there a way we can test this? Or do we just wait until the next harvest to verify?

**Comment by lsitu** [comment]
@arwenhutt No. But I am running a CIL Harvest process on staging now and the group members in Digital_Object_Metadata_Unit@ucsd.edu should be able to receive email notification once it's done. I'll let you and @abbypenn93 know once it's ready for you to review.

**Comment by arwenhutt** [comment]
@lsitu perfect, thanks!

**Comment by arwenhutt** [comment]
@lsitu I left the "ad" off the email address -- it should have been "Digital_Object_Metadata_Unit@AD.UCSD.EDU"

**Comment by arwenhutt** [comment]
@lsitu I received a harvesting status report via the unit email address -- definitely working!
