### ISSUE TITLE
Update Excel Standard InputStream in DAMS Manager to use the expected CC copyright Use Constrain(s) template on object creation

### ISSUE THREAD

**Issue by jessicahilt** [ucsdlib/damsmanager#387]
### Descriptive summary

Update Excel Standard InputStream in DAMS Manager to use the expected CC copyright Use Constrain(s) template on object creation

### Related work
Batch Export uses old Creative Commons license boilerplate text #367
Global data cleanup to change the existing old Use Constraint(s) (dams:copyrightNote) to the new CC copyright Use Constraint(s) template for objects with a cc license #386

**Comment by lsitu** [comment]
@arwenhutt I think we should move the copyright boilerplate metadata cleanup work to be done and QA on prod if overall looks good on staging. What do you think?

**Comment by arwenhutt** [comment]
@lsitu 
@abbypenn93 tested the import scenarios outlined in: https://github.com/ucsdlib/damsmanager/issues/386#issuecomment-579494388 and they all worked as expected.

But we noticed an issue when ingesting a batch of records, the records created had an empty dams:copyright property: 
`    <dams:copyright><dams:Copyright/></dams:copyright>`

Here's the batch export for the files (it's rdf but I changed the extension so github would allow it as an attachment): 
[batchExport-1514851669-rdf-.txt](https://github.com/ucsdlib/damsmanager/files/4227218/batchExport-1514851669-rdf-.txt) 

We also found examples of this empty tag in records created prior to this release.  
I believe this is impacting UI functionality (I described this more in: https://github.com/ucsdlib/damsmanager/issues/388#issuecomment-588410352

**Comment by lsitu** [comment]
@arwenhutt Thanks. I think it should be an existing bug that wasn't found. Could you attached the Excel source file that was used for ingest so that I can take a look?

**Comment by arwenhutt** [comment]
@lsitu I've created the new ticket and added the excel source file there #402 
With that in a separate ticket, I think we can close this one.

**Comment by lsitu** [comment]
@arwenhutt Thanks. I am on that new ticket now.

**Comment by arwenhutt** [comment]
@lsitu - @abbypenn93 verified this on production ✔️
