### ISSUE TITLE
Event metadata missing from object records

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#392]
### Descriptive summary
Some object records are missing event metadata.   

Examples: 
- https://library.ucsd.edu/dc/object/bb1199538d 
- https://library.ucsd.edu/dc/object/bb7104020x 

These records have only one event at the object level, of type "record edited" 
They should have at least two events, "record created" and "record edited," and possibly more depending on the records event history.

**Comment by lsitu** [comment]
@mcritchlow I've added MR https://github.com/ucsdlib/damsmanager/pull/397 to retain the events metadata. It's ready for review now. Thanks.

**Comment by arwenhutt** [comment]
@lsitu Can you give us some information about why event data was missing, and what conditions causedit?  also when the relevant code was deployed?

This will help us with figuring out how to test and give us an idea for how many records may have been affected.

**Comment by lsitu** [comment]
@arwenhutt I think the major reason is that we failed to pass the curator name over to the backend damsrepo, and damsrepo just use an empty ark to create the event for the user. The codes are deployed to staging and I think you can test it now:
1. Ingest some new objects and validate events.
2. Batch overlay the objects and validate all events again.
3. Test RDF Import and validate events
...

**Comment by arwenhutt** [comment]
@lsitu does that mean it's related to https://github.com/ucsdlib/damsmanager/issues/393 ?

**Comment by arwenhutt** [comment]
@lsitu 
I tested ingest, batch overlay (3 times) for batch of objects (test ah1) + single item edit for 1 of the items.  I've reviewed the events for the single item carefully and they look correct (number, type) - also reviewed a sample of items from the rest of the batch and they look good.

**Comment by arwenhutt** [comment]
@lsitu verified on production ✔️
