### ISSUE TITLE
empty dams:copyright property created on ingest

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#402]
### Descriptive summary
We've found many examples of objects with an empty dams:copyright property
`<dams:copyright><dams:Copyright /></dams:copyright>`

in some cases this is the only copyright info in the record, sometimes it is in addition to a populated copyright property.  

This was identified during testing of release candidate 2.77 on staging, but also is seen in production objects ingested with previous releases. 

This seems to also be affecting display, with objects sometimes not displaying copyright info (use, status, constraints on use) in the UI.  It seems that:
-  when the empty block is before the correct dams:copyright block in the rdf, not text is displayed in the UI
-   when the correct dams:copyright block is before the empty block in the rdf, the text is displayed
and since rdf isn't ordered, the order of the rdf can change when it's served up, thus the inconsistent results.

### Example:
This collection of objects was ingested at the end of last week.  On nothing the issues, we exported the metadata:

- ingest file: [Revelle_OLR_Batch1.xlsx](https://github.com/ucsdlib/damsmanager/files/4227724/Revelle_OLR_Batch1.xlsx)
- rdf export of objects: [batchExport-1514851669-rdf-.txt](https://github.com/ucsdlib/damsmanager/files/4227650/batchExport-1514851669-rdf-.txt)
- excel export of objects: [batchExport-1514346373.xlsx](https://github.com/ucsdlib/damsmanager/files/4227649/batchExport-1514346373.xlsx) 

*note that the items were subsequently edited so the collection could be reviewed by data providers, and so the records in the dams have been manually cleaned up and the empty properties removed.  The exports attached were made before any editing and show the records as they were created on ingest.

**Comment by lsitu** [comment]
@arwenhutt I see column `Copyright   status` and `Copyright holder` are there in the ingest metadata, which may cause the confusing. At this time, the batch editing/overlay tool expects the copyrights to be captured from the spreadsheet while the batch ingest expect it from the Excel InputStream form, which causing the trouble.
Would you like me to just ignore all fields related to copyright and `Copyright holder` for new object ingest now?

**Comment by arwenhutt** [comment]
@lsitu ah! I totally missed that.  I just looked at some objects with the blank copyright that had been ingested into production and their spreadsheets have the same columns.  

hmmm, since the batch overlay can import those fields, how difficult would it be to have the excel input stream work the same way - use information from the spreadsheet instead of the form?

**Comment by lsitu** [comment]
@arwenhutt It won't be hard but if we want to move forward with the deployment now, I think we can simply fix the empty copyright element issue now and then made the improvement for ticket [Move rights and access controls into spreadsheet](https://github.com/ucsdlib/damsmanager/issues/265) in the next step, which may need some discussions. Or would you like to hold on the new release and wrap up the ticket now?

**Comment by arwenhutt** [comment]
@lsitu I think the only reason we might consider holding the new release is if the interim fix was a lot of work or would make it a lot harder to move rights into the spreadsheet in the future.  

But it sounds like it probably isn't and doesn't, so...
> ignore all fields related to copyright and Copyright holder for new object ingest
sounds like the best plan!

**Comment by lsitu** [comment]
@arwenhutt Yes, it's a simple fix.

**Comment by arwenhutt** [comment]
@lsitu great!

**Comment by lsitu** [comment]
@arwenhutt @mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/403 to fix the empty copyright element problem. It's ready for review now. Thanks.

**Comment by lsitu** [comment]
@arwenhutt The changes in PR https://github.com/ucsdlib/damsmanager/pull/403 to staging is deployed to staging, which will fix the empty Copyright element in Excel InputStream. Could you test it on staging? Thank you.

**Comment by arwenhutt** [comment]
@lsitu this looks good! I checked all the values we use in those fields and none of the records created have an empty copyright element.

**Comment by arwenhutt** [comment]
reopening for production verification

**Comment by arwenhutt** [comment]
@lsitu verified on production ✔️
