### ISSUE TITLE
Export master files from Spanish Civil War Children's Drawings collection for Starlight exhibit

### ISSUE THREAD

**Issue by mdpeters** [ucsdlib/damsmanager#404]
### Descriptive summary

Please export the object master files for items belonging to the collection https://library.ucsd.edu/dc/collection/bb4540678g to the starlight staging space in \\lib-storage.ucsd.edu\starlight-upload\sw_children_drawings\

### Rationale

Prep for ingest into the Starlight exhibit system

**Comment by lsitu** [comment]
@rstanonik I don't have write access to \lib-storage.ucsd.edu\starlight-upload\sw_children_drawings\, and all 634 tiff files in [Spanish Civil War Children's Drawings collection](https://library.ucsd.edu/dc/collection/bb4540678g) are exported to \\darry\dams_staging\starlight-upload\sw_children_drawings now. However. Could you help us copy all files in `\\darry\dams_staging\starlight-upload\sw_children_drawings` to `\lib-storage.ucsd.edu\starlight-upload\sw_children_drawings\`? Thank you.

**Comment by lsitu** [comment]
@rstanonik Have you got a chance to copy the files in \\darry\dams_staging\starlight-upload\sw_children_drawings to \lib-storage.ucsd.edu\starlight-upload\sw_children_drawings\? Thanks.

**Comment by gamontoya** [comment]
@rstanonik Hi Ron -- please note that I'm running the copy at this time. Thank you though!

**Comment by rstanonik** [comment]
Oops, me too.

**Comment by rstanonik** [comment]
And I gave @lsitu access to \lib-storage.ucsd.edu\starlight-upload

**Comment by gamontoya** [comment]
Ron is running this after all.

**Comment by rstanonik** [comment]
The copy is done

**Comment by gamontoya** [comment]
@mdpeters @lsitu Ron's work is complete.
